
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { accessibilityOutline } from "ionicons/icons";

addIcons({"accessibility-outline": accessibilityOutline });

export let iconAccessibilityOutline = "accessibility-outline";
