
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { addSharp } from "ionicons/icons";

addIcons({"add-sharp": addSharp });

export let iconAddSharp = "add-sharp";
