
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { addCircleOutline } from "ionicons/icons";

addIcons({ addCircleOutline });

export let iconAddCircleOutline = addCircleOutline;
