
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { airplaneSharp } from "ionicons/icons";

addIcons({ airplaneSharp });

export let iconAirplaneSharp = "airplaneSharp";
