
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { airplaneOutline } from "ionicons/icons";

addIcons({"airplane-outline": airplaneOutline });

export let iconAirplaneOutline = "airplane-outline";
