
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { airplaneSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ airplaneSharp });

export let iconAirplaneSharp = airplaneSharp;
