
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { alarmSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ alarmSharp });

export let iconAlarmSharp = alarmSharp;
