
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { alarmOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ alarmOutline });

export let iconAlarmOutline = alarmOutline;
