
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { albumsOutline } from "ionicons/icons";

addIcons({ albumsOutline });

export let iconAlbumsOutline = "albumsOutline";
