
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { albumsOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ albumsOutline });

export default albumsOutline;
