
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { albumsSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ albumsSharp });

export default albumsSharp;
