
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { albumsSharp } from "ionicons/icons";

addIcons({"albums-sharp": albumsSharp });

export let iconAlbumsSharp = "albums-sharp";
