
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { alertSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ alertSharp });

export let iconAlertSharp = alertSharp;
