
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { alertCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ alertCircleSharp });

export default alertCircleSharp;
