
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { alertCircleOutline } from "ionicons/icons";

addIcons({"alert-circle-outline": alertCircleOutline });

export let iconAlertCircleOutline = "alert-circle-outline";
