
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { alertOutline } from "ionicons/icons";

addIcons({ alertOutline });

export let iconAlertOutline = alertOutline;
