
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { alertOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ alertOutline });

export let iconAlertOutline = alertOutline;
