
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { americanFootball } from "ionicons/icons";

addIcons({ americanFootball });

export let iconAmericanFootball = americanFootball;
