
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { americanFootballSharp } from "ionicons/icons";

addIcons({ americanFootballSharp });

export let iconAmericanFootballSharp = americanFootballSharp;
