
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { americanFootballSharp } from "ionicons/icons";

addIcons({"american-football-sharp": americanFootballSharp });

export let iconAmericanFootballSharp = "american-football-sharp";
