
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { analytics } from "ionicons/icons";
import '../lib-icons'

addIcons({ analytics });

export let iconAnalytics = analytics;
