
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { apertureOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ apertureOutline });

export default apertureOutline;
