
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { aperture } from "ionicons/icons";
import '../lib-icons'

addIcons({ aperture });

export let iconAperture = aperture;
