
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { appsSharp } from "ionicons/icons";

addIcons({"apps-sharp": appsSharp });

export let iconAppsSharp = "apps-sharp";
