
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { appsOutline } from "ionicons/icons";

addIcons({"apps-outline": appsOutline });

export let iconAppsOutline = "apps-outline";
