
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { archiveOutline } from "ionicons/icons";

addIcons({"archive-outline": archiveOutline });

export let iconArchiveOutline = "archive-outline";
