
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpRightBox } from "ionicons/icons";

addIcons({ arrowUpRightBox });

export let iconArrowUpRightBox = arrowUpRightBox;
