
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUndoCircle } from "ionicons/icons";

addIcons({"arrow-undo-circle": arrowUndoCircle });

export let iconArrowUndoCircle = "arrow-undo-circle";
