
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowRedo } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowRedo });

export let iconArrowRedo = arrowRedo;
