
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowBack } from "ionicons/icons";

addIcons({"arrow-back": arrowBack });

export let iconArrowBack = "arrow-back";
