
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowBackCircleSharp } from "ionicons/icons";

addIcons({"arrow-back-circle-sharp": arrowBackCircleSharp });

export let iconArrowBackCircleSharp = "arrow-back-circle-sharp";
