
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDownLeftBoxSharp } from "ionicons/icons";

addIcons({"arrow-down-left-box-sharp": arrowDownLeftBoxSharp });

export let iconArrowDownLeftBoxSharp = "arrow-down-left-box-sharp";
