
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowRedo } from "ionicons/icons";

addIcons({"arrow-redo": arrowRedo });

export let iconArrowRedo = "arrow-redo";
