
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowForward } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowForward });

export let iconArrowForward = arrowForward;
