
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowBackCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowBackCircleSharp });

export default arrowBackCircleSharp;
