
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowForwardCircle } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowForwardCircle });

export default arrowForwardCircle;
