
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowForwardSharp } from "ionicons/icons";

addIcons({ arrowForwardSharp });

export let iconArrowForwardSharp = "arrowForwardSharp";
