
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowRedoCircleSharp } from "ionicons/icons";

addIcons({ arrowRedoCircleSharp });

export let iconArrowRedoCircleSharp = arrowRedoCircleSharp;
