
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowBackOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowBackOutline });

export let iconArrowBackOutline = arrowBackOutline;
