
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpOutline } from "ionicons/icons";

addIcons({ arrowUpOutline });

export let iconArrowUpOutline = "arrowUpOutline";
