
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowForwardSharp } from "ionicons/icons";

addIcons({"arrow-forward-sharp": arrowForwardSharp });

export let iconArrowForwardSharp = "arrow-forward-sharp";
