
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowBackOutline } from "ionicons/icons";

addIcons({"arrow-back-outline": arrowBackOutline });

export let iconArrowBackOutline = "arrow-back-outline";
