
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowBackCircleOutline } from "ionicons/icons";

addIcons({"arrow-back-circle-outline": arrowBackCircleOutline });

export let iconArrowBackCircleOutline = "arrow-back-circle-outline";
