
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowRedoCircleOutline } from "ionicons/icons";

addIcons({"arrow-redo-circle-outline": arrowRedoCircleOutline });

export let iconArrowRedoCircleOutline = "arrow-redo-circle-outline";
