
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDownLeftBoxOutline } from "ionicons/icons";

addIcons({ arrowDownLeftBoxOutline });

export let iconArrowDownLeftBoxOutline = arrowDownLeftBoxOutline;
