
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpRightBoxSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowUpRightBoxSharp });

export default arrowUpRightBoxSharp;
