
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDownCircleSharp } from "ionicons/icons";

addIcons({ arrowDownCircleSharp });

export let iconArrowDownCircleSharp = arrowDownCircleSharp;
