
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowForwardCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowForwardCircleOutline });

export let iconArrowForwardCircleOutline = arrowForwardCircleOutline;
