
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowBackCircle } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowBackCircle });

export let iconArrowBackCircle = arrowBackCircle;
