
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDownOutline } from "ionicons/icons";

addIcons({ arrowDownOutline });

export let iconArrowDownOutline = "arrowDownOutline";
