
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUndo } from "ionicons/icons";

addIcons({"arrow-undo": arrowUndo });

export let iconArrowUndo = "arrow-undo";
