
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpRightBoxSharp } from "ionicons/icons";

addIcons({"arrow-up-right-box-sharp": arrowUpRightBoxSharp });

export let iconArrowUpRightBoxSharp = "arrow-up-right-box-sharp";
