
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowBackCircle } from "ionicons/icons";

addIcons({"arrow-back-circle": arrowBackCircle });

export let iconArrowBackCircle = "arrow-back-circle";
