
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpOutline } from "ionicons/icons";

addIcons({"arrow-up-outline": arrowUpOutline });

export let iconArrowUpOutline = "arrow-up-outline";
