
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowUpCircleSharp });

export let iconArrowUpCircleSharp = arrowUpCircleSharp;
