
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowBack } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowBack });

export let iconArrowBack = arrowBack;
