
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowBackCircleSharp } from "ionicons/icons";

addIcons({ arrowBackCircleSharp });

export let iconArrowBackCircleSharp = "arrowBackCircleSharp";
