
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDownCircle } from "ionicons/icons";

addIcons({ arrowDownCircle });

export let iconArrowDownCircle = "arrowDownCircle";
