
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDownRightBox } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowDownRightBox });

export default arrowDownRightBox;
