
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowBackOutline } from "ionicons/icons";

addIcons({ arrowBackOutline });

export let iconArrowBackOutline = "arrowBackOutline";
