
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpLeftBoxOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowUpLeftBoxOutline });

export let iconArrowUpLeftBoxOutline = arrowUpLeftBoxOutline;
