
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDown } from "ionicons/icons";

addIcons({"arrow-down": arrowDown });

export let iconArrowDown = "arrow-down";
