
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpLeftBox } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowUpLeftBox });

export let iconArrowUpLeftBox = arrowUpLeftBox;
