
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDownSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowDownSharp });

export let iconArrowDownSharp = arrowDownSharp;
