
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUndoOutline } from "ionicons/icons";

addIcons({"arrow-undo-outline": arrowUndoOutline });

export let iconArrowUndoOutline = "arrow-undo-outline";
