
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUndoSharp } from "ionicons/icons";

addIcons({"arrow-undo-sharp": arrowUndoSharp });

export let iconArrowUndoSharp = "arrow-undo-sharp";
