
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowRedoCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowRedoCircleSharp });

export default arrowRedoCircleSharp;
