
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpRightBoxOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowUpRightBoxOutline });

export default arrowUpRightBoxOutline;
