
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDownLeftBoxOutline } from "ionicons/icons";

addIcons({"arrow-down-left-box-outline": arrowDownLeftBoxOutline });

export let iconArrowDownLeftBoxOutline = "arrow-down-left-box-outline";
