
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowRedoCircle } from "ionicons/icons";

addIcons({"arrow-redo-circle": arrowRedoCircle });

export let iconArrowRedoCircle = "arrow-redo-circle";
