
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowRedoCircleSharp } from "ionicons/icons";

addIcons({"arrow-redo-circle-sharp": arrowRedoCircleSharp });

export let iconArrowRedoCircleSharp = "arrow-redo-circle-sharp";
