
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUndoSharp } from "ionicons/icons";

addIcons({ arrowUndoSharp });

export let iconArrowUndoSharp = "arrowUndoSharp";
