
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDownRightBoxOutline } from "ionicons/icons";

addIcons({"arrow-down-right-box-outline": arrowDownRightBoxOutline });

export let iconArrowDownRightBoxOutline = "arrow-down-right-box-outline";
