
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDownCircle } from "ionicons/icons";

addIcons({"arrow-down-circle": arrowDownCircle });

export let iconArrowDownCircle = "arrow-down-circle";
