
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUndoOutline } from "ionicons/icons";

addIcons({ arrowUndoOutline });

export let iconArrowUndoOutline = "arrowUndoOutline";
