
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowForwardOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowForwardOutline });

export let iconArrowForwardOutline = arrowForwardOutline;
