
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowRedoSharp } from "ionicons/icons";

addIcons({ arrowRedoSharp });

export let iconArrowRedoSharp = "arrowRedoSharp";
