
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDownOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowDownOutline });

export default arrowDownOutline;
