
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpCircle } from "ionicons/icons";

addIcons({ arrowUpCircle });

export let iconArrowUpCircle = "arrowUpCircle";
