
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpRightBoxOutline } from "ionicons/icons";

addIcons({ arrowUpRightBoxOutline });

export let iconArrowUpRightBoxOutline = arrowUpRightBoxOutline;
