
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowRedoOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowRedoOutline });

export let iconArrowRedoOutline = arrowRedoOutline;
