
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowRedoCircleOutline } from "ionicons/icons";

addIcons({ arrowRedoCircleOutline });

export let iconArrowRedoCircleOutline = arrowRedoCircleOutline;
