
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowRedoOutline } from "ionicons/icons";

addIcons({ arrowRedoOutline });

export let iconArrowRedoOutline = arrowRedoOutline;
