
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowBackSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowBackSharp });

export let iconArrowBackSharp = arrowBackSharp;
