
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowBackCircleOutline } from "ionicons/icons";

addIcons({ arrowBackCircleOutline });

export let iconArrowBackCircleOutline = "arrowBackCircleOutline";
