
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpLeftBoxSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowUpLeftBoxSharp });

export let iconArrowUpLeftBoxSharp = arrowUpLeftBoxSharp;
