
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDownCircleOutline } from "ionicons/icons";

addIcons({ arrowDownCircleOutline });

export let iconArrowDownCircleOutline = arrowDownCircleOutline;
