
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDownLeftBox } from "ionicons/icons";

addIcons({"arrow-down-left-box": arrowDownLeftBox });

export let iconArrowDownLeftBox = "arrow-down-left-box";
