
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUndoCircleOutline } from "ionicons/icons";

addIcons({"arrow-undo-circle-outline": arrowUndoCircleOutline });

export let iconArrowUndoCircleOutline = "arrow-undo-circle-outline";
