
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ arrowUpOutline });

export let iconArrowUpOutline = arrowUpOutline;
