
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { atCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ atCircleSharp });

export default atCircleSharp;
