
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { atCircleSharp } from "ionicons/icons";

addIcons({ atCircleSharp });

export let iconAtCircleSharp = "atCircleSharp";
