
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { atCircleOutline } from "ionicons/icons";

addIcons({"at-circle-outline": atCircleOutline });

export let iconAtCircleOutline = "at-circle-outline";
