
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { atCircleSharp } from "ionicons/icons";

addIcons({"at-circle-sharp": atCircleSharp });

export let iconAtCircleSharp = "at-circle-sharp";
