
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { atOutline } from "ionicons/icons";

addIcons({"at-outline": atOutline });

export let iconAtOutline = "at-outline";
