
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { attachOutline } from "ionicons/icons";

addIcons({ attachOutline });

export let iconAttachOutline = attachOutline;
