
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { attachSharp } from "ionicons/icons";

addIcons({"attach-sharp": attachSharp });

export let iconAttachSharp = "attach-sharp";
