
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { backspace } from "ionicons/icons";
import '../lib-icons'

addIcons({ backspace });

export let iconBackspace = backspace;
