
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagAddOutline } from "ionicons/icons";

addIcons({ bagAddOutline });

export let iconBagAddOutline = "bagAddOutline";
