
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagHandle } from "ionicons/icons";

addIcons({"bag-handle": bagHandle });

export let iconBagHandle = "bag-handle";
