
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagRemoveSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ bagRemoveSharp });

export let iconBagRemoveSharp = bagRemoveSharp;
