
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagHandleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ bagHandleOutline });

export default bagHandleOutline;
