
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagCheckOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ bagCheckOutline });

export default bagCheckOutline;
