
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagAddOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ bagAddOutline });

export default bagAddOutline;
