
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagCheckSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ bagCheckSharp });

export default bagCheckSharp;
