
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagRemove } from "ionicons/icons";
import '../lib-icons'

addIcons({ bagRemove });

export let iconBagRemove = bagRemove;
