
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ bagSharp });

export let iconBagSharp = bagSharp;
