
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagRemoveOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ bagRemoveOutline });

export default bagRemoveOutline;
