
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagHandleSharp } from "ionicons/icons";

addIcons({ bagHandleSharp });

export let iconBagHandleSharp = "bagHandleSharp";
