
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagCheckOutline } from "ionicons/icons";

addIcons({ bagCheckOutline });

export let iconBagCheckOutline = bagCheckOutline;
