
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagCheckSharp } from "ionicons/icons";

addIcons({ bagCheckSharp });

export let iconBagCheckSharp = "bagCheckSharp";
