
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { balloonSharp } from "ionicons/icons";

addIcons({"balloon-sharp": balloonSharp });

export let iconBalloonSharp = "balloon-sharp";
