
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { balloonSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ balloonSharp });

export let iconBalloonSharp = balloonSharp;
