
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { balloonOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ balloonOutline });

export let iconBalloonOutline = balloonOutline;
