
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { banOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ banOutline });

export let iconBanOutline = banOutline;
