
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { banOutline } from "ionicons/icons";

addIcons({"ban-outline": banOutline });

export let iconBanOutline = "ban-outline";
