
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bandageOutline } from "ionicons/icons";

addIcons({ bandageOutline });

export let iconBandageOutline = "bandageOutline";
