
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bandage } from "ionicons/icons";
import '../lib-icons'

addIcons({ bandage });

export let iconBandage = bandage;
