
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { barChartSharp } from "ionicons/icons";

addIcons({"bar-chart-sharp": barChartSharp });

export let iconBarChartSharp = "bar-chart-sharp";
