
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { barChartOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ barChartOutline });

export let iconBarChartOutline = barChartOutline;
