
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { barChartSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ barChartSharp });

export default barChartSharp;
