
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { barChartOutline } from "ionicons/icons";

addIcons({"bar-chart-outline": barChartOutline });

export let iconBarChartOutline = "bar-chart-outline";
