
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { barbellSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ barbellSharp });

export let iconBarbellSharp = barbellSharp;
