
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { barcodeSharp } from "ionicons/icons";

addIcons({"barcode-sharp": barcodeSharp });

export let iconBarcodeSharp = "barcode-sharp";
