
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { barcodeOutline } from "ionicons/icons";

addIcons({ barcodeOutline });

export let iconBarcodeOutline = barcodeOutline;
