
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { barcodeSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ barcodeSharp });

export let iconBarcodeSharp = barcodeSharp;
