
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { baseballSharp } from "ionicons/icons";

addIcons({ baseballSharp });

export let iconBaseballSharp = baseballSharp;
