
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { basketSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ basketSharp });

export default basketSharp;
