
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { basketballSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ basketballSharp });

export let iconBasketballSharp = basketballSharp;
