
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { basketballSharp } from "ionicons/icons";

addIcons({"basketball-sharp": basketballSharp });

export let iconBasketballSharp = "basketball-sharp";
