
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { basketOutline } from "ionicons/icons";

addIcons({ basketOutline });

export let iconBasketOutline = "basketOutline";
