
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { basketball } from "ionicons/icons";
import '../lib-icons'

addIcons({ basketball });

export let iconBasketball = basketball;
