
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { basketOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ basketOutline });

export default basketOutline;
