
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { batteryChargingOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ batteryChargingOutline });

export let iconBatteryChargingOutline = batteryChargingOutline;
