
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { batteryHalf } from "ionicons/icons";

addIcons({"battery-half": batteryHalf });

export let iconBatteryHalf = "battery-half";
