
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { batteryFullSharp } from "ionicons/icons";

addIcons({ batteryFullSharp });

export let iconBatteryFullSharp = batteryFullSharp;
