
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { batteryCharging } from "ionicons/icons";

addIcons({"battery-charging": batteryCharging });

export let iconBatteryCharging = "battery-charging";
