
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { batteryFullOutline } from "ionicons/icons";

addIcons({ batteryFullOutline });

export let iconBatteryFullOutline = "batteryFullOutline";
