
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { batteryHalf } from "ionicons/icons";
import '../lib-icons'

addIcons({ batteryHalf });

export let iconBatteryHalf = batteryHalf;
