
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { batteryDead } from "ionicons/icons";
import '../lib-icons'

addIcons({ batteryDead });

export let iconBatteryDead = batteryDead;
