
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { batteryDeadOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ batteryDeadOutline });

export default batteryDeadOutline;
