
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { batteryHalfOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ batteryHalfOutline });

export default batteryHalfOutline;
