
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { batteryChargingSharp } from "ionicons/icons";

addIcons({ batteryChargingSharp });

export let iconBatteryChargingSharp = batteryChargingSharp;
