
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { batteryHalfSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ batteryHalfSharp });

export default batteryHalfSharp;
