
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { batteryFullOutline } from "ionicons/icons";

addIcons({"battery-full-outline": batteryFullOutline });

export let iconBatteryFullOutline = "battery-full-outline";
