
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { beakerSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ beakerSharp });

export default beakerSharp;
