
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { beakerOutline } from "ionicons/icons";

addIcons({ beakerOutline });

export let iconBeakerOutline = "beakerOutline";
