
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { beakerOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ beakerOutline });

export default beakerOutline;
