
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bedOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ bedOutline });

export default bedOutline;
