
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { beerSharp } from "ionicons/icons";

addIcons({"beer-sharp": beerSharp });

export let iconBeerSharp = "beer-sharp";
