
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { beerOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ beerOutline });

export default beerOutline;
