
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { beerOutline } from "ionicons/icons";

addIcons({"beer-outline": beerOutline });

export let iconBeerOutline = "beer-outline";
