
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bicycleOutline } from "ionicons/icons";

addIcons({"bicycle-outline": bicycleOutline });

export let iconBicycleOutline = "bicycle-outline";
