
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bicycleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ bicycleSharp });

export let iconBicycleSharp = bicycleSharp;
