
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bicycleOutline } from "ionicons/icons";

addIcons({ bicycleOutline });

export let iconBicycleOutline = "bicycleOutline";
