
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bicycleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ bicycleOutline });

export let iconBicycleOutline = bicycleOutline;
