
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bicycleSharp } from "ionicons/icons";

addIcons({"bicycle-sharp": bicycleSharp });

export let iconBicycleSharp = "bicycle-sharp";
