
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { binocularsSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ binocularsSharp });

export let iconBinocularsSharp = binocularsSharp;
