
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { binocularsOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ binocularsOutline });

export default binocularsOutline;
