
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bluetoothOutline } from "ionicons/icons";

addIcons({"bluetooth-outline": bluetoothOutline });

export let iconBluetoothOutline = "bluetooth-outline";
