
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bluetoothSharp } from "ionicons/icons";

addIcons({ bluetoothSharp });

export let iconBluetoothSharp = "bluetoothSharp";
