
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bodyOutline } from "ionicons/icons";

addIcons({"body-outline": bodyOutline });

export let iconBodyOutline = "body-outline";
