
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bodyOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ bodyOutline });

export default bodyOutline;
