
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bonfireSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ bonfireSharp });

export let iconBonfireSharp = bonfireSharp;
