
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bookSharp } from "ionicons/icons";

addIcons({"book-sharp": bookSharp });

export let iconBookSharp = "book-sharp";
