
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bookSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ bookSharp });

export let iconBookSharp = bookSharp;
