
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bookOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ bookOutline });

export let iconBookOutline = bookOutline;
