
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bookmarkSharp } from "ionicons/icons";

addIcons({ bookmarkSharp });

export let iconBookmarkSharp = "bookmarkSharp";
