
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bookmarksOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ bookmarksOutline });

export default bookmarksOutline;
