
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bookmarkSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ bookmarkSharp });

export let iconBookmarkSharp = bookmarkSharp;
