
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bookmarksSharp } from "ionicons/icons";

addIcons({ bookmarksSharp });

export let iconBookmarksSharp = bookmarksSharp;
