
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bookmarkSharp } from "ionicons/icons";

addIcons({"bookmark-sharp": bookmarkSharp });

export let iconBookmarkSharp = "bookmark-sharp";
