
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bowlingBallSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ bowlingBallSharp });

export let iconBowlingBallSharp = bowlingBallSharp;
