
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bowlingBallSharp } from "ionicons/icons";

addIcons({"bowling-ball-sharp": bowlingBallSharp });

export let iconBowlingBallSharp = "bowling-ball-sharp";
