
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { briefcaseOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ briefcaseOutline });

export default briefcaseOutline;
