
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { briefcaseOutline } from "ionicons/icons";

addIcons({"briefcase-outline": briefcaseOutline });

export let iconBriefcaseOutline = "briefcase-outline";
