
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { briefcaseSharp } from "ionicons/icons";

addIcons({ briefcaseSharp });

export let iconBriefcaseSharp = "briefcaseSharp";
