
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { briefcase } from "ionicons/icons";

addIcons({"briefcase": briefcase });

export let iconBriefcase = "briefcase";
