
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { briefcaseSharp } from "ionicons/icons";

addIcons({"briefcase-sharp": briefcaseSharp });

export let iconBriefcaseSharp = "briefcase-sharp";
