
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { browsersOutline } from "ionicons/icons";

addIcons({"browsers-outline": browsersOutline });

export let iconBrowsersOutline = "browsers-outline";
