
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { browsersSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ browsersSharp });

export let iconBrowsersSharp = browsersSharp;
