
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { browsers } from "ionicons/icons";
import '../lib-icons'

addIcons({ browsers });

export let iconBrowsers = browsers;
