
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { brushOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ brushOutline });

export let iconBrushOutline = brushOutline;
