
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { brushOutline } from "ionicons/icons";

addIcons({ brushOutline });

export let iconBrushOutline = "brushOutline";
