
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { brushSharp } from "ionicons/icons";

addIcons({"brush-sharp": brushSharp });

export let iconBrushSharp = "brush-sharp";
