
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bugSharp } from "ionicons/icons";

addIcons({"bug-sharp": bugSharp });

export let iconBugSharp = "bug-sharp";
