
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { buildOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ buildOutline });

export default buildOutline;
