
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { buildOutline } from "ionicons/icons";

addIcons({ buildOutline });

export let iconBuildOutline = buildOutline;
