
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bulbSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ bulbSharp });

export let iconBulbSharp = bulbSharp;
