
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { busSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ busSharp });

export let iconBusSharp = busSharp;
