
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { businessOutline } from "ionicons/icons";

addIcons({"business-outline": businessOutline });

export let iconBusinessOutline = "business-outline";
