
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { businessOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ businessOutline });

export let iconBusinessOutline = businessOutline;
