
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { businessOutline } from "ionicons/icons";

addIcons({ businessOutline });

export let iconBusinessOutline = "businessOutline";
