
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { businessSharp } from "ionicons/icons";

addIcons({ businessSharp });

export let iconBusinessSharp = businessSharp;
