
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { businessSharp } from "ionicons/icons";

addIcons({"business-sharp": businessSharp });

export let iconBusinessSharp = "business-sharp";
