
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cafeSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ cafeSharp });

export let iconCafeSharp = cafeSharp;
