
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { calculator } from "ionicons/icons";

addIcons({"calculator": calculator });

export let iconCalculator = "calculator";
