
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { calculator } from "ionicons/icons";
import '../lib-icons'

addIcons({ calculator });

export default calculator;
