
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { calculatorSharp } from "ionicons/icons";

addIcons({"calculator-sharp": calculatorSharp });

export let iconCalculatorSharp = "calculator-sharp";
