
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { calendarClearSharp } from "ionicons/icons";

addIcons({ calendarClearSharp });

export let iconCalendarClearSharp = calendarClearSharp;
