
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { calendarClearOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ calendarClearOutline });

export default calendarClearOutline;
