
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { calendarClearOutline } from "ionicons/icons";

addIcons({"calendar-clear-outline": calendarClearOutline });

export let iconCalendarClearOutline = "calendar-clear-outline";
