
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { calendarNumberSharp } from "ionicons/icons";

addIcons({ calendarNumberSharp });

export let iconCalendarNumberSharp = calendarNumberSharp;
