
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { calendarOutline } from "ionicons/icons";

addIcons({ calendarOutline });

export let iconCalendarOutline = calendarOutline;
