
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { calendarNumberOutline } from "ionicons/icons";

addIcons({ calendarNumberOutline });

export let iconCalendarNumberOutline = "calendarNumberOutline";
