
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { calendarNumberOutline } from "ionicons/icons";

addIcons({"calendar-number-outline": calendarNumberOutline });

export let iconCalendarNumberOutline = "calendar-number-outline";
