
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { calendarSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ calendarSharp });

export let iconCalendarSharp = calendarSharp;
