
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { calendarNumber } from "ionicons/icons";

addIcons({ calendarNumber });

export let iconCalendarNumber = "calendarNumber";
