
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { callOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ callOutline });

export default callOutline;
