
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { callSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ callSharp });

export let iconCallSharp = callSharp;
