
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cameraReverse } from "ionicons/icons";

addIcons({ cameraReverse });

export let iconCameraReverse = cameraReverse;
