
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cameraOutline } from "ionicons/icons";

addIcons({"camera-outline": cameraOutline });

export let iconCameraOutline = "camera-outline";
