
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cameraOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ cameraOutline });

export default cameraOutline;
