
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cameraSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ cameraSharp });

export default cameraSharp;
