
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { carSportOutline } from "ionicons/icons";

addIcons({ carSportOutline });

export let iconCarSportOutline = "carSportOutline";
