
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { carSportSharp } from "ionicons/icons";

addIcons({"car-sport-sharp": carSportSharp });

export let iconCarSportSharp = "car-sport-sharp";
