
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { carSportOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ carSportOutline });

export let iconCarSportOutline = carSportOutline;
