
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { carSportSharp } from "ionicons/icons";

addIcons({ carSportSharp });

export let iconCarSportSharp = carSportSharp;
