
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cardSharp } from "ionicons/icons";

addIcons({"card-sharp": cardSharp });

export let iconCardSharp = "card-sharp";
