
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cardOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ cardOutline });

export let iconCardOutline = cardOutline;
