
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretDownCircle } from "ionicons/icons";

addIcons({ caretDownCircle });

export let iconCaretDownCircle = caretDownCircle;
