
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretBackCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ caretBackCircleSharp });

export let iconCaretBackCircleSharp = caretBackCircleSharp;
