
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretBackSharp } from "ionicons/icons";

addIcons({ caretBackSharp });

export let iconCaretBackSharp = caretBackSharp;
