
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretUpCircle } from "ionicons/icons";
import '../lib-icons'

addIcons({ caretUpCircle });

export default caretUpCircle;
