
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretBack } from "ionicons/icons";
import '../lib-icons'

addIcons({ caretBack });

export let iconCaretBack = caretBack;
