
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretDownCircleSharp } from "ionicons/icons";

addIcons({"caret-down-circle-sharp": caretDownCircleSharp });

export let iconCaretDownCircleSharp = "caret-down-circle-sharp";
