
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretBackSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ caretBackSharp });

export default caretBackSharp;
