
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretForwardCircle } from "ionicons/icons";

addIcons({ caretForwardCircle });

export let iconCaretForwardCircle = caretForwardCircle;
