
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretDownCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ caretDownCircleSharp });

export let iconCaretDownCircleSharp = caretDownCircleSharp;
