
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretDownSharp } from "ionicons/icons";

addIcons({ caretDownSharp });

export let iconCaretDownSharp = "caretDownSharp";
