
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretDownCircleSharp } from "ionicons/icons";

addIcons({ caretDownCircleSharp });

export let iconCaretDownCircleSharp = "caretDownCircleSharp";
