
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretForward } from "ionicons/icons";
import '../lib-icons'

addIcons({ caretForward });

export let iconCaretForward = caretForward;
