
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretBackCircleSharp } from "ionicons/icons";

addIcons({"caret-back-circle-sharp": caretBackCircleSharp });

export let iconCaretBackCircleSharp = "caret-back-circle-sharp";
