
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretBackOutline } from "ionicons/icons";

addIcons({"caret-back-outline": caretBackOutline });

export let iconCaretBackOutline = "caret-back-outline";
