
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretDownCircleOutline } from "ionicons/icons";

addIcons({"caret-down-circle-outline": caretDownCircleOutline });

export let iconCaretDownCircleOutline = "caret-down-circle-outline";
