
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretDownSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ caretDownSharp });

export default caretDownSharp;
