
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretDownOutline } from "ionicons/icons";

addIcons({"caret-down-outline": caretDownOutline });

export let iconCaretDownOutline = "caret-down-outline";
