
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretBackCircle } from "ionicons/icons";

addIcons({"caret-back-circle": caretBackCircle });

export let iconCaretBackCircle = "caret-back-circle";
