
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretForwardCircleOutline } from "ionicons/icons";

addIcons({"caret-forward-circle-outline": caretForwardCircleOutline });

export let iconCaretForwardCircleOutline = "caret-forward-circle-outline";
