
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretForwardCircleSharp } from "ionicons/icons";

addIcons({"caret-forward-circle-sharp": caretForwardCircleSharp });

export let iconCaretForwardCircleSharp = "caret-forward-circle-sharp";
