
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretUpSharp } from "ionicons/icons";

addIcons({ caretUpSharp });

export let iconCaretUpSharp = "caretUpSharp";
