
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretForwardCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ caretForwardCircleOutline });

export default caretForwardCircleOutline;
