
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretUpOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ caretUpOutline });

export let iconCaretUpOutline = caretUpOutline;
