
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cartOutline } from "ionicons/icons";

addIcons({"cart-outline": cartOutline });

export let iconCartOutline = "cart-outline";
