
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cashOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ cashOutline });

export default cashOutline;
