
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cashSharp } from "ionicons/icons";

addIcons({"cash-sharp": cashSharp });

export let iconCashSharp = "cash-sharp";
