
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cellularSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ cellularSharp });

export let iconCellularSharp = cellularSharp;
