
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cellularOutline } from "ionicons/icons";

addIcons({"cellular-outline": cellularOutline });

export let iconCellularOutline = "cellular-outline";
