
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cellularOutline } from "ionicons/icons";

addIcons({ cellularOutline });

export let iconCellularOutline = cellularOutline;
