
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cellularSharp } from "ionicons/icons";

addIcons({"cellular-sharp": cellularSharp });

export let iconCellularSharp = "cellular-sharp";
