
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatboxSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ chatboxSharp });

export default chatboxSharp;
