
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatboxEllipsesSharp } from "ionicons/icons";

addIcons({ chatboxEllipsesSharp });

export let iconChatboxEllipsesSharp = chatboxEllipsesSharp;
