
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatbubbleEllipsesOutline } from "ionicons/icons";

addIcons({"chatbubble-ellipses-outline": chatbubbleEllipsesOutline });

export let iconChatbubbleEllipsesOutline = "chatbubble-ellipses-outline";
