
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatbubbles } from "ionicons/icons";
import '../lib-icons'

addIcons({ chatbubbles });

export let iconChatbubbles = chatbubbles;
