
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatbubbleEllipses } from "ionicons/icons";

addIcons({ chatbubbleEllipses });

export let iconChatbubbleEllipses = chatbubbleEllipses;
