
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatbubblesSharp } from "ionicons/icons";

addIcons({ chatbubblesSharp });

export let iconChatbubblesSharp = chatbubblesSharp;
