
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatbubblesOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ chatbubblesOutline });

export default chatbubblesOutline;
