
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatboxEllipsesOutline } from "ionicons/icons";

addIcons({ chatboxEllipsesOutline });

export let iconChatboxEllipsesOutline = "chatboxEllipsesOutline";
