
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatbubbleEllipsesOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ chatbubbleEllipsesOutline });

export default chatbubbleEllipsesOutline;
