
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatbubbleEllipsesSharp } from "ionicons/icons";

addIcons({ chatbubbleEllipsesSharp });

export let iconChatbubbleEllipsesSharp = chatbubbleEllipsesSharp;
