
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatbox } from "ionicons/icons";
import '../lib-icons'

addIcons({ chatbox });

export let iconChatbox = chatbox;
