
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatbubbles } from "ionicons/icons";

addIcons({"chatbubbles": chatbubbles });

export let iconChatbubbles = "chatbubbles";
