
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatboxEllipses } from "ionicons/icons";

addIcons({ chatboxEllipses });

export let iconChatboxEllipses = "chatboxEllipses";
