
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatbubbleOutline } from "ionicons/icons";

addIcons({"chatbubble-outline": chatbubbleOutline });

export let iconChatbubbleOutline = "chatbubble-outline";
