
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatbubbleSharp } from "ionicons/icons";

addIcons({ chatbubbleSharp });

export let iconChatbubbleSharp = "chatbubbleSharp";
