
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatboxOutline } from "ionicons/icons";

addIcons({"chatbox-outline": chatboxOutline });

export let iconChatboxOutline = "chatbox-outline";
