
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatbubbleEllipsesSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ chatbubbleEllipsesSharp });

export default chatbubbleEllipsesSharp;
