
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkmarkCircle } from "ionicons/icons";

addIcons({"checkmark-circle": checkmarkCircle });

export let iconCheckmarkCircle = "checkmark-circle";
