
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkmarkCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ checkmarkCircleSharp });

export default checkmarkCircleSharp;
