
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkboxSharp } from "ionicons/icons";

addIcons({"checkbox-sharp": checkboxSharp });

export let iconCheckboxSharp = "checkbox-sharp";
