
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkmarkDoneCircle } from "ionicons/icons";

addIcons({"checkmark-done-circle": checkmarkDoneCircle });

export let iconCheckmarkDoneCircle = "checkmark-done-circle";
