
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkmarkOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ checkmarkOutline });

export default checkmarkOutline;
