
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkboxSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ checkboxSharp });

export let iconCheckboxSharp = checkboxSharp;
