
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkmarkCircle } from "ionicons/icons";
import '../lib-icons'

addIcons({ checkmarkCircle });

export let iconCheckmarkCircle = checkmarkCircle;
