
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkmarkSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ checkmarkSharp });

export let iconCheckmarkSharp = checkmarkSharp;
