
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkmarkDoneSharp } from "ionicons/icons";

addIcons({"checkmark-done-sharp": checkmarkDoneSharp });

export let iconCheckmarkDoneSharp = "checkmark-done-sharp";
