
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkmarkDoneSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ checkmarkDoneSharp });

export let iconCheckmarkDoneSharp = checkmarkDoneSharp;
