
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkmarkDoneCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ checkmarkDoneCircleSharp });

export let iconCheckmarkDoneCircleSharp = checkmarkDoneCircleSharp;
