
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkboxOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ checkboxOutline });

export let iconCheckboxOutline = checkboxOutline;
