
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkmarkDoneCircle } from "ionicons/icons";

addIcons({ checkmarkDoneCircle });

export let iconCheckmarkDoneCircle = checkmarkDoneCircle;
