
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkmarkDoneOutline } from "ionicons/icons";

addIcons({"checkmark-done-outline": checkmarkDoneOutline });

export let iconCheckmarkDoneOutline = "checkmark-done-outline";
