
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkmarkDone } from "ionicons/icons";

addIcons({ checkmarkDone });

export let iconCheckmarkDone = checkmarkDone;
