
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkmarkDoneCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ checkmarkDoneCircleOutline });

export default checkmarkDoneCircleOutline;
