
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronForwardSharp } from "ionicons/icons";

addIcons({ chevronForwardSharp });

export let iconChevronForwardSharp = "chevronForwardSharp";
