
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronDownSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ chevronDownSharp });

export default chevronDownSharp;
