
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronUpCircle } from "ionicons/icons";

addIcons({ chevronUpCircle });

export let iconChevronUpCircle = chevronUpCircle;
