
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronDownOutline } from "ionicons/icons";

addIcons({ chevronDownOutline });

export let iconChevronDownOutline = chevronDownOutline;
