
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronForwardCircle } from "ionicons/icons";

addIcons({ chevronForwardCircle });

export let iconChevronForwardCircle = "chevronForwardCircle";
