
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronUpOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ chevronUpOutline });

export let iconChevronUpOutline = chevronUpOutline;
