
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronCollapseSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ chevronCollapseSharp });

export default chevronCollapseSharp;
