
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronBack } from "ionicons/icons";
import '../lib-icons'

addIcons({ chevronBack });

export let iconChevronBack = chevronBack;
