
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronForward } from "ionicons/icons";

addIcons({ chevronForward });

export let iconChevronForward = "chevronForward";
