
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronDownCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ chevronDownCircleSharp });

export default chevronDownCircleSharp;
