
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronBackCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ chevronBackCircleSharp });

export let iconChevronBackCircleSharp = chevronBackCircleSharp;
