
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronDownCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ chevronDownCircleOutline });

export default chevronDownCircleOutline;
