
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronBackOutline } from "ionicons/icons";

addIcons({ chevronBackOutline });

export let iconChevronBackOutline = "chevronBackOutline";
