
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronExpand } from "ionicons/icons";

addIcons({ chevronExpand });

export let iconChevronExpand = chevronExpand;
