
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronCollapseSharp } from "ionicons/icons";

addIcons({ chevronCollapseSharp });

export let iconChevronCollapseSharp = chevronCollapseSharp;
