
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronBackCircleOutline } from "ionicons/icons";

addIcons({"chevron-back-circle-outline": chevronBackCircleOutline });

export let iconChevronBackCircleOutline = "chevron-back-circle-outline";
