
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronUpCircleSharp } from "ionicons/icons";

addIcons({"chevron-up-circle-sharp": chevronUpCircleSharp });

export let iconChevronUpCircleSharp = "chevron-up-circle-sharp";
