
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronBackCircle } from "ionicons/icons";

addIcons({"chevron-back-circle": chevronBackCircle });

export let iconChevronBackCircle = "chevron-back-circle";
