
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronExpandSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ chevronExpandSharp });

export let iconChevronExpandSharp = chevronExpandSharp;
