
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronDownCircle } from "ionicons/icons";
import '../lib-icons'

addIcons({ chevronDownCircle });

export default chevronDownCircle;
