
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronCollapseOutline } from "ionicons/icons";

addIcons({"chevron-collapse-outline": chevronCollapseOutline });

export let iconChevronCollapseOutline = "chevron-collapse-outline";
