
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronUpSharp } from "ionicons/icons";

addIcons({ chevronUpSharp });

export let iconChevronUpSharp = chevronUpSharp;
