
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronForwardOutline } from "ionicons/icons";

addIcons({ chevronForwardOutline });

export let iconChevronForwardOutline = "chevronForwardOutline";
