
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronDownCircleSharp } from "ionicons/icons";

addIcons({ chevronDownCircleSharp });

export let iconChevronDownCircleSharp = chevronDownCircleSharp;
