
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronBackCircle } from "ionicons/icons";

addIcons({ chevronBackCircle });

export let iconChevronBackCircle = chevronBackCircle;
