
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronExpandOutline } from "ionicons/icons";

addIcons({ chevronExpandOutline });

export let iconChevronExpandOutline = "chevronExpandOutline";
