
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronBack } from "ionicons/icons";

addIcons({"chevron-back": chevronBack });

export let iconChevronBack = "chevron-back";
