
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronForwardOutline } from "ionicons/icons";

addIcons({"chevron-forward-outline": chevronForwardOutline });

export let iconChevronForwardOutline = "chevron-forward-outline";
