
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronDownSharp } from "ionicons/icons";

addIcons({"chevron-down-sharp": chevronDownSharp });

export let iconChevronDownSharp = "chevron-down-sharp";
