
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronDown } from "ionicons/icons";
import '../lib-icons'

addIcons({ chevronDown });

export default chevronDown;
