
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronDownOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ chevronDownOutline });

export default chevronDownOutline;
