
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronForwardCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ chevronForwardCircleOutline });

export let iconChevronForwardCircleOutline = chevronForwardCircleOutline;
