
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronForwardSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ chevronForwardSharp });

export default chevronForwardSharp;
