
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronBackCircleSharp } from "ionicons/icons";

addIcons({"chevron-back-circle-sharp": chevronBackCircleSharp });

export let iconChevronBackCircleSharp = "chevron-back-circle-sharp";
