
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronExpandSharp } from "ionicons/icons";

addIcons({"chevron-expand-sharp": chevronExpandSharp });

export let iconChevronExpandSharp = "chevron-expand-sharp";
