
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronUpSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ chevronUpSharp });

export default chevronUpSharp;
