
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronUpCircleSharp } from "ionicons/icons";

addIcons({ chevronUpCircleSharp });

export let iconChevronUpCircleSharp = chevronUpCircleSharp;
