
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { clipboardOutline } from "ionicons/icons";

addIcons({ clipboardOutline });

export let iconClipboardOutline = clipboardOutline;
