
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { clipboardSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ clipboardSharp });

export let iconClipboardSharp = clipboardSharp;
