
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { closeOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ closeOutline });

export let iconCloseOutline = closeOutline;
