
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { closeCircleSharp } from "ionicons/icons";

addIcons({ closeCircleSharp });

export let iconCloseCircleSharp = "closeCircleSharp";
