
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { closeCircle } from "ionicons/icons";
import '../lib-icons'

addIcons({ closeCircle });

export let iconCloseCircle = closeCircle;
