
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudUpload } from "ionicons/icons";
import '../lib-icons'

addIcons({ cloudUpload });

export let iconCloudUpload = cloudUpload;
