
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudOutline } from "ionicons/icons";

addIcons({ cloudOutline });

export let iconCloudOutline = cloudOutline;
