
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudCircleSharp } from "ionicons/icons";

addIcons({"cloud-circle-sharp": cloudCircleSharp });

export let iconCloudCircleSharp = "cloud-circle-sharp";
