
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudOfflineSharp } from "ionicons/icons";

addIcons({"cloud-offline-sharp": cloudOfflineSharp });

export let iconCloudOfflineSharp = "cloud-offline-sharp";
