
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudyOutline } from "ionicons/icons";

addIcons({"cloudy-outline": cloudyOutline });

export let iconCloudyOutline = "cloudy-outline";
