
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudOffline } from "ionicons/icons";

addIcons({"cloud-offline": cloudOffline });

export let iconCloudOffline = "cloud-offline";
