
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudyNightSharp } from "ionicons/icons";

addIcons({ cloudyNightSharp });

export let iconCloudyNightSharp = cloudyNightSharp;
