
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudDoneOutline } from "ionicons/icons";

addIcons({ cloudDoneOutline });

export let iconCloudDoneOutline = cloudDoneOutline;
