
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudDownloadSharp } from "ionicons/icons";

addIcons({ cloudDownloadSharp });

export let iconCloudDownloadSharp = "cloudDownloadSharp";
