
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudDone } from "ionicons/icons";
import '../lib-icons'

addIcons({ cloudDone });

export let iconCloudDone = cloudDone;
