
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudDownload } from "ionicons/icons";

addIcons({ cloudDownload });

export let iconCloudDownload = "cloudDownload";
