
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudOffline } from "ionicons/icons";

addIcons({ cloudOffline });

export let iconCloudOffline = "cloudOffline";
