
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudUploadSharp } from "ionicons/icons";

addIcons({"cloud-upload-sharp": cloudUploadSharp });

export let iconCloudUploadSharp = "cloud-upload-sharp";
