
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudCircle } from "ionicons/icons";
import '../lib-icons'

addIcons({ cloudCircle });

export let iconCloudCircle = cloudCircle;
