
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudOutline } from "ionicons/icons";

addIcons({"cloud-outline": cloudOutline });

export let iconCloudOutline = "cloud-outline";
