
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudyNightOutline } from "ionicons/icons";

addIcons({ cloudyNightOutline });

export let iconCloudyNightOutline = "cloudyNightOutline";
