
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudyOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ cloudyOutline });

export default cloudyOutline;
