
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudUploadSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ cloudUploadSharp });

export let iconCloudUploadSharp = cloudUploadSharp;
