
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeWorkingOutline } from "ionicons/icons";

addIcons({ codeWorkingOutline });

export let iconCodeWorkingOutline = "codeWorkingOutline";
