
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ codeSharp });

export let iconCodeSharp = codeSharp;
