
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeSlashSharp } from "ionicons/icons";

addIcons({"code-slash-sharp": codeSlashSharp });

export let iconCodeSlashSharp = "code-slash-sharp";
