
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeDownload } from "ionicons/icons";

addIcons({"code-download": codeDownload });

export let iconCodeDownload = "code-download";
