
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeDownloadSharp } from "ionicons/icons";

addIcons({ codeDownloadSharp });

export let iconCodeDownloadSharp = codeDownloadSharp;
