
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeDownload } from "ionicons/icons";
import '../lib-icons'

addIcons({ codeDownload });

export default codeDownload;
