
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeDownloadSharp } from "ionicons/icons";

addIcons({"code-download-sharp": codeDownloadSharp });

export let iconCodeDownloadSharp = "code-download-sharp";
