
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeWorking } from "ionicons/icons";
import '../lib-icons'

addIcons({ codeWorking });

export let iconCodeWorking = codeWorking;
