
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeDownloadOutline } from "ionicons/icons";

addIcons({"code-download-outline": codeDownloadOutline });

export let iconCodeDownloadOutline = "code-download-outline";
