
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeOutline } from "ionicons/icons";

addIcons({"code-outline": codeOutline });

export let iconCodeOutline = "code-outline";
