
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeWorkingOutline } from "ionicons/icons";

addIcons({"code-working-outline": codeWorkingOutline });

export let iconCodeWorkingOutline = "code-working-outline";
