
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeWorkingOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ codeWorkingOutline });

export let iconCodeWorkingOutline = codeWorkingOutline;
