
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeSlashOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ codeSlashOutline });

export default codeSlashOutline;
