
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeWorkingSharp } from "ionicons/icons";

addIcons({ codeWorkingSharp });

export let iconCodeWorkingSharp = "codeWorkingSharp";
