
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ codeOutline });

export let iconCodeOutline = codeOutline;
