
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeSlashOutline } from "ionicons/icons";

addIcons({ codeSlashOutline });

export let iconCodeSlashOutline = codeSlashOutline;
