
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cogOutline } from "ionicons/icons";

addIcons({"cog-outline": cogOutline });

export let iconCogOutline = "cog-outline";
