
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cogOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ cogOutline });

export let iconCogOutline = cogOutline;
