
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cogSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ cogSharp });

export let iconCogSharp = cogSharp;
