
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { colorFillOutline } from "ionicons/icons";

addIcons({"color-fill-outline": colorFillOutline });

export let iconColorFillOutline = "color-fill-outline";
