
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { colorFillOutline } from "ionicons/icons";

addIcons({ colorFillOutline });

export let iconColorFillOutline = "colorFillOutline";
