
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { colorWandSharp } from "ionicons/icons";

addIcons({"color-wand-sharp": colorWandSharp });

export let iconColorWandSharp = "color-wand-sharp";
