
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { colorWandSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ colorWandSharp });

export let iconColorWandSharp = colorWandSharp;
