
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { colorFilter } from "ionicons/icons";
import '../lib-icons'

addIcons({ colorFilter });

export let iconColorFilter = colorFilter;
