
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { colorFilterSharp } from "ionicons/icons";

addIcons({ colorFilterSharp });

export let iconColorFilterSharp = "colorFilterSharp";
