
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { colorPalette } from "ionicons/icons";

addIcons({ colorPalette });

export let iconColorPalette = "colorPalette";
