
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { colorFilterOutline } from "ionicons/icons";

addIcons({"color-filter-outline": colorFilterOutline });

export let iconColorFilterOutline = "color-filter-outline";
