
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { colorPaletteSharp } from "ionicons/icons";

addIcons({ colorPaletteSharp });

export let iconColorPaletteSharp = colorPaletteSharp;
