
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { colorFillSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ colorFillSharp });

export default colorFillSharp;
