
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { compassOutline } from "ionicons/icons";

addIcons({ compassOutline });

export let iconCompassOutline = compassOutline;
