
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { compassSharp } from "ionicons/icons";

addIcons({"compass-sharp": compassSharp });

export let iconCompassSharp = "compass-sharp";
