
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { constructSharp } from "ionicons/icons";

addIcons({ constructSharp });

export let iconConstructSharp = "constructSharp";
