
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { constructSharp } from "ionicons/icons";

addIcons({"construct-sharp": constructSharp });

export let iconConstructSharp = "construct-sharp";
