
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { constructSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ constructSharp });

export default constructSharp;
