
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { contractSharp } from "ionicons/icons";

addIcons({"contract-sharp": contractSharp });

export let iconContractSharp = "contract-sharp";
