
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { contractSharp } from "ionicons/icons";

addIcons({ contractSharp });

export let iconContractSharp = contractSharp;
