
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { contractOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ contractOutline });

export default contractOutline;
