
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { contrast } from "ionicons/icons";
import '../lib-icons'

addIcons({ contrast });

export let iconContrast = contrast;
