
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { contractSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ contractSharp });

export let iconContractSharp = contractSharp;
