
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { contrastOutline } from "ionicons/icons";

addIcons({ contrastOutline });

export let iconContrastOutline = "contrastOutline";
