
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { contrastSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ contrastSharp });

export let iconContrastSharp = contrastSharp;
