
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { contrastOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ contrastOutline });

export default contrastOutline;
