
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { copySharp } from "ionicons/icons";

addIcons({"copy-sharp": copySharp });

export let iconCopySharp = "copy-sharp";
