
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { copySharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ copySharp });

export let iconCopySharp = copySharp;
