
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cropOutline } from "ionicons/icons";

addIcons({"crop-outline": cropOutline });

export let iconCropOutline = "crop-outline";
