
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cropOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ cropOutline });

export let iconCropOutline = cropOutline;
