
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cropSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ cropSharp });

export let iconCropSharp = cropSharp;
