
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cubeOutline } from "ionicons/icons";

addIcons({"cube-outline": cubeOutline });

export let iconCubeOutline = "cube-outline";
