
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cutSharp } from "ionicons/icons";

addIcons({"cut-sharp": cutSharp });

export let iconCutSharp = "cut-sharp";
