
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cutOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ cutOutline });

export let iconCutOutline = cutOutline;
