
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cutSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ cutSharp });

export let iconCutSharp = cutSharp;
