
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cutOutline } from "ionicons/icons";

addIcons({"cut-outline": cutOutline });

export let iconCutOutline = "cut-outline";
