
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { desktopOutline } from "ionicons/icons";

addIcons({ desktopOutline });

export let iconDesktopOutline = desktopOutline;
