
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { diamondOutline } from "ionicons/icons";

addIcons({"diamond-outline": diamondOutline });

export let iconDiamondOutline = "diamond-outline";
