
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { diamond } from "ionicons/icons";
import '../lib-icons'

addIcons({ diamond });

export let iconDiamond = diamond;
