
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { diamondSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ diamondSharp });

export default diamondSharp;
