
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { diceOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ diceOutline });

export default diceOutline;
