
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { discOutline } from "ionicons/icons";

addIcons({"disc-outline": discOutline });

export let iconDiscOutline = "disc-outline";
