
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { discSharp } from "ionicons/icons";

addIcons({"disc-sharp": discSharp });

export let iconDiscSharp = "disc-sharp";
