
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentLock } from "ionicons/icons";

addIcons({"document-lock": documentLock });

export let iconDocumentLock = "document-lock";
