
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentAttachOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ documentAttachOutline });

export let iconDocumentAttachOutline = documentAttachOutline;
