
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentAttachOutline } from "ionicons/icons";

addIcons({"document-attach-outline": documentAttachOutline });

export let iconDocumentAttachOutline = "document-attach-outline";
