
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentSharp } from "ionicons/icons";

addIcons({ documentSharp });

export let iconDocumentSharp = documentSharp;
