
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentsSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ documentsSharp });

export let iconDocumentsSharp = documentsSharp;
