
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentLockOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ documentLockOutline });

export default documentLockOutline;
