
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentText } from "ionicons/icons";

addIcons({"document-text": documentText });

export let iconDocumentText = "document-text";
