
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentSharp } from "ionicons/icons";

addIcons({"document-sharp": documentSharp });

export let iconDocumentSharp = "document-sharp";
