
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentsSharp } from "ionicons/icons";

addIcons({"documents-sharp": documentsSharp });

export let iconDocumentsSharp = "documents-sharp";
