
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentLockOutline } from "ionicons/icons";

addIcons({ documentLockOutline });

export let iconDocumentLockOutline = "documentLockOutline";
