
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentsOutline } from "ionicons/icons";

addIcons({"documents-outline": documentsOutline });

export let iconDocumentsOutline = "documents-outline";
