
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documents } from "ionicons/icons";
import '../lib-icons'

addIcons({ documents });

export let iconDocuments = documents;
