
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentAttachSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ documentAttachSharp });

export default documentAttachSharp;
