
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documents } from "ionicons/icons";

addIcons({"documents": documents });

export let iconDocuments = "documents";
