
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentsOutline } from "ionicons/icons";

addIcons({ documentsOutline });

export let iconDocumentsOutline = "documentsOutline";
