
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentAttachSharp } from "ionicons/icons";

addIcons({"document-attach-sharp": documentAttachSharp });

export let iconDocumentAttachSharp = "document-attach-sharp";
