
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentLockSharp } from "ionicons/icons";

addIcons({ documentLockSharp });

export let iconDocumentLockSharp = "documentLockSharp";
