
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentsOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ documentsOutline });

export let iconDocumentsOutline = documentsOutline;
