
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentAttach } from "ionicons/icons";
import '../lib-icons'

addIcons({ documentAttach });

export default documentAttach;
