
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentOutline } from "ionicons/icons";

addIcons({ documentOutline });

export let iconDocumentOutline = documentOutline;
