
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentAttachOutline } from "ionicons/icons";

addIcons({ documentAttachOutline });

export let iconDocumentAttachOutline = "documentAttachOutline";
