
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ documentSharp });

export default documentSharp;
