
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { download } from "ionicons/icons";
import '../lib-icons'

addIcons({ download });

export let iconDownload = download;
