
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { downloadSharp } from "ionicons/icons";

addIcons({ downloadSharp });

export let iconDownloadSharp = downloadSharp;
