
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { downloadOutline } from "ionicons/icons";

addIcons({ downloadOutline });

export let iconDownloadOutline = downloadOutline;
