
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { duplicateOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ duplicateOutline });

export let iconDuplicateOutline = duplicateOutline;
