
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { duplicateSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ duplicateSharp });

export let iconDuplicateSharp = duplicateSharp;
