
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { duplicateOutline } from "ionicons/icons";

addIcons({"duplicate-outline": duplicateOutline });

export let iconDuplicateOutline = "duplicate-outline";
