
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { earSharp } from "ionicons/icons";

addIcons({"ear-sharp": earSharp });

export let iconEarSharp = "ear-sharp";
