
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { earSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ earSharp });

export let iconEarSharp = earSharp;
