
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { earOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ earOutline });

export default earOutline;
