
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { earthOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ earthOutline });

export let iconEarthOutline = earthOutline;
