
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { earthSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ earthSharp });

export let iconEarthSharp = earthSharp;
