
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { easelOutline } from "ionicons/icons";

addIcons({ easelOutline });

export let iconEaselOutline = "easelOutline";
