
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { easelSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ easelSharp });

export default easelSharp;
