
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { easelOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ easelOutline });

export default easelOutline;
