
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { easelSharp } from "ionicons/icons";

addIcons({"easel-sharp": easelSharp });

export let iconEaselSharp = "easel-sharp";
