
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { eggOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ eggOutline });

export default eggOutline;
