
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisHorizontalOutline } from "ionicons/icons";

addIcons({"ellipsis-horizontal-outline": ellipsisHorizontalOutline });

export let iconEllipsisHorizontalOutline = "ellipsis-horizontal-outline";
