
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisVerticalCircle } from "ionicons/icons";
import '../lib-icons'

addIcons({ ellipsisVerticalCircle });

export let iconEllipsisVerticalCircle = ellipsisVerticalCircle;
