
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisVertical } from "ionicons/icons";

addIcons({ ellipsisVertical });

export let iconEllipsisVertical = ellipsisVertical;
