
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisHorizontalSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ ellipsisHorizontalSharp });

export default ellipsisHorizontalSharp;
