
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisVerticalCircleSharp } from "ionicons/icons";

addIcons({"ellipsis-vertical-circle-sharp": ellipsisVerticalCircleSharp });

export let iconEllipsisVerticalCircleSharp = "ellipsis-vertical-circle-sharp";
