
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisVertical } from "ionicons/icons";

addIcons({"ellipsis-vertical": ellipsisVertical });

export let iconEllipsisVertical = "ellipsis-vertical";
