
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisVerticalSharp } from "ionicons/icons";

addIcons({ ellipsisVerticalSharp });

export let iconEllipsisVerticalSharp = "ellipsisVerticalSharp";
