
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisHorizontalCircleOutline } from "ionicons/icons";

addIcons({"ellipsis-horizontal-circle-outline": ellipsisHorizontalCircleOutline });

export let iconEllipsisHorizontalCircleOutline = "ellipsis-horizontal-circle-outline";
