
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisVerticalCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ ellipsisVerticalCircleOutline });

export let iconEllipsisVerticalCircleOutline = ellipsisVerticalCircleOutline;
