
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisVerticalCircleSharp } from "ionicons/icons";

addIcons({ ellipsisVerticalCircleSharp });

export let iconEllipsisVerticalCircleSharp = ellipsisVerticalCircleSharp;
