
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisHorizontalCircle } from "ionicons/icons";

addIcons({ ellipsisHorizontalCircle });

export let iconEllipsisHorizontalCircle = "ellipsisHorizontalCircle";
