
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisHorizontalCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ ellipsisHorizontalCircleOutline });

export let iconEllipsisHorizontalCircleOutline = ellipsisHorizontalCircleOutline;
