
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisHorizontalSharp } from "ionicons/icons";

addIcons({ ellipsisHorizontalSharp });

export let iconEllipsisHorizontalSharp = ellipsisHorizontalSharp;
