
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisHorizontalCircleSharp } from "ionicons/icons";

addIcons({ ellipsisHorizontalCircleSharp });

export let iconEllipsisHorizontalCircleSharp = "ellipsisHorizontalCircleSharp";
