
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { enterOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ enterOutline });

export let iconEnterOutline = enterOutline;
