
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { enterOutline } from "ionicons/icons";

addIcons({"enter-outline": enterOutline });

export let iconEnterOutline = "enter-outline";
