
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { enterSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ enterSharp });

export default enterSharp;
