
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { expandOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ expandOutline });

export let iconExpandOutline = expandOutline;
