
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { extensionPuzzleSharp } from "ionicons/icons";

addIcons({ extensionPuzzleSharp });

export let iconExtensionPuzzleSharp = extensionPuzzleSharp;
