
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { extensionPuzzle } from "ionicons/icons";
import '../lib-icons'

addIcons({ extensionPuzzle });

export default extensionPuzzle;
