
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { extensionPuzzleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ extensionPuzzleOutline });

export default extensionPuzzleOutline;
