
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { extensionPuzzle } from "ionicons/icons";

addIcons({ extensionPuzzle });

export let iconExtensionPuzzle = "extensionPuzzle";
