
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { eyeOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ eyeOutline });

export default eyeOutline;
