
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { eyeSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ eyeSharp });

export let iconEyeSharp = eyeSharp;
