
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { eyedropOutline } from "ionicons/icons";

addIcons({ eyedropOutline });

export let iconEyedropOutline = eyedropOutline;
