
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { eyedropOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ eyedropOutline });

export default eyedropOutline;
