
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fastFoodSharp } from "ionicons/icons";

addIcons({ fastFoodSharp });

export let iconFastFoodSharp = "fastFoodSharp";
