
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fastFood } from "ionicons/icons";

addIcons({"fast-food": fastFood });

export let iconFastFood = "fast-food";
