
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fastFoodSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ fastFoodSharp });

export default fastFoodSharp;
