
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { femaleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ femaleSharp });

export default femaleSharp;
