
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { femaleSharp } from "ionicons/icons";

addIcons({"female-sharp": femaleSharp });

export let iconFemaleSharp = "female-sharp";
