
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { femaleOutline } from "ionicons/icons";

addIcons({ femaleOutline });

export let iconFemaleOutline = femaleOutline;
