
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { femaleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ femaleOutline });

export default femaleOutline;
