
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fileTrayStackedSharp } from "ionicons/icons";

addIcons({"file-tray-stacked-sharp": fileTrayStackedSharp });

export let iconFileTrayStackedSharp = "file-tray-stacked-sharp";
