
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fileTrayFullSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ fileTrayFullSharp });

export let iconFileTrayFullSharp = fileTrayFullSharp;
