
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fileTrayFull } from "ionicons/icons";

addIcons({"file-tray-full": fileTrayFull });

export let iconFileTrayFull = "file-tray-full";
