
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fileTrayStacked } from "ionicons/icons";

addIcons({"file-tray-stacked": fileTrayStacked });

export let iconFileTrayStacked = "file-tray-stacked";
