
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fileTrayStackedSharp } from "ionicons/icons";

addIcons({ fileTrayStackedSharp });

export let iconFileTrayStackedSharp = fileTrayStackedSharp;
