
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fileTrayOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ fileTrayOutline });

export let iconFileTrayOutline = fileTrayOutline;
