
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fileTrayFullOutline } from "ionicons/icons";

addIcons({ fileTrayFullOutline });

export let iconFileTrayFullOutline = fileTrayFullOutline;
