
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fileTrayOutline } from "ionicons/icons";

addIcons({"file-tray-outline": fileTrayOutline });

export let iconFileTrayOutline = "file-tray-outline";
