
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { filmOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ filmOutline });

export let iconFilmOutline = filmOutline;
