
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { filmOutline } from "ionicons/icons";

addIcons({"film-outline": filmOutline });

export let iconFilmOutline = "film-outline";
