
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { filterSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ filterSharp });

export default filterSharp;
