
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { filterCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ filterCircleSharp });

export default filterCircleSharp;
