
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { filterSharp } from "ionicons/icons";

addIcons({"filter-sharp": filterSharp });

export let iconFilterSharp = "filter-sharp";
