
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { filterOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ filterOutline });

export default filterOutline;
