
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fingerPrintSharp } from "ionicons/icons";

addIcons({"finger-print-sharp": fingerPrintSharp });

export let iconFingerPrintSharp = "finger-print-sharp";
