
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fingerPrintSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ fingerPrintSharp });

export default fingerPrintSharp;
