
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fingerPrintOutline } from "ionicons/icons";

addIcons({"finger-print-outline": fingerPrintOutline });

export let iconFingerPrintOutline = "finger-print-outline";
