
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fingerPrintSharp } from "ionicons/icons";

addIcons({ fingerPrintSharp });

export let iconFingerPrintSharp = fingerPrintSharp;
