
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fingerPrint } from "ionicons/icons";
import '../lib-icons'

addIcons({ fingerPrint });

export default fingerPrint;
