
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fishSharp } from "ionicons/icons";

addIcons({"fish-sharp": fishSharp });

export let iconFishSharp = "fish-sharp";
