
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fishOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ fishOutline });

export default fishOutline;
