
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fitness } from "ionicons/icons";
import '../lib-icons'

addIcons({ fitness });

export let iconFitness = fitness;
