
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fitnessSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ fitnessSharp });

export let iconFitnessSharp = fitnessSharp;
