
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flagOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ flagOutline });

export default flagOutline;
