
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flagSharp } from "ionicons/icons";

addIcons({"flag-sharp": flagSharp });

export let iconFlagSharp = "flag-sharp";
