
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flagSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ flagSharp });

export let iconFlagSharp = flagSharp;
