
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flameSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ flameSharp });

export default flameSharp;
