
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flashOffOutline } from "ionicons/icons";

addIcons({"flash-off-outline": flashOffOutline });

export let iconFlashOffOutline = "flash-off-outline";
