
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flashOffOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ flashOffOutline });

export let iconFlashOffOutline = flashOffOutline;
