
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flashlightSharp } from "ionicons/icons";

addIcons({ flashlightSharp });

export let iconFlashlightSharp = flashlightSharp;
