
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flaskSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ flaskSharp });

export let iconFlaskSharp = flaskSharp;
