
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flashOffSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ flashOffSharp });

export default flashOffSharp;
