
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flashOffSharp } from "ionicons/icons";

addIcons({"flash-off-sharp": flashOffSharp });

export let iconFlashOffSharp = "flash-off-sharp";
