
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flaskOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ flaskOutline });

export default flaskOutline;
