
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flashlightSharp } from "ionicons/icons";

addIcons({"flashlight-sharp": flashlightSharp });

export let iconFlashlightSharp = "flashlight-sharp";
