
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flashlightSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ flashlightSharp });

export default flashlightSharp;
