
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flashOffSharp } from "ionicons/icons";

addIcons({ flashOffSharp });

export let iconFlashOffSharp = flashOffSharp;
