
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flowerOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ flowerOutline });

export default flowerOutline;
