
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flowerOutline } from "ionicons/icons";

addIcons({ flowerOutline });

export let iconFlowerOutline = flowerOutline;
