
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { folderOutline } from "ionicons/icons";

addIcons({ folderOutline });

export let iconFolderOutline = "folderOutline";
