
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { folderOpenOutline } from "ionicons/icons";

addIcons({ folderOpenOutline });

export let iconFolderOpenOutline = "folderOpenOutline";
