
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { folderSharp } from "ionicons/icons";

addIcons({"folder-sharp": folderSharp });

export let iconFolderSharp = "folder-sharp";
