
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { folderOutline } from "ionicons/icons";

addIcons({"folder-outline": folderOutline });

export let iconFolderOutline = "folder-outline";
