
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { folderOpenSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ folderOpenSharp });

export let iconFolderOpenSharp = folderOpenSharp;
