
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { folderOpen } from "ionicons/icons";
import '../lib-icons'

addIcons({ folderOpen });

export default folderOpen;
