
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { folderOpenOutline } from "ionicons/icons";

addIcons({"folder-open-outline": folderOpenOutline });

export let iconFolderOpenOutline = "folder-open-outline";
