
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { footstepsSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ footstepsSharp });

export default footstepsSharp;
