
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { footballOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ footballOutline });

export let iconFootballOutline = footballOutline;
