
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { footstepsOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ footstepsOutline });

export let iconFootstepsOutline = footstepsOutline;
