
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { footstepsSharp } from "ionicons/icons";

addIcons({"footsteps-sharp": footstepsSharp });

export let iconFootstepsSharp = "footsteps-sharp";
