
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { footsteps } from "ionicons/icons";

addIcons({"footsteps": footsteps });

export let iconFootsteps = "footsteps";
