
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { funnelSharp } from "ionicons/icons";

addIcons({"funnel-sharp": funnelSharp });

export let iconFunnelSharp = "funnel-sharp";
