
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { funnelOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ funnelOutline });

export default funnelOutline;
