
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gameControllerSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ gameControllerSharp });

export default gameControllerSharp;
