
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gameController } from "ionicons/icons";

addIcons({"game-controller": gameController });

export let iconGameController = "game-controller";
