
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gameControllerSharp } from "ionicons/icons";

addIcons({ gameControllerSharp });

export let iconGameControllerSharp = gameControllerSharp;
