
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { giftOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ giftOutline });

export default giftOutline;
