
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitPullRequestOutline } from "ionicons/icons";

addIcons({ gitPullRequestOutline });

export let iconGitPullRequestOutline = "gitPullRequestOutline";
