
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitMergeOutline } from "ionicons/icons";

addIcons({"git-merge-outline": gitMergeOutline });

export let iconGitMergeOutline = "git-merge-outline";
