
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitBranchOutline } from "ionicons/icons";

addIcons({"git-branch-outline": gitBranchOutline });

export let iconGitBranchOutline = "git-branch-outline";
