
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitNetwork } from "ionicons/icons";
import '../lib-icons'

addIcons({ gitNetwork });

export let iconGitNetwork = gitNetwork;
