
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitMergeOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ gitMergeOutline });

export let iconGitMergeOutline = gitMergeOutline;
