
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitPullRequest } from "ionicons/icons";

addIcons({"git-pull-request": gitPullRequest });

export let iconGitPullRequest = "git-pull-request";
