
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitPullRequestSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ gitPullRequestSharp });

export let iconGitPullRequestSharp = gitPullRequestSharp;
