
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitCompareSharp } from "ionicons/icons";

addIcons({"git-compare-sharp": gitCompareSharp });

export let iconGitCompareSharp = "git-compare-sharp";
