
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitBranchSharp } from "ionicons/icons";

addIcons({ gitBranchSharp });

export let iconGitBranchSharp = "gitBranchSharp";
