
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitMergeSharp } from "ionicons/icons";

addIcons({"git-merge-sharp": gitMergeSharp });

export let iconGitMergeSharp = "git-merge-sharp";
