
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitPullRequestSharp } from "ionicons/icons";

addIcons({ gitPullRequestSharp });

export let iconGitPullRequestSharp = gitPullRequestSharp;
