
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitNetworkSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ gitNetworkSharp });

export default gitNetworkSharp;
