
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitCommitSharp } from "ionicons/icons";

addIcons({ gitCommitSharp });

export let iconGitCommitSharp = gitCommitSharp;
