
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitBranchOutline } from "ionicons/icons";

addIcons({ gitBranchOutline });

export let iconGitBranchOutline = "gitBranchOutline";
