
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitCompareSharp } from "ionicons/icons";

addIcons({ gitCompareSharp });

export let iconGitCompareSharp = gitCompareSharp;
