
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitCompareOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ gitCompareOutline });

export let iconGitCompareOutline = gitCompareOutline;
