
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { glassesOutline } from "ionicons/icons";

addIcons({ glassesOutline });

export let iconGlassesOutline = "glassesOutline";
