
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { glassesOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ glassesOutline });

export default glassesOutline;
