
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { glassesOutline } from "ionicons/icons";

addIcons({"glasses-outline": glassesOutline });

export let iconGlassesOutline = "glasses-outline";
