
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { globeSharp } from "ionicons/icons";

addIcons({"globe-sharp": globeSharp });

export let iconGlobeSharp = "globe-sharp";
