
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { globeOutline } from "ionicons/icons";

addIcons({ globeOutline });

export let iconGlobeOutline = "globeOutline";
