
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { globeSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ globeSharp });

export default globeSharp;
