
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { golfOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ golfOutline });

export default golfOutline;
