
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gridOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ gridOutline });

export let iconGridOutline = gridOutline;
