
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { hammerOutline } from "ionicons/icons";

addIcons({"hammer-outline": hammerOutline });

export let iconHammerOutline = "hammer-outline";
