
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { handRightSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ handRightSharp });

export default handRightSharp;
