
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { handRightSharp } from "ionicons/icons";

addIcons({ handRightSharp });

export let iconHandRightSharp = handRightSharp;
