
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { handLeftSharp } from "ionicons/icons";

addIcons({"hand-left-sharp": handLeftSharp });

export let iconHandLeftSharp = "hand-left-sharp";
