
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { handRightSharp } from "ionicons/icons";

addIcons({"hand-right-sharp": handRightSharp });

export let iconHandRightSharp = "hand-right-sharp";
