
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { handLeftSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ handLeftSharp });

export let iconHandLeftSharp = handLeftSharp;
