
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { handLeftOutline } from "ionicons/icons";

addIcons({ handLeftOutline });

export let iconHandLeftOutline = "handLeftOutline";
