
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { handLeftOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ handLeftOutline });

export default handLeftOutline;
