
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { happyOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ happyOutline });

export default happyOutline;
