
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { happySharp } from "ionicons/icons";

addIcons({"happy-sharp": happySharp });

export let iconHappySharp = "happy-sharp";
