
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { happySharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ happySharp });

export default happySharp;
