
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { hardwareChipSharp } from "ionicons/icons";

addIcons({ hardwareChipSharp });

export let iconHardwareChipSharp = hardwareChipSharp;
