
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { hardwareChipOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ hardwareChipOutline });

export default hardwareChipOutline;
