
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { hardwareChip } from "ionicons/icons";

addIcons({ hardwareChip });

export let iconHardwareChip = hardwareChip;
