
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { hardwareChip } from "ionicons/icons";

addIcons({"hardware-chip": hardwareChip });

export let iconHardwareChip = "hardware-chip";
