
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { headsetSharp } from "ionicons/icons";

addIcons({"headset-sharp": headsetSharp });

export let iconHeadsetSharp = "headset-sharp";
