
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { headsetOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ headsetOutline });

export let iconHeadsetOutline = headsetOutline;
