
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { headsetOutline } from "ionicons/icons";

addIcons({"headset-outline": headsetOutline });

export let iconHeadsetOutline = "headset-outline";
