
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartDislikeCircleSharp } from "ionicons/icons";

addIcons({"heart-dislike-circle-sharp": heartDislikeCircleSharp });

export let iconHeartDislikeCircleSharp = "heart-dislike-circle-sharp";
