
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartOutline } from "ionicons/icons";

addIcons({ heartOutline });

export let iconHeartOutline = "heartOutline";
