
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartDislikeCircle } from "ionicons/icons";

addIcons({ heartDislikeCircle });

export let iconHeartDislikeCircle = "heartDislikeCircle";
