
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ heartCircleSharp });

export let iconHeartCircleSharp = heartCircleSharp;
