
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartCircleOutline } from "ionicons/icons";

addIcons({ heartCircleOutline });

export let iconHeartCircleOutline = "heartCircleOutline";
