
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartDislikeSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ heartDislikeSharp });

export let iconHeartDislikeSharp = heartDislikeSharp;
