
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartOutline } from "ionicons/icons";

addIcons({"heart-outline": heartOutline });

export let iconHeartOutline = "heart-outline";
