
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ heartOutline });

export default heartOutline;
