
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartHalfOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ heartHalfOutline });

export default heartHalfOutline;
