
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartCircle } from "ionicons/icons";

addIcons({"heart-circle": heartCircle });

export let iconHeartCircle = "heart-circle";
