
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartDislikeOutline } from "ionicons/icons";

addIcons({ heartDislikeOutline });

export let iconHeartDislikeOutline = "heartDislikeOutline";
