
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartCircle } from "ionicons/icons";
import '../lib-icons'

addIcons({ heartCircle });

export default heartCircle;
