
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartDislikeOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ heartDislikeOutline });

export default heartDislikeOutline;
