
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartHalfSharp } from "ionicons/icons";

addIcons({ heartHalfSharp });

export let iconHeartHalfSharp = heartHalfSharp;
