
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartDislike } from "ionicons/icons";
import '../lib-icons'

addIcons({ heartDislike });

export default heartDislike;
