
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { helpSharp } from "ionicons/icons";

addIcons({"help-sharp": helpSharp });

export let iconHelpSharp = "help-sharp";
