
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { helpCircle } from "ionicons/icons";

addIcons({"help-circle": helpCircle });

export let iconHelpCircle = "help-circle";
