
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { helpCircleOutline } from "ionicons/icons";

addIcons({"help-circle-outline": helpCircleOutline });

export let iconHelpCircleOutline = "help-circle-outline";
