
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { helpSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ helpSharp });

export let iconHelpSharp = helpSharp;
