
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { helpCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ helpCircleOutline });

export default helpCircleOutline;
