
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { helpOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ helpOutline });

export let iconHelpOutline = helpOutline;
