
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { helpCircleSharp } from "ionicons/icons";

addIcons({ helpCircleSharp });

export let iconHelpCircleSharp = helpCircleSharp;
