
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { helpBuoySharp } from "ionicons/icons";

addIcons({"help-buoy-sharp": helpBuoySharp });

export let iconHelpBuoySharp = "help-buoy-sharp";
