
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { helpCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ helpCircleSharp });

export default helpCircleSharp;
