
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { helpCircleSharp } from "ionicons/icons";

addIcons({"help-circle-sharp": helpCircleSharp });

export let iconHelpCircleSharp = "help-circle-sharp";
