
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { homeOutline } from "ionicons/icons";

addIcons({"home-outline": homeOutline });

export let iconHomeOutline = "home-outline";
