
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { homeSharp } from "ionicons/icons";

addIcons({"home-sharp": homeSharp });

export let iconHomeSharp = "home-sharp";
