
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { hourglassOutline } from "ionicons/icons";

addIcons({ hourglassOutline });

export let iconHourglassOutline = "hourglassOutline";
