
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { hourglassSharp } from "ionicons/icons";

addIcons({ hourglassSharp });

export let iconHourglassSharp = "hourglassSharp";
