
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { hourglassOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ hourglassOutline });

export let iconHourglassOutline = hourglassOutline;
