
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { iceCreamOutline } from "ionicons/icons";

addIcons({ iceCreamOutline });

export let iconIceCreamOutline = "iceCreamOutline";
