
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { iceCreamSharp } from "ionicons/icons";

addIcons({"ice-cream-sharp": iceCreamSharp });

export let iconIceCreamSharp = "ice-cream-sharp";
