
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { idCardOutline } from "ionicons/icons";

addIcons({"id-card-outline": idCardOutline });

export let iconIdCardOutline = "id-card-outline";
