
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { idCardSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ idCardSharp });

export let iconIdCardSharp = idCardSharp;
