
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { idCardSharp } from "ionicons/icons";

addIcons({"id-card-sharp": idCardSharp });

export let iconIdCardSharp = "id-card-sharp";
