
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { infiniteSharp } from "ionicons/icons";

addIcons({ infiniteSharp });

export let iconInfiniteSharp = "infiniteSharp";
