
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { informationCircleSharp } from "ionicons/icons";

addIcons({ informationCircleSharp });

export let iconInformationCircleSharp = "informationCircleSharp";
