
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { informationCircle } from "ionicons/icons";

addIcons({"information-circle": informationCircle });

export let iconInformationCircle = "information-circle";
