
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { informationSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ informationSharp });

export default informationSharp;
