
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { informationSharp } from "ionicons/icons";

addIcons({"information-sharp": informationSharp });

export let iconInformationSharp = "information-sharp";
