
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { informationCircle } from "ionicons/icons";

addIcons({ informationCircle });

export let iconInformationCircle = "informationCircle";
