
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { invertModeOutline } from "ionicons/icons";

addIcons({"invert-mode-outline": invertModeOutline });

export let iconInvertModeOutline = "invert-mode-outline";
