
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { invertMode } from "ionicons/icons";
import '../lib-icons'

addIcons({ invertMode });

export let iconInvertMode = invertMode;
