
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { invertModeSharp } from "ionicons/icons";

addIcons({ invertModeSharp });

export let iconInvertModeSharp = "invertModeSharp";
