
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { invertModeOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ invertModeOutline });

export let iconInvertModeOutline = invertModeOutline;
