
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { invertModeSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ invertModeSharp });

export default invertModeSharp;
