
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { journalSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ journalSharp });

export let iconJournalSharp = journalSharp;
