
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { journalOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ journalOutline });

export default journalOutline;
