
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { keySharp } from "ionicons/icons";

addIcons({"key-sharp": keySharp });

export let iconKeySharp = "key-sharp";
