
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { keypadOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ keypadOutline });

export let iconKeypadOutline = keypadOutline;
