
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { keypadSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ keypadSharp });

export let iconKeypadSharp = keypadSharp;
