
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { keypadOutline } from "ionicons/icons";

addIcons({"keypad-outline": keypadOutline });

export let iconKeypadOutline = "keypad-outline";
