
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { languageOutline } from "ionicons/icons";

addIcons({"language-outline": languageOutline });

export let iconLanguageOutline = "language-outline";
