
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { languageOutline } from "ionicons/icons";

addIcons({ languageOutline });

export let iconLanguageOutline = "languageOutline";
