
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { languageSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ languageSharp });

export default languageSharp;
