
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { languageOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ languageOutline });

export default languageOutline;
