
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { laptopSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ laptopSharp });

export default laptopSharp;
