
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { laptopOutline } from "ionicons/icons";

addIcons({ laptopOutline });

export let iconLaptopOutline = laptopOutline;
