
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { layersSharp } from "ionicons/icons";

addIcons({"layers-sharp": layersSharp });

export let iconLayersSharp = "layers-sharp";
