
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { layersOutline } from "ionicons/icons";

addIcons({ layersOutline });

export let iconLayersOutline = "layersOutline";
