
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { libraryOutline } from "ionicons/icons";

addIcons({ libraryOutline });

export let iconLibraryOutline = libraryOutline;
