
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { libraryOutline } from "ionicons/icons";

addIcons({"library-outline": libraryOutline });

export let iconLibraryOutline = "library-outline";
