
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { linkSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ linkSharp });

export let iconLinkSharp = linkSharp;
