
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { listSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ listSharp });

export let iconListSharp = listSharp;
