
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { listCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ listCircleOutline });

export let iconListCircleOutline = listCircleOutline;
