
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { listCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ listCircleSharp });

export default listCircleSharp;
