
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { listOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ listOutline });

export let iconListOutline = listOutline;
