
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { listCircleSharp } from "ionicons/icons";

addIcons({ listCircleSharp });

export let iconListCircleSharp = listCircleSharp;
