
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { listCircle } from "ionicons/icons";

addIcons({"list-circle": listCircle });

export let iconListCircle = "list-circle";
