
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { locateOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ locateOutline });

export let iconLocateOutline = locateOutline;
