
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { locationSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ locationSharp });

export default locationSharp;
