
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { locateSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ locateSharp });

export let iconLocateSharp = locateSharp;
