
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { locationOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ locationOutline });

export default locationOutline;
