
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { locationSharp } from "ionicons/icons";

addIcons({"location-sharp": locationSharp });

export let iconLocationSharp = "location-sharp";
