
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { locationSharp } from "ionicons/icons";

addIcons({ locationSharp });

export let iconLocationSharp = "locationSharp";
