
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { lockClosedSharp } from "ionicons/icons";

addIcons({ lockClosedSharp });

export let iconLockClosedSharp = "lockClosedSharp";
