
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { lockOpenSharp } from "ionicons/icons";

addIcons({"lock-open-sharp": lockOpenSharp });

export let iconLockOpenSharp = "lock-open-sharp";
