
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { lockOpenOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ lockOpenOutline });

export let iconLockOpenOutline = lockOpenOutline;
