
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { lockClosedSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ lockClosedSharp });

export default lockClosedSharp;
