
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { lockClosedOutline } from "ionicons/icons";

addIcons({ lockClosedOutline });

export let iconLockClosedOutline = lockClosedOutline;
