
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { lockClosedOutline } from "ionicons/icons";

addIcons({"lock-closed-outline": lockClosedOutline });

export let iconLockClosedOutline = "lock-closed-outline";
