
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logOutSharp } from "ionicons/icons";

addIcons({"log-out-sharp": logOutSharp });

export let iconLogOutSharp = "log-out-sharp";
