
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logOutSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ logOutSharp });

export let iconLogOutSharp = logOutSharp;
