
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logInOutline } from "ionicons/icons";

addIcons({"log-in-outline": logInOutline });

export let iconLogInOutline = "log-in-outline";
