
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logOutOutline } from "ionicons/icons";

addIcons({"log-out-outline": logOutOutline });

export let iconLogOutOutline = "log-out-outline";
