
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logInSharp } from "ionicons/icons";

addIcons({"log-in-sharp": logInSharp });

export let iconLogInSharp = "log-in-sharp";
