
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logInOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ logInOutline });

export default logInOutline;
