
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoGitlab } from "ionicons/icons";

addIcons({"logo-gitlab": logoGitlab });

export let iconLogoGitlab = "logo-gitlab";
