
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoCapacitor } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoCapacitor });

export default logoCapacitor;
