
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoBuffer } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoBuffer });

export let iconLogoBuffer = logoBuffer;
