
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoPython } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoPython });

export default logoPython;
