
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoTiktok } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoTiktok });

export let iconLogoTiktok = logoTiktok;
