
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoNoSmoking } from "ionicons/icons";

addIcons({"logo-no-smoking": logoNoSmoking });

export let iconLogoNoSmoking = "logo-no-smoking";
