
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoPaypal } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoPaypal });

export let iconLogoPaypal = logoPaypal;
