
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoStackoverflow } from "ionicons/icons";

addIcons({ logoStackoverflow });

export let iconLogoStackoverflow = logoStackoverflow;
