
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoBitcoin } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoBitcoin });

export let iconLogoBitcoin = logoBitcoin;
