
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoMicrosoft } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoMicrosoft });

export default logoMicrosoft;
