
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoAlipay } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoAlipay });

export let iconLogoAlipay = logoAlipay;
