
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoWordpress } from "ionicons/icons";

addIcons({"logo-wordpress": logoWordpress });

export let iconLogoWordpress = "logo-wordpress";
