
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoJavascript } from "ionicons/icons";

addIcons({ logoJavascript });

export let iconLogoJavascript = logoJavascript;
