
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoIonitron } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoIonitron });

export let iconLogoIonitron = logoIonitron;
