
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoAppleAr } from "ionicons/icons";

addIcons({"logo-apple-ar": logoAppleAr });

export let iconLogoAppleAr = "logo-apple-ar";
