
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoHtml5 } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoHtml5 });

export let iconLogoHtml5 = logoHtml5;
