
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoHackernews } from "ionicons/icons";

addIcons({"logo-hackernews": logoHackernews });

export let iconLogoHackernews = "logo-hackernews";
