
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoDiscord } from "ionicons/icons";

addIcons({"logo-discord": logoDiscord });

export let iconLogoDiscord = "logo-discord";
