
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoBitbucket } from "ionicons/icons";

addIcons({ logoBitbucket });

export let iconLogoBitbucket = "logoBitbucket";
