
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoFirefox } from "ionicons/icons";

addIcons({"logo-firefox": logoFirefox });

export let iconLogoFirefox = "logo-firefox";
