
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoDribbble } from "ionicons/icons";

addIcons({ logoDribbble });

export let iconLogoDribbble = "logoDribbble";
