
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoGithub } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoGithub });

export let iconLogoGithub = logoGithub;
