
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoClosedCaptioning } from "ionicons/icons";

addIcons({ logoClosedCaptioning });

export let iconLogoClosedCaptioning = logoClosedCaptioning;
