
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoDesignernews } from "ionicons/icons";

addIcons({ logoDesignernews });

export let iconLogoDesignernews = logoDesignernews;
