
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoMarkdown } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoMarkdown });

export let iconLogoMarkdown = logoMarkdown;
