
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoWindows } from "ionicons/icons";

addIcons({"logo-windows": logoWindows });

export let iconLogoWindows = "logo-windows";
