
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoAngular } from "ionicons/icons";

addIcons({"logo-angular": logoAngular });

export let iconLogoAngular = "logo-angular";
