
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoSnapchat } from "ionicons/icons";

addIcons({ logoSnapchat });

export let iconLogoSnapchat = "logoSnapchat";
