
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoMedium } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoMedium });

export let iconLogoMedium = logoMedium;
