
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoEdge } from "ionicons/icons";

addIcons({"logo-edge": logoEdge });

export let iconLogoEdge = "logo-edge";
