
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoWebComponent } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoWebComponent });

export default logoWebComponent;
