
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoDeviantart } from "ionicons/icons";

addIcons({"logo-deviantart": logoDeviantart });

export let iconLogoDeviantart = "logo-deviantart";
