
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoFoursquare } from "ionicons/icons";

addIcons({ logoFoursquare });

export let iconLogoFoursquare = "logoFoursquare";
