
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoWebComponent } from "ionicons/icons";

addIcons({"logo-web-component": logoWebComponent });

export let iconLogoWebComponent = "logo-web-component";
