
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoGooglePlaystore } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoGooglePlaystore });

export default logoGooglePlaystore;
