
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoElectron } from "ionicons/icons";

addIcons({ logoElectron });

export let iconLogoElectron = "logoElectron";
