
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoInstagram } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoInstagram });

export let iconLogoInstagram = logoInstagram;
