
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoFirebase } from "ionicons/icons";

addIcons({"logo-firebase": logoFirebase });

export let iconLogoFirebase = "logo-firebase";
