
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoNodejs } from "ionicons/icons";

addIcons({"logo-nodejs": logoNodejs });

export let iconLogoNodejs = "logo-nodejs";
