
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoTumblr } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoTumblr });

export let iconLogoTumblr = logoTumblr;
