
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoWebComponent } from "ionicons/icons";

addIcons({ logoWebComponent });

export let iconLogoWebComponent = "logoWebComponent";
