
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoAppflow } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoAppflow });

export default logoAppflow;
