
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoNoSmoking } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoNoSmoking });

export default logoNoSmoking;
