
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoVenmo } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoVenmo });

export let iconLogoVenmo = logoVenmo;
