
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoSnapchat } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoSnapchat });

export default logoSnapchat;
