
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoRss } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoRss });

export let iconLogoRss = logoRss;
