
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoDocker } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoDocker });

export default logoDocker;
