
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoPython } from "ionicons/icons";

addIcons({"logo-python": logoPython });

export let iconLogoPython = "logo-python";
