
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoDropbox } from "ionicons/icons";

addIcons({"logo-dropbox": logoDropbox });

export let iconLogoDropbox = "logo-dropbox";
