
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoWordpress } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoWordpress });

export default logoWordpress;
