
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoAppleAppstore } from "ionicons/icons";

addIcons({"logo-apple-appstore": logoAppleAppstore });

export let iconLogoAppleAppstore = "logo-apple-appstore";
