
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoOctocat } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoOctocat });

export default logoOctocat;
