
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoSkype } from "ionicons/icons";

addIcons({"logo-skype": logoSkype });

export let iconLogoSkype = "logo-skype";
