
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoTux } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoTux });

export let iconLogoTux = logoTux;
