
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoPlaystation } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoPlaystation });

export let iconLogoPlaystation = logoPlaystation;
