
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoAmplify } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoAmplify });

export default logoAmplify;
