
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoWhatsapp } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoWhatsapp });

export let iconLogoWhatsapp = logoWhatsapp;
