
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoCodepen } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoCodepen });

export let iconLogoCodepen = logoCodepen;
