
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoAlipay } from "ionicons/icons";

addIcons({"logo-alipay": logoAlipay });

export let iconLogoAlipay = "logo-alipay";
