
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoDropbox } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoDropbox });

export let iconLogoDropbox = logoDropbox;
