
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoFigma } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoFigma });

export let iconLogoFigma = logoFigma;
