
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoXbox } from "ionicons/icons";

addIcons({"logo-xbox": logoXbox });

export let iconLogoXbox = "logo-xbox";
