
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoAppleAr } from "ionicons/icons";
import '../lib-icons'

addIcons({ logoAppleAr });

export let iconLogoAppleAr = logoAppleAr;
