
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoMarkdown } from "ionicons/icons";

addIcons({ logoMarkdown });

export let iconLogoMarkdown = "logoMarkdown";
