
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { magnetOutline } from "ionicons/icons";

addIcons({ magnetOutline });

export let iconMagnetOutline = magnetOutline;
