
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { magnetOutline } from "ionicons/icons";

addIcons({"magnet-outline": magnetOutline });

export let iconMagnetOutline = "magnet-outline";
