
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { mailOpen } from "ionicons/icons";
import '../lib-icons'

addIcons({ mailOpen });

export let iconMailOpen = mailOpen;
