
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { mailUnreadSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ mailUnreadSharp });

export let iconMailUnreadSharp = mailUnreadSharp;
