
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { mailUnreadOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ mailUnreadOutline });

export let iconMailUnreadOutline = mailUnreadOutline;
