
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { mailUnread } from "ionicons/icons";

addIcons({"mail-unread": mailUnread });

export let iconMailUnread = "mail-unread";
