
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { mailOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ mailOutline });

export let iconMailOutline = mailOutline;
