
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { mailOpenSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ mailOpenSharp });

export default mailOpenSharp;
