
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { mailOpenSharp } from "ionicons/icons";

addIcons({"mail-open-sharp": mailOpenSharp });

export let iconMailOpenSharp = "mail-open-sharp";
