
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { maleFemaleSharp } from "ionicons/icons";

addIcons({"male-female-sharp": maleFemaleSharp });

export let iconMaleFemaleSharp = "male-female-sharp";
