
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { maleFemale } from "ionicons/icons";
import '../lib-icons'

addIcons({ maleFemale });

export let iconMaleFemale = maleFemale;
