
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { manOutline } from "ionicons/icons";

addIcons({"man-outline": manOutline });

export let iconManOutline = "man-outline";
