
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { mapOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ mapOutline });

export default mapOutline;
