
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { medalOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ medalOutline });

export default medalOutline;
