
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { medalOutline } from "ionicons/icons";

addIcons({ medalOutline });

export let iconMedalOutline = medalOutline;
