
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { medicalOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ medicalOutline });

export default medicalOutline;
