
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { medicalOutline } from "ionicons/icons";

addIcons({"medical-outline": medicalOutline });

export let iconMedicalOutline = "medical-outline";
