
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { medical } from "ionicons/icons";
import '../lib-icons'

addIcons({ medical });

export let iconMedical = medical;
