
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { medicalSharp } from "ionicons/icons";

addIcons({ medicalSharp });

export let iconMedicalSharp = medicalSharp;
