
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { medkitOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ medkitOutline });

export let iconMedkitOutline = medkitOutline;
