
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { megaphoneOutline } from "ionicons/icons";

addIcons({ megaphoneOutline });

export let iconMegaphoneOutline = megaphoneOutline;
