
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { megaphoneSharp } from "ionicons/icons";

addIcons({ megaphoneSharp });

export let iconMegaphoneSharp = megaphoneSharp;
