
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { menuOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ menuOutline });

export let iconMenuOutline = menuOutline;
