
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { micCircle } from "ionicons/icons";
import '../lib-icons'

addIcons({ micCircle });

export let iconMicCircle = micCircle;
