
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { micOffCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ micOffCircleSharp });

export let iconMicOffCircleSharp = micOffCircleSharp;
