
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { micOffSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ micOffSharp });

export let iconMicOffSharp = micOffSharp;
