
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { micOutline } from "ionicons/icons";

addIcons({"mic-outline": micOutline });

export let iconMicOutline = "mic-outline";
