
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { micOffCircle } from "ionicons/icons";

addIcons({ micOffCircle });

export let iconMicOffCircle = micOffCircle;
