
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { micOffOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ micOffOutline });

export let iconMicOffOutline = micOffOutline;
