
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { micOffOutline } from "ionicons/icons";

addIcons({"mic-off-outline": micOffOutline });

export let iconMicOffOutline = "mic-off-outline";
