
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { micOffCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ micOffCircleOutline });

export default micOffCircleOutline;
