
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { micCircleOutline } from "ionicons/icons";

addIcons({"mic-circle-outline": micCircleOutline });

export let iconMicCircleOutline = "mic-circle-outline";
