
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { moonOutline } from "ionicons/icons";

addIcons({"moon-outline": moonOutline });

export let iconMoonOutline = "moon-outline";
