
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { moonOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ moonOutline });

export default moonOutline;
