
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { moveSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ moveSharp });

export let iconMoveSharp = moveSharp;
