
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { musicalNoteOutline } from "ionicons/icons";

addIcons({"musical-note-outline": musicalNoteOutline });

export let iconMusicalNoteOutline = "musical-note-outline";
