
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { musicalNoteSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ musicalNoteSharp });

export let iconMusicalNoteSharp = musicalNoteSharp;
