
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { musicalNoteOutline } from "ionicons/icons";

addIcons({ musicalNoteOutline });

export let iconMusicalNoteOutline = "musicalNoteOutline";
