
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { musicalNotesOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ musicalNotesOutline });

export let iconMusicalNotesOutline = musicalNotesOutline;
