
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { musicalNote } from "ionicons/icons";
import '../lib-icons'

addIcons({ musicalNote });

export default musicalNote;
