
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { musicalNotes } from "ionicons/icons";

addIcons({"musical-notes": musicalNotes });

export let iconMusicalNotes = "musical-notes";
