
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { musicalNoteSharp } from "ionicons/icons";

addIcons({"musical-note-sharp": musicalNoteSharp });

export let iconMusicalNoteSharp = "musical-note-sharp";
