
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { musicalNotes } from "ionicons/icons";

addIcons({ musicalNotes });

export let iconMusicalNotes = musicalNotes;
