
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { musicalNotes } from "ionicons/icons";
import '../lib-icons'

addIcons({ musicalNotes });

export let iconMusicalNotes = musicalNotes;
