
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { musicalNotesSharp } from "ionicons/icons";

addIcons({ musicalNotesSharp });

export let iconMusicalNotesSharp = "musicalNotesSharp";
