
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { navigateSharp } from "ionicons/icons";

addIcons({"navigate-sharp": navigateSharp });

export let iconNavigateSharp = "navigate-sharp";
