
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { navigateCircle } from "ionicons/icons";
import '../lib-icons'

addIcons({ navigateCircle });

export default navigateCircle;
