
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { navigateCircleSharp } from "ionicons/icons";

addIcons({"navigate-circle-sharp": navigateCircleSharp });

export let iconNavigateCircleSharp = "navigate-circle-sharp";
