
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { navigateOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ navigateOutline });

export default navigateOutline;
