
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { navigateSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ navigateSharp });

export default navigateSharp;
