
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { navigateCircle } from "ionicons/icons";

addIcons({ navigateCircle });

export let iconNavigateCircle = "navigateCircle";
