
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { navigateSharp } from "ionicons/icons";

addIcons({ navigateSharp });

export let iconNavigateSharp = "navigateSharp";
