
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { newspaperSharp } from "ionicons/icons";

addIcons({ newspaperSharp });

export let iconNewspaperSharp = newspaperSharp;
