
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { newspaperOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ newspaperOutline });

export let iconNewspaperOutline = newspaperOutline;
