
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { newspaperOutline } from "ionicons/icons";

addIcons({"newspaper-outline": newspaperOutline });

export let iconNewspaperOutline = "newspaper-outline";
