
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { newspaper } from "ionicons/icons";
import '../lib-icons'

addIcons({ newspaper });

export let iconNewspaper = newspaper;
