
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsOff } from "ionicons/icons";

addIcons({"notifications-off": notificationsOff });

export let iconNotificationsOff = "notifications-off";
