
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsOutline } from "ionicons/icons";

addIcons({ notificationsOutline });

export let iconNotificationsOutline = notificationsOutline;
