
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsOff } from "ionicons/icons";
import '../lib-icons'

addIcons({ notificationsOff });

export default notificationsOff;
