
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsOffOutline } from "ionicons/icons";

addIcons({"notifications-off-outline": notificationsOffOutline });

export let iconNotificationsOffOutline = "notifications-off-outline";
