
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsOffSharp } from "ionicons/icons";

addIcons({"notifications-off-sharp": notificationsOffSharp });

export let iconNotificationsOffSharp = "notifications-off-sharp";
