
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsCircle } from "ionicons/icons";
import '../lib-icons'

addIcons({ notificationsCircle });

export default notificationsCircle;
