
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsOffCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ notificationsOffCircleSharp });

export let iconNotificationsOffCircleSharp = notificationsOffCircleSharp;
