
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsOffCircleSharp } from "ionicons/icons";

addIcons({"notifications-off-circle-sharp": notificationsOffCircleSharp });

export let iconNotificationsOffCircleSharp = "notifications-off-circle-sharp";
