
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsOffCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ notificationsOffCircleOutline });

export let iconNotificationsOffCircleOutline = notificationsOffCircleOutline;
