
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsOff } from "ionicons/icons";

addIcons({ notificationsOff });

export let iconNotificationsOff = notificationsOff;
