
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsCircle } from "ionicons/icons";

addIcons({ notificationsCircle });

export let iconNotificationsCircle = "notificationsCircle";
