
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsOffCircle } from "ionicons/icons";

addIcons({"notifications-off-circle": notificationsOffCircle });

export let iconNotificationsOffCircle = "notifications-off-circle";
