
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsOffOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ notificationsOffOutline });

export let iconNotificationsOffOutline = notificationsOffOutline;
