
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsCircle } from "ionicons/icons";

addIcons({"notifications-circle": notificationsCircle });

export let iconNotificationsCircle = "notifications-circle";
