
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notifications } from "ionicons/icons";

addIcons({ notifications });

export let iconNotifications = notifications;
