
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsOffCircleOutline } from "ionicons/icons";

addIcons({"notifications-off-circle-outline": notificationsOffCircleOutline });

export let iconNotificationsOffCircleOutline = "notifications-off-circle-outline";
