
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ notificationsSharp });

export default notificationsSharp;
