
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { nuclearOutline } from "ionicons/icons";

addIcons({ nuclearOutline });

export let iconNuclearOutline = "nuclearOutline";
