
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { nuclearSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ nuclearSharp });

export default nuclearSharp;
