
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { nuclearSharp } from "ionicons/icons";

addIcons({"nuclear-sharp": nuclearSharp });

export let iconNuclearSharp = "nuclear-sharp";
