
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { nuclearOutline } from "ionicons/icons";

addIcons({"nuclear-outline": nuclearOutline });

export let iconNuclearOutline = "nuclear-outline";
