
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { nutritionOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ nutritionOutline });

export default nutritionOutline;
