
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { nutrition } from "ionicons/icons";

addIcons({"nutrition": nutrition });

export let iconNutrition = "nutrition";
