
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { openOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ openOutline });

export let iconOpenOutline = openOutline;
