
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { optionsSharp } from "ionicons/icons";

addIcons({"options-sharp": optionsSharp });

export let iconOptionsSharp = "options-sharp";
