
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { optionsSharp } from "ionicons/icons";

addIcons({ optionsSharp });

export let iconOptionsSharp = optionsSharp;
