
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { optionsOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ optionsOutline });

export let iconOptionsOutline = optionsOutline;
