
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { paperPlaneOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ paperPlaneOutline });

export default paperPlaneOutline;
