
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { paperPlaneSharp } from "ionicons/icons";

addIcons({ paperPlaneSharp });

export let iconPaperPlaneSharp = "paperPlaneSharp";
