
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { paperPlaneSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ paperPlaneSharp });

export default paperPlaneSharp;
