
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { paperPlane } from "ionicons/icons";
import '../lib-icons'

addIcons({ paperPlane });

export let iconPaperPlane = paperPlane;
