
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { paperPlane } from "ionicons/icons";

addIcons({"paper-plane": paperPlane });

export let iconPaperPlane = "paper-plane";
