
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { partlySunnySharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ partlySunnySharp });

export let iconPartlySunnySharp = partlySunnySharp;
