
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { partlySunnyOutline } from "ionicons/icons";

addIcons({ partlySunnyOutline });

export let iconPartlySunnyOutline = partlySunnyOutline;
