
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { partlySunnySharp } from "ionicons/icons";

addIcons({"partly-sunny-sharp": partlySunnySharp });

export let iconPartlySunnySharp = "partly-sunny-sharp";
