
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { partlySunnySharp } from "ionicons/icons";

addIcons({ partlySunnySharp });

export let iconPartlySunnySharp = "partlySunnySharp";
