
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { partlySunnyOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ partlySunnyOutline });

export default partlySunnyOutline;
