
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pauseCircleSharp } from "ionicons/icons";

addIcons({ pauseCircleSharp });

export let iconPauseCircleSharp = "pauseCircleSharp";
