
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pauseSharp } from "ionicons/icons";

addIcons({"pause-sharp": pauseSharp });

export let iconPauseSharp = "pause-sharp";
