
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pauseCircleSharp } from "ionicons/icons";

addIcons({"pause-circle-sharp": pauseCircleSharp });

export let iconPauseCircleSharp = "pause-circle-sharp";
