
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pencilOutline } from "ionicons/icons";

addIcons({"pencil-outline": pencilOutline });

export let iconPencilOutline = "pencil-outline";
