
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pencilOutline } from "ionicons/icons";

addIcons({ pencilOutline });

export let iconPencilOutline = "pencilOutline";
