
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { peopleCircleOutline } from "ionicons/icons";

addIcons({ peopleCircleOutline });

export let iconPeopleCircleOutline = "peopleCircleOutline";
