
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { peopleCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ peopleCircleSharp });

export let iconPeopleCircleSharp = peopleCircleSharp;
