
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { peopleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ peopleOutline });

export let iconPeopleOutline = peopleOutline;
