
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { peopleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ peopleSharp });

export let iconPeopleSharp = peopleSharp;
