
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { peopleCircle } from "ionicons/icons";

addIcons({"people-circle": peopleCircle });

export let iconPeopleCircle = "people-circle";
