
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personRemoveSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ personRemoveSharp });

export default personRemoveSharp;
