
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personCircle } from "ionicons/icons";
import '../lib-icons'

addIcons({ personCircle });

export let iconPersonCircle = personCircle;
