
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personRemoveSharp } from "ionicons/icons";

addIcons({"person-remove-sharp": personRemoveSharp });

export let iconPersonRemoveSharp = "person-remove-sharp";
