
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personCircleOutline } from "ionicons/icons";

addIcons({ personCircleOutline });

export let iconPersonCircleOutline = "personCircleOutline";
