
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ personCircleSharp });

export default personCircleSharp;
