
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personCircleSharp } from "ionicons/icons";

addIcons({ personCircleSharp });

export let iconPersonCircleSharp = "personCircleSharp";
