
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personAddOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ personAddOutline });

export default personAddOutline;
