
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personRemoveSharp } from "ionicons/icons";

addIcons({ personRemoveSharp });

export let iconPersonRemoveSharp = personRemoveSharp;
