
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personOutline } from "ionicons/icons";

addIcons({"person-outline": personOutline });

export let iconPersonOutline = "person-outline";
