
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personRemoveOutline } from "ionicons/icons";

addIcons({ personRemoveOutline });

export let iconPersonRemoveOutline = personRemoveOutline;
