
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personOutline } from "ionicons/icons";

addIcons({ personOutline });

export let iconPersonOutline = personOutline;
