
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personAddOutline } from "ionicons/icons";

addIcons({"person-add-outline": personAddOutline });

export let iconPersonAddOutline = "person-add-outline";
