
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personRemove } from "ionicons/icons";
import '../lib-icons'

addIcons({ personRemove });

export let iconPersonRemove = personRemove;
