
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personAddSharp } from "ionicons/icons";

addIcons({ personAddSharp });

export let iconPersonAddSharp = personAddSharp;
