
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { phonePortrait } from "ionicons/icons";
import '../lib-icons'

addIcons({ phonePortrait });

export default phonePortrait;
