
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { phonePortraitSharp } from "ionicons/icons";

addIcons({ phonePortraitSharp });

export let iconPhonePortraitSharp = "phonePortraitSharp";
