
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { phoneLandscapeSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ phoneLandscapeSharp });

export let iconPhoneLandscapeSharp = phoneLandscapeSharp;
