
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { phonePortraitOutline } from "ionicons/icons";

addIcons({ phonePortraitOutline });

export let iconPhonePortraitOutline = "phonePortraitOutline";
