
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { phoneLandscapeOutline } from "ionicons/icons";

addIcons({"phone-landscape-outline": phoneLandscapeOutline });

export let iconPhoneLandscapeOutline = "phone-landscape-outline";
