
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { phoneLandscapeOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ phoneLandscapeOutline });

export default phoneLandscapeOutline;
