
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { phonePortrait } from "ionicons/icons";

addIcons({"phone-portrait": phonePortrait });

export let iconPhonePortrait = "phone-portrait";
