
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { phoneLandscapeSharp } from "ionicons/icons";

addIcons({"phone-landscape-sharp": phoneLandscapeSharp });

export let iconPhoneLandscapeSharp = "phone-landscape-sharp";
