
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { phonePortrait } from "ionicons/icons";

addIcons({ phonePortrait });

export let iconPhonePortrait = "phonePortrait";
