
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pieChartOutline } from "ionicons/icons";

addIcons({"pie-chart-outline": pieChartOutline });

export let iconPieChartOutline = "pie-chart-outline";
