
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pieChartSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ pieChartSharp });

export default pieChartSharp;
