
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pinOutline } from "ionicons/icons";

addIcons({"pin-outline": pinOutline });

export let iconPinOutline = "pin-outline";
