
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pinSharp } from "ionicons/icons";

addIcons({"pin-sharp": pinSharp });

export let iconPinSharp = "pin-sharp";
