
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pintOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ pintOutline });

export let iconPintOutline = pintOutline;
