
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pintSharp } from "ionicons/icons";

addIcons({"pint-sharp": pintSharp });

export let iconPintSharp = "pint-sharp";
