
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pizzaOutline } from "ionicons/icons";

addIcons({"pizza-outline": pizzaOutline });

export let iconPizzaOutline = "pizza-outline";
