
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pizzaSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ pizzaSharp });

export default pizzaSharp;
