
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playForwardOutline } from "ionicons/icons";

addIcons({ playForwardOutline });

export let iconPlayForwardOutline = playForwardOutline;
