
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playSkipBackCircle } from "ionicons/icons";

addIcons({"play-skip-back-circle": playSkipBackCircle });

export let iconPlaySkipBackCircle = "play-skip-back-circle";
