
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playCircle } from "ionicons/icons";
import '../lib-icons'

addIcons({ playCircle });

export let iconPlayCircle = playCircle;
