
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playSkipBackCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ playSkipBackCircleSharp });

export let iconPlaySkipBackCircleSharp = playSkipBackCircleSharp;
