
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playSkipForwardCircleOutline } from "ionicons/icons";

addIcons({ playSkipForwardCircleOutline });

export let iconPlaySkipForwardCircleOutline = "playSkipForwardCircleOutline";
