
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playSkipForwardCircle } from "ionicons/icons";

addIcons({"play-skip-forward-circle": playSkipForwardCircle });

export let iconPlaySkipForwardCircle = "play-skip-forward-circle";
