
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playSkipBackOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ playSkipBackOutline });

export let iconPlaySkipBackOutline = playSkipBackOutline;
