
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playSkipBackCircleSharp } from "ionicons/icons";

addIcons({"play-skip-back-circle-sharp": playSkipBackCircleSharp });

export let iconPlaySkipBackCircleSharp = "play-skip-back-circle-sharp";
