
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playForwardOutline } from "ionicons/icons";

addIcons({"play-forward-outline": playForwardOutline });

export let iconPlayForwardOutline = "play-forward-outline";
