
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ playOutline });

export default playOutline;
