
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playForwardCircle } from "ionicons/icons";

addIcons({"play-forward-circle": playForwardCircle });

export let iconPlayForwardCircle = "play-forward-circle";
