
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playSkipBackCircleOutline } from "ionicons/icons";

addIcons({"play-skip-back-circle-outline": playSkipBackCircleOutline });

export let iconPlaySkipBackCircleOutline = "play-skip-back-circle-outline";
