
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playForwardCircleSharp } from "ionicons/icons";

addIcons({ playForwardCircleSharp });

export let iconPlayForwardCircleSharp = playForwardCircleSharp;
