
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playBackCircleOutline } from "ionicons/icons";

addIcons({"play-back-circle-outline": playBackCircleOutline });

export let iconPlayBackCircleOutline = "play-back-circle-outline";
