
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playBackCircle } from "ionicons/icons";

addIcons({ playBackCircle });

export let iconPlayBackCircle = "playBackCircle";
