
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playBackCircleSharp } from "ionicons/icons";

addIcons({ playBackCircleSharp });

export let iconPlayBackCircleSharp = playBackCircleSharp;
