
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playSkipBackOutline } from "ionicons/icons";

addIcons({ playSkipBackOutline });

export let iconPlaySkipBackOutline = "playSkipBackOutline";
