
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ playCircleOutline });

export let iconPlayCircleOutline = playCircleOutline;
