
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playBack } from "ionicons/icons";
import '../lib-icons'

addIcons({ playBack });

export let iconPlayBack = playBack;
