
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playBackCircleSharp } from "ionicons/icons";

addIcons({"play-back-circle-sharp": playBackCircleSharp });

export let iconPlayBackCircleSharp = "play-back-circle-sharp";
