
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playSkipForwardCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ playSkipForwardCircleOutline });

export default playSkipForwardCircleOutline;
