
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playBack } from "ionicons/icons";

addIcons({"play-back": playBack });

export let iconPlayBack = "play-back";
