
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playBackOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ playBackOutline });

export default playBackOutline;
