
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playSkipBackCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ playSkipBackCircleOutline });

export let iconPlaySkipBackCircleOutline = playSkipBackCircleOutline;
