
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playForwardCircle } from "ionicons/icons";

addIcons({ playForwardCircle });

export let iconPlayForwardCircle = playForwardCircle;
