
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playForwardSharp } from "ionicons/icons";

addIcons({"play-forward-sharp": playForwardSharp });

export let iconPlayForwardSharp = "play-forward-sharp";
