
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playOutline } from "ionicons/icons";

addIcons({"play-outline": playOutline });

export let iconPlayOutline = "play-outline";
