
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playBackCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ playBackCircleOutline });

export default playBackCircleOutline;
