
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playCircleSharp } from "ionicons/icons";

addIcons({ playCircleSharp });

export let iconPlayCircleSharp = playCircleSharp;
