
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playSkipForwardSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ playSkipForwardSharp });

export let iconPlaySkipForwardSharp = playSkipForwardSharp;
