
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playSkipForwardOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ playSkipForwardOutline });

export let iconPlaySkipForwardOutline = playSkipForwardOutline;
