
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playForwardCircleOutline } from "ionicons/icons";

addIcons({ playForwardCircleOutline });

export let iconPlayForwardCircleOutline = "playForwardCircleOutline";
