
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playForwardSharp } from "ionicons/icons";

addIcons({ playForwardSharp });

export let iconPlayForwardSharp = "playForwardSharp";
