
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playSkipForwardOutline } from "ionicons/icons";

addIcons({"play-skip-forward-outline": playSkipForwardOutline });

export let iconPlaySkipForwardOutline = "play-skip-forward-outline";
