
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { podiumSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ podiumSharp });

export default podiumSharp;
