
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { powerOutline } from "ionicons/icons";

addIcons({ powerOutline });

export let iconPowerOutline = "powerOutline";
