
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { powerSharp } from "ionicons/icons";

addIcons({"power-sharp": powerSharp });

export let iconPowerSharp = "power-sharp";
