
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pricetagSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ pricetagSharp });

export default pricetagSharp;
