
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pricetagsSharp } from "ionicons/icons";

addIcons({ pricetagsSharp });

export let iconPricetagsSharp = pricetagsSharp;
