
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pricetag } from "ionicons/icons";
import '../lib-icons'

addIcons({ pricetag });

export let iconPricetag = pricetag;
