
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pricetagSharp } from "ionicons/icons";

addIcons({"pricetag-sharp": pricetagSharp });

export let iconPricetagSharp = "pricetag-sharp";
