
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pricetagOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ pricetagOutline });

export default pricetagOutline;
