
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { printOutline } from "ionicons/icons";

addIcons({"print-outline": printOutline });

export let iconPrintOutline = "print-outline";
