
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { prismSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ prismSharp });

export let iconPrismSharp = prismSharp;
