
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { prismOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ prismOutline });

export default prismOutline;
