
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pulseSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ pulseSharp });

export let iconPulseSharp = pulseSharp;
