
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pulseSharp } from "ionicons/icons";

addIcons({"pulse-sharp": pulseSharp });

export let iconPulseSharp = "pulse-sharp";
