
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pulseOutline } from "ionicons/icons";

addIcons({"pulse-outline": pulseOutline });

export let iconPulseOutline = "pulse-outline";
