
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pushOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ pushOutline });

export let iconPushOutline = pushOutline;
