
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { qrCodeOutline } from "ionicons/icons";

addIcons({"qr-code-outline": qrCodeOutline });

export let iconQrCodeOutline = "qr-code-outline";
