
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { qrCodeSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ qrCodeSharp });

export let iconQrCodeSharp = qrCodeSharp;
