
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { qrCodeOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ qrCodeOutline });

export let iconQrCodeOutline = qrCodeOutline;
