
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { radioButtonOnSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ radioButtonOnSharp });

export default radioButtonOnSharp;
