
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { radioButtonOnSharp } from "ionicons/icons";

addIcons({ radioButtonOnSharp });

export let iconRadioButtonOnSharp = radioButtonOnSharp;
