
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { radioOutline } from "ionicons/icons";

addIcons({"radio-outline": radioOutline });

export let iconRadioOutline = "radio-outline";
