
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { radioButtonOn } from "ionicons/icons";

addIcons({ radioButtonOn });

export let iconRadioButtonOn = radioButtonOn;
