
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { radioButtonOffSharp } from "ionicons/icons";

addIcons({ radioButtonOffSharp });

export let iconRadioButtonOffSharp = "radioButtonOffSharp";
