
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { radioButtonOffOutline } from "ionicons/icons";

addIcons({"radio-button-off-outline": radioButtonOffOutline });

export let iconRadioButtonOffOutline = "radio-button-off-outline";
