
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { radioSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ radioSharp });

export default radioSharp;
