
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { radioOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ radioOutline });

export default radioOutline;
