
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { rainySharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ rainySharp });

export let iconRainySharp = rainySharp;
