
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { rainyOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ rainyOutline });

export default rainyOutline;
