
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { rainyOutline } from "ionicons/icons";

addIcons({"rainy-outline": rainyOutline });

export let iconRainyOutline = "rainy-outline";
