
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { rainyOutline } from "ionicons/icons";

addIcons({ rainyOutline });

export let iconRainyOutline = rainyOutline;
