
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { readerSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ readerSharp });

export default readerSharp;
