
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { readerSharp } from "ionicons/icons";

addIcons({"reader-sharp": readerSharp });

export let iconReaderSharp = "reader-sharp";
