
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { readerOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ readerOutline });

export default readerOutline;
