
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { receiptOutline } from "ionicons/icons";

addIcons({ receiptOutline });

export let iconReceiptOutline = "receiptOutline";
