
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { refreshCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ refreshCircleOutline });

export let iconRefreshCircleOutline = refreshCircleOutline;
