
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { refreshOutline } from "ionicons/icons";

addIcons({ refreshOutline });

export let iconRefreshOutline = refreshOutline;
