
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { refreshCircle } from "ionicons/icons";

addIcons({ refreshCircle });

export let iconRefreshCircle = "refreshCircle";
