
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { refreshOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ refreshOutline });

export default refreshOutline;
