
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { refreshCircle } from "ionicons/icons";

addIcons({"refresh-circle": refreshCircle });

export let iconRefreshCircle = "refresh-circle";
