
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { refreshCircle } from "ionicons/icons";
import '../lib-icons'

addIcons({ refreshCircle });

export default refreshCircle;
