
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { reloadCircleSharp } from "ionicons/icons";

addIcons({ reloadCircleSharp });

export let iconReloadCircleSharp = reloadCircleSharp;
