
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { reloadCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ reloadCircleSharp });

export default reloadCircleSharp;
