
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { reloadCircleOutline } from "ionicons/icons";

addIcons({ reloadCircleOutline });

export let iconReloadCircleOutline = "reloadCircleOutline";
