
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { reloadCircleOutline } from "ionicons/icons";

addIcons({"reload-circle-outline": reloadCircleOutline });

export let iconReloadCircleOutline = "reload-circle-outline";
