
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { removeCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ removeCircleSharp });

export default removeCircleSharp;
