
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { removeOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ removeOutline });

export let iconRemoveOutline = removeOutline;
