
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { reorderTwoSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ reorderTwoSharp });

export let iconReorderTwoSharp = reorderTwoSharp;
