
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { reorderThreeOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ reorderThreeOutline });

export default reorderThreeOutline;
