
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { reorderThreeOutline } from "ionicons/icons";

addIcons({"reorder-three-outline": reorderThreeOutline });

export let iconReorderThreeOutline = "reorder-three-outline";
