
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { reorderThreeSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ reorderThreeSharp });

export let iconReorderThreeSharp = reorderThreeSharp;
