
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { reorderTwoOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ reorderTwoOutline });

export default reorderTwoOutline;
