
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { reorderThree } from "ionicons/icons";
import '../lib-icons'

addIcons({ reorderThree });

export default reorderThree;
