
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { reorderTwoOutline } from "ionicons/icons";

addIcons({"reorder-two-outline": reorderTwoOutline });

export let iconReorderTwoOutline = "reorder-two-outline";
