
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { reorderThree } from "ionicons/icons";

addIcons({ reorderThree });

export let iconReorderThree = reorderThree;
