
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { repeatSharp } from "ionicons/icons";

addIcons({"repeat-sharp": repeatSharp });

export let iconRepeatSharp = "repeat-sharp";
