
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { repeatOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ repeatOutline });

export default repeatOutline;
