
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { resizeOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ resizeOutline });

export default resizeOutline;
