
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { resizeOutline } from "ionicons/icons";

addIcons({ resizeOutline });

export let iconResizeOutline = "resizeOutline";
