
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { restaurantSharp } from "ionicons/icons";

addIcons({ restaurantSharp });

export let iconRestaurantSharp = restaurantSharp;
