
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { restaurantOutline } from "ionicons/icons";

addIcons({"restaurant-outline": restaurantOutline });

export let iconRestaurantOutline = "restaurant-outline";
