
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnUpBack } from "ionicons/icons";
import '../lib-icons'

addIcons({ returnUpBack });

export default returnUpBack;
