
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnDownForwardSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ returnDownForwardSharp });

export default returnDownForwardSharp;
