
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnUpBack } from "ionicons/icons";

addIcons({ returnUpBack });

export let iconReturnUpBack = "returnUpBack";
