
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnUpForwardSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ returnUpForwardSharp });

export let iconReturnUpForwardSharp = returnUpForwardSharp;
