
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnDownBackOutline } from "ionicons/icons";

addIcons({"return-down-back-outline": returnDownBackOutline });

export let iconReturnDownBackOutline = "return-down-back-outline";
