
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnDownBackOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ returnDownBackOutline });

export default returnDownBackOutline;
