
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnDownForwardOutline } from "ionicons/icons";

addIcons({ returnDownForwardOutline });

export let iconReturnDownForwardOutline = "returnDownForwardOutline";
