
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnUpForwardOutline } from "ionicons/icons";

addIcons({ returnUpForwardOutline });

export let iconReturnUpForwardOutline = "returnUpForwardOutline";
