
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnDownForward } from "ionicons/icons";
import '../lib-icons'

addIcons({ returnDownForward });

export let iconReturnDownForward = returnDownForward;
