
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnUpBackSharp } from "ionicons/icons";

addIcons({ returnUpBackSharp });

export let iconReturnUpBackSharp = returnUpBackSharp;
