
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnUpBackOutline } from "ionicons/icons";

addIcons({ returnUpBackOutline });

export let iconReturnUpBackOutline = returnUpBackOutline;
