
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnDownBackSharp } from "ionicons/icons";

addIcons({ returnDownBackSharp });

export let iconReturnDownBackSharp = "returnDownBackSharp";
