
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnUpBack } from "ionicons/icons";

addIcons({"return-up-back": returnUpBack });

export let iconReturnUpBack = "return-up-back";
