
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnUpBackOutline } from "ionicons/icons";

addIcons({"return-up-back-outline": returnUpBackOutline });

export let iconReturnUpBackOutline = "return-up-back-outline";
