
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnUpForward } from "ionicons/icons";
import '../lib-icons'

addIcons({ returnUpForward });

export let iconReturnUpForward = returnUpForward;
