
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ribbonOutline } from "ionicons/icons";

addIcons({"ribbon-outline": ribbonOutline });

export let iconRibbonOutline = "ribbon-outline";
