
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { sadOutline } from "ionicons/icons";

addIcons({"sad-outline": sadOutline });

export let iconSadOutline = "sad-outline";
