
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { saveSharp } from "ionicons/icons";

addIcons({"save-sharp": saveSharp });

export let iconSaveSharp = "save-sharp";
