
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { saveOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ saveOutline });

export default saveOutline;
