
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { scaleOutline } from "ionicons/icons";

addIcons({"scale-outline": scaleOutline });

export let iconScaleOutline = "scale-outline";
