
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { scaleOutline } from "ionicons/icons";

addIcons({ scaleOutline });

export let iconScaleOutline = "scaleOutline";
