
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { scaleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ scaleOutline });

export default scaleOutline;
