
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { scanOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ scanOutline });

export let iconScanOutline = scanOutline;
