
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { scanCircle } from "ionicons/icons";

addIcons({"scan-circle": scanCircle });

export let iconScanCircle = "scan-circle";
