
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { scanSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ scanSharp });

export let iconScanSharp = scanSharp;
