
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { scanCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ scanCircleOutline });

export default scanCircleOutline;
