
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { schoolOutline } from "ionicons/icons";

addIcons({ schoolOutline });

export let iconSchoolOutline = "schoolOutline";
