
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { schoolOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ schoolOutline });

export default schoolOutline;
