
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { searchCircle } from "ionicons/icons";

addIcons({ searchCircle });

export let iconSearchCircle = searchCircle;
