
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { searchCircleOutline } from "ionicons/icons";

addIcons({ searchCircleOutline });

export let iconSearchCircleOutline = searchCircleOutline;
