
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { searchOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ searchOutline });

export let iconSearchOutline = searchOutline;
