
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { searchCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ searchCircleSharp });

export let iconSearchCircleSharp = searchCircleSharp;
