
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { searchSharp } from "ionicons/icons";

addIcons({"search-sharp": searchSharp });

export let iconSearchSharp = "search-sharp";
