
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shapesOutline } from "ionicons/icons";

addIcons({ shapesOutline });

export let iconShapesOutline = shapesOutline;
