
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shareSharp } from "ionicons/icons";

addIcons({"share-sharp": shareSharp });

export let iconShareSharp = "share-sharp";
