
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shareSocialSharp } from "ionicons/icons";

addIcons({"share-social-sharp": shareSocialSharp });

export let iconShareSocialSharp = "share-social-sharp";
