
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shareSocialSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ shareSocialSharp });

export default shareSocialSharp;
