
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shareSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ shareSharp });

export default shareSharp;
