
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shieldCheckmarkOutline } from "ionicons/icons";

addIcons({"shield-checkmark-outline": shieldCheckmarkOutline });

export let iconShieldCheckmarkOutline = "shield-checkmark-outline";
