
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shieldCheckmarkOutline } from "ionicons/icons";

addIcons({ shieldCheckmarkOutline });

export let iconShieldCheckmarkOutline = "shieldCheckmarkOutline";
