
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shieldCheckmarkOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ shieldCheckmarkOutline });

export default shieldCheckmarkOutline;
