
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shieldHalfSharp } from "ionicons/icons";

addIcons({ shieldHalfSharp });

export let iconShieldHalfSharp = "shieldHalfSharp";
