
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shieldHalf } from "ionicons/icons";
import '../lib-icons'

addIcons({ shieldHalf });

export let iconShieldHalf = shieldHalf;
