
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shieldHalfSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ shieldHalfSharp });

export default shieldHalfSharp;
