
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shieldCheckmark } from "ionicons/icons";

addIcons({"shield-checkmark": shieldCheckmark });

export let iconShieldCheckmark = "shield-checkmark";
