
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shieldCheckmark } from "ionicons/icons";

addIcons({ shieldCheckmark });

export let iconShieldCheckmark = shieldCheckmark;
