
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shieldCheckmarkSharp } from "ionicons/icons";

addIcons({"shield-checkmark-sharp": shieldCheckmarkSharp });

export let iconShieldCheckmarkSharp = "shield-checkmark-sharp";
