
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shieldHalfOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ shieldHalfOutline });

export let iconShieldHalfOutline = shieldHalfOutline;
