
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shirtSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ shirtSharp });

export default shirtSharp;
