
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shuffleOutline } from "ionicons/icons";

addIcons({"shuffle-outline": shuffleOutline });

export let iconShuffleOutline = "shuffle-outline";
