
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shuffleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ shuffleSharp });

export let iconShuffleSharp = shuffleSharp;
