
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shuffleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ shuffleOutline });

export default shuffleOutline;
