
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { skullSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ skullSharp });

export let iconSkullSharp = skullSharp;
