
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { skullOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ skullOutline });

export default skullOutline;
