
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { snowOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ snowOutline });

export let iconSnowOutline = snowOutline;
