
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { sparklesOutline } from "ionicons/icons";

addIcons({ sparklesOutline });

export let iconSparklesOutline = "sparklesOutline";
