
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { sparklesSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ sparklesSharp });

export default sparklesSharp;
