
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { speedometerSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ speedometerSharp });

export let iconSpeedometerSharp = speedometerSharp;
