
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { squareSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ squareSharp });

export default squareSharp;
