
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { squareOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ squareOutline });

export default squareOutline;
