
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { starOutline } from "ionicons/icons";

addIcons({"star-outline": starOutline });

export let iconStarOutline = "star-outline";
