
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { starHalfSharp } from "ionicons/icons";

addIcons({"star-half-sharp": starHalfSharp });

export let iconStarHalfSharp = "star-half-sharp";
