
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { starHalf } from "ionicons/icons";

addIcons({"star-half": starHalf });

export let iconStarHalf = "star-half";
