
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { starHalfOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ starHalfOutline });

export default starHalfOutline;
