
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { statsChartSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ statsChartSharp });

export let iconStatsChartSharp = statsChartSharp;
