
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { statsChartOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ statsChartOutline });

export let iconStatsChartOutline = statsChartOutline;
