
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { stopwatchOutline } from "ionicons/icons";

addIcons({ stopwatchOutline });

export let iconStopwatchOutline = stopwatchOutline;
