
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { stopCircleOutline } from "ionicons/icons";

addIcons({"stop-circle-outline": stopCircleOutline });

export let iconStopCircleOutline = "stop-circle-outline";
