
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { stopwatchSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ stopwatchSharp });

export default stopwatchSharp;
