
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { stopCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ stopCircleSharp });

export let iconStopCircleSharp = stopCircleSharp;
