
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { stopOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ stopOutline });

export let iconStopOutline = stopOutline;
