
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { storefrontOutline } from "ionicons/icons";

addIcons({"storefront-outline": storefrontOutline });

export let iconStorefrontOutline = "storefront-outline";
