
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { storefrontOutline } from "ionicons/icons";

addIcons({ storefrontOutline });

export let iconStorefrontOutline = "storefrontOutline";
