
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { subwayOutline } from "ionicons/icons";

addIcons({ subwayOutline });

export let iconSubwayOutline = "subwayOutline";
