
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { subwayOutline } from "ionicons/icons";

addIcons({"subway-outline": subwayOutline });

export let iconSubwayOutline = "subway-outline";
