
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { sunnyOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ sunnyOutline });

export default sunnyOutline;
