
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { sunnyOutline } from "ionicons/icons";

addIcons({"sunny-outline": sunnyOutline });

export let iconSunnyOutline = "sunny-outline";
