
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { swapHorizontal } from "ionicons/icons";

addIcons({ swapHorizontal });

export let iconSwapHorizontal = "swapHorizontal";
