
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { swapHorizontalOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ swapHorizontalOutline });

export let iconSwapHorizontalOutline = swapHorizontalOutline;
