
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { swapHorizontalSharp } from "ionicons/icons";

addIcons({"swap-horizontal-sharp": swapHorizontalSharp });

export let iconSwapHorizontalSharp = "swap-horizontal-sharp";
