
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { swapVerticalSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ swapVerticalSharp });

export default swapVerticalSharp;
