
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { swapVerticalOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ swapVerticalOutline });

export default swapVerticalOutline;
