
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { swapHorizontalSharp } from "ionicons/icons";

addIcons({ swapHorizontalSharp });

export let iconSwapHorizontalSharp = swapHorizontalSharp;
