
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { syncCircleOutline } from "ionicons/icons";

addIcons({ syncCircleOutline });

export let iconSyncCircleOutline = "syncCircleOutline";
