
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { syncCircleSharp } from "ionicons/icons";

addIcons({ syncCircleSharp });

export let iconSyncCircleSharp = "syncCircleSharp";
