
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { syncCircleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ syncCircleOutline });

export default syncCircleOutline;
