
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { syncCircle } from "ionicons/icons";
import '../lib-icons'

addIcons({ syncCircle });

export default syncCircle;
