
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { syncCircleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ syncCircleSharp });

export default syncCircleSharp;
