
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tabletLandscape } from "ionicons/icons";
import '../lib-icons'

addIcons({ tabletLandscape });

export default tabletLandscape;
