
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tabletPortrait } from "ionicons/icons";
import '../lib-icons'

addIcons({ tabletPortrait });

export default tabletPortrait;
