
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tabletLandscapeOutline } from "ionicons/icons";

addIcons({ tabletLandscapeOutline });

export let iconTabletLandscapeOutline = "tabletLandscapeOutline";
