
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tabletPortraitOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ tabletPortraitOutline });

export default tabletPortraitOutline;
