
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tabletLandscapeSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ tabletLandscapeSharp });

export let iconTabletLandscapeSharp = tabletLandscapeSharp;
