
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tabletLandscapeSharp } from "ionicons/icons";

addIcons({"tablet-landscape-sharp": tabletLandscapeSharp });

export let iconTabletLandscapeSharp = "tablet-landscape-sharp";
