
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tabletPortraitSharp } from "ionicons/icons";

addIcons({"tablet-portrait-sharp": tabletPortraitSharp });

export let iconTabletPortraitSharp = "tablet-portrait-sharp";
