
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tabletPortraitOutline } from "ionicons/icons";

addIcons({ tabletPortraitOutline });

export let iconTabletPortraitOutline = tabletPortraitOutline;
