
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tabletPortrait } from "ionicons/icons";

addIcons({ tabletPortrait });

export let iconTabletPortrait = tabletPortrait;
