
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tabletPortraitSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ tabletPortraitSharp });

export let iconTabletPortraitSharp = tabletPortraitSharp;
