
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { telescopeSharp } from "ionicons/icons";

addIcons({ telescopeSharp });

export let iconTelescopeSharp = "telescopeSharp";
