
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { telescopeOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ telescopeOutline });

export default telescopeOutline;
