
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { telescopeSharp } from "ionicons/icons";

addIcons({"telescope-sharp": telescopeSharp });

export let iconTelescopeSharp = "telescope-sharp";
