
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tennisballOutline } from "ionicons/icons";

addIcons({ tennisballOutline });

export let iconTennisballOutline = tennisballOutline;
