
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tennisballSharp } from "ionicons/icons";

addIcons({"tennisball-sharp": tennisballSharp });

export let iconTennisballSharp = "tennisball-sharp";
