
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tennisballSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ tennisballSharp });

export let iconTennisballSharp = tennisballSharp;
