
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { terminalSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ terminalSharp });

export default terminalSharp;
