
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { terminalOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ terminalOutline });

export let iconTerminalOutline = terminalOutline;
