
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { textOutline } from "ionicons/icons";

addIcons({"text-outline": textOutline });

export let iconTextOutline = "text-outline";
