
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { textOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ textOutline });

export let iconTextOutline = textOutline;
