
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thermometerSharp } from "ionicons/icons";

addIcons({ thermometerSharp });

export let iconThermometerSharp = thermometerSharp;
