
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thermometerOutline } from "ionicons/icons";

addIcons({ thermometerOutline });

export let iconThermometerOutline = thermometerOutline;
