
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thermometerOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ thermometerOutline });

export default thermometerOutline;
