
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thermometer } from "ionicons/icons";
import '../lib-icons'

addIcons({ thermometer });

export default thermometer;
