
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thumbsDownOutline } from "ionicons/icons";

addIcons({ thumbsDownOutline });

export let iconThumbsDownOutline = thumbsDownOutline;
