
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thumbsDownOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ thumbsDownOutline });

export default thumbsDownOutline;
