
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thumbsUp } from "ionicons/icons";
import '../lib-icons'

addIcons({ thumbsUp });

export let iconThumbsUp = thumbsUp;
