
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thumbsDownSharp } from "ionicons/icons";

addIcons({ thumbsDownSharp });

export let iconThumbsDownSharp = thumbsDownSharp;
