
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thumbsDownSharp } from "ionicons/icons";

addIcons({"thumbs-down-sharp": thumbsDownSharp });

export let iconThumbsDownSharp = "thumbs-down-sharp";
