
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thumbsUpOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ thumbsUpOutline });

export default thumbsUpOutline;
