
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thumbsUpSharp } from "ionicons/icons";

addIcons({ thumbsUpSharp });

export let iconThumbsUpSharp = "thumbsUpSharp";
