
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thunderstormSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ thunderstormSharp });

export default thunderstormSharp;
