
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thunderstormSharp } from "ionicons/icons";

addIcons({ thunderstormSharp });

export let iconThunderstormSharp = "thunderstormSharp";
