
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thunderstormOutline } from "ionicons/icons";

addIcons({"thunderstorm-outline": thunderstormOutline });

export let iconThunderstormOutline = "thunderstorm-outline";
