
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thunderstormSharp } from "ionicons/icons";

addIcons({"thunderstorm-sharp": thunderstormSharp });

export let iconThunderstormSharp = "thunderstorm-sharp";
