
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thunderstormOutline } from "ionicons/icons";

addIcons({ thunderstormOutline });

export let iconThunderstormOutline = thunderstormOutline;
