
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thunderstormOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ thunderstormOutline });

export default thunderstormOutline;
