
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { timerSharp } from "ionicons/icons";

addIcons({"timer-sharp": timerSharp });

export let iconTimerSharp = "timer-sharp";
