
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { timerOutline } from "ionicons/icons";

addIcons({ timerOutline });

export let iconTimerOutline = "timerOutline";
