
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { timeOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ timeOutline });

export let iconTimeOutline = timeOutline;
