
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { timerSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ timerSharp });

export let iconTimerSharp = timerSharp;
