
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { timeOutline } from "ionicons/icons";

addIcons({"time-outline": timeOutline });

export let iconTimeOutline = "time-outline";
