
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { todayOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ todayOutline });

export let iconTodayOutline = todayOutline;
