
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { toggleSharp } from "ionicons/icons";

addIcons({"toggle-sharp": toggleSharp });

export let iconToggleSharp = "toggle-sharp";
