
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { toggleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ toggleSharp });

export default toggleSharp;
