
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trailSign } from "ionicons/icons";
import '../lib-icons'

addIcons({ trailSign });

export let iconTrailSign = trailSign;
