
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trainSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ trainSharp });

export default trainSharp;
