
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trainOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ trainOutline });

export default trainOutline;
