
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trailSignSharp } from "ionicons/icons";

addIcons({ trailSignSharp });

export let iconTrailSignSharp = trailSignSharp;
