
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trailSignSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ trailSignSharp });

export default trailSignSharp;
