
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trailSignOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ trailSignOutline });

export default trailSignOutline;
