
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { transgender } from "ionicons/icons";

addIcons({"transgender": transgender });

export let iconTransgender = "transgender";
