
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { transgenderSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ transgenderSharp });

export let iconTransgenderSharp = transgenderSharp;
