
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trashSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ trashSharp });

export default trashSharp;
