
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trashOutline } from "ionicons/icons";

addIcons({ trashOutline });

export let iconTrashOutline = "trashOutline";
