
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trashBin } from "ionicons/icons";
import '../lib-icons'

addIcons({ trashBin });

export let iconTrashBin = trashBin;
