
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trashBinSharp } from "ionicons/icons";

addIcons({"trash-bin-sharp": trashBinSharp });

export let iconTrashBinSharp = "trash-bin-sharp";
