
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trashBinOutline } from "ionicons/icons";

addIcons({"trash-bin-outline": trashBinOutline });

export let iconTrashBinOutline = "trash-bin-outline";
