
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trashBinOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ trashBinOutline });

export let iconTrashBinOutline = trashBinOutline;
