
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trashBinSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ trashBinSharp });

export let iconTrashBinSharp = trashBinSharp;
