
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trendingUpSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ trendingUpSharp });

export default trendingUpSharp;
