
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trendingDownOutline } from "ionicons/icons";

addIcons({ trendingDownOutline });

export let iconTrendingDownOutline = trendingDownOutline;
