
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trendingDown } from "ionicons/icons";
import '../lib-icons'

addIcons({ trendingDown });

export default trendingDown;
