
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trendingDownSharp } from "ionicons/icons";

addIcons({ trendingDownSharp });

export let iconTrendingDownSharp = trendingDownSharp;
