
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trendingUpSharp } from "ionicons/icons";

addIcons({ trendingUpSharp });

export let iconTrendingUpSharp = trendingUpSharp;
