
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trendingUpOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ trendingUpOutline });

export let iconTrendingUpOutline = trendingUpOutline;
