
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trendingDownSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ trendingDownSharp });

export default trendingDownSharp;
