
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { triangleSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ triangleSharp });

export let iconTriangleSharp = triangleSharp;
