
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { triangle } from "ionicons/icons";
import '../lib-icons'

addIcons({ triangle });

export let iconTriangle = triangle;
