
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { triangleOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ triangleOutline });

export let iconTriangleOutline = triangleOutline;
