
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trophyOutline } from "ionicons/icons";

addIcons({ trophyOutline });

export let iconTrophyOutline = "trophyOutline";
