
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trophyOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ trophyOutline });

export default trophyOutline;
