
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { umbrellaOutline } from "ionicons/icons";

addIcons({"umbrella-outline": umbrellaOutline });

export let iconUmbrellaOutline = "umbrella-outline";
