
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { umbrellaSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ umbrellaSharp });

export default umbrellaSharp;
