
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { umbrella } from "ionicons/icons";
import '../lib-icons'

addIcons({ umbrella });

export let iconUmbrella = umbrella;
