
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { umbrellaOutline } from "ionicons/icons";

addIcons({ umbrellaOutline });

export let iconUmbrellaOutline = umbrellaOutline;
