
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { videocamOffSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ videocamOffSharp });

export default videocamOffSharp;
