
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { videocamSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ videocamSharp });

export let iconVideocamSharp = videocamSharp;
