
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { videocamOff } from "ionicons/icons";

addIcons({"videocam-off": videocamOff });

export let iconVideocamOff = "videocam-off";
