
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { videocamOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ videocamOutline });

export let iconVideocamOutline = videocamOutline;
