
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeHighOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ volumeHighOutline });

export let iconVolumeHighOutline = volumeHighOutline;
