
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeLowOutline } from "ionicons/icons";

addIcons({ volumeLowOutline });

export let iconVolumeLowOutline = "volumeLowOutline";
