
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeLowSharp } from "ionicons/icons";

addIcons({ volumeLowSharp });

export let iconVolumeLowSharp = "volumeLowSharp";
