
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeMuteOutline } from "ionicons/icons";

addIcons({ volumeMuteOutline });

export let iconVolumeMuteOutline = volumeMuteOutline;
