
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeLowOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ volumeLowOutline });

export let iconVolumeLowOutline = volumeLowOutline;
