
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeMediumSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ volumeMediumSharp });

export default volumeMediumSharp;
