
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeLow } from "ionicons/icons";

addIcons({"volume-low": volumeLow });

export let iconVolumeLow = "volume-low";
