
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeOffOutline } from "ionicons/icons";

addIcons({"volume-off-outline": volumeOffOutline });

export let iconVolumeOffOutline = "volume-off-outline";
