
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeMuteOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ volumeMuteOutline });

export default volumeMuteOutline;
