
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeHighSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ volumeHighSharp });

export default volumeHighSharp;
