
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeMediumOutline } from "ionicons/icons";

addIcons({"volume-medium-outline": volumeMediumOutline });

export let iconVolumeMediumOutline = "volume-medium-outline";
