
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeLowSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ volumeLowSharp });

export default volumeLowSharp;
