
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeLow } from "ionicons/icons";
import '../lib-icons'

addIcons({ volumeLow });

export let iconVolumeLow = volumeLow;
