
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeMediumOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ volumeMediumOutline });

export let iconVolumeMediumOutline = volumeMediumOutline;
