
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeOffOutline } from "ionicons/icons";

addIcons({ volumeOffOutline });

export let iconVolumeOffOutline = "volumeOffOutline";
