
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { walkOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ walkOutline });

export default walkOutline;
