
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { walkSharp } from "ionicons/icons";

addIcons({"walk-sharp": walkSharp });

export let iconWalkSharp = "walk-sharp";
