
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { walletOutline } from "ionicons/icons";

addIcons({ walletOutline });

export let iconWalletOutline = walletOutline;
