
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { walletSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ walletSharp });

export default walletSharp;
