
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { warningOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ warningOutline });

export let iconWarningOutline = warningOutline;
