
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { warningSharp } from "ionicons/icons";

addIcons({ warningSharp });

export let iconWarningSharp = "warningSharp";
