
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { wifiOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ wifiOutline });

export let iconWifiOutline = wifiOutline;
