
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { wineSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ wineSharp });

export let iconWineSharp = wineSharp;
