
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { wineSharp } from "ionicons/icons";

addIcons({"wine-sharp": wineSharp });

export let iconWineSharp = "wine-sharp";
