
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { wineOutline } from "ionicons/icons";

addIcons({"wine-outline": wineOutline });

export let iconWineOutline = "wine-outline";
