
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { womanOutline } from "ionicons/icons";

addIcons({ womanOutline });

export let iconWomanOutline = womanOutline;
