
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { womanSharp } from "ionicons/icons";
import '../lib-icons'

addIcons({ womanSharp });

export default womanSharp;
