
// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { womanOutline } from "ionicons/icons";
import '../lib-icons'

addIcons({ womanOutline });

export default womanOutline;
