// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { accessibility } from "ionicons/icons";

addIcons({"accessibility": accessibility });

export const iconAccessibility = "accessibility";
