// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { addCircleSharp } from "ionicons/icons";

addIcons({"add-circle-sharp": addCircleSharp });

export const iconAddCircleSharp = "add-circle-sharp";
