// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { airplaneSharp } from "ionicons/icons";

addIcons({"airplane-sharp": airplaneSharp });

export const iconAirplaneSharp = "airplane-sharp";
