// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { albumsOutline } from "ionicons/icons";

addIcons({"albums-outline": albumsOutline });

export const iconAlbumsOutline = "albums-outline";
