// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { alertOutline } from "ionicons/icons";

addIcons({"alert-outline": alertOutline });

export const iconAlertOutline = "alert-outline";
