// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { americanFootball } from "ionicons/icons";

addIcons({"american-football": americanFootball });

export const iconAmericanFootball = "american-football";
