// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { analyticsOutline } from "ionicons/icons";

addIcons({"analytics-outline": analyticsOutline });

export const iconAnalyticsOutline = "analytics-outline";
