// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { analytics } from "ionicons/icons";

addIcons({"analytics": analytics });

export const iconAnalytics = "analytics";
