// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpRightBoxOutline } from "ionicons/icons";

addIcons({"arrow-up-right-box-outline": arrowUpRightBoxOutline });

export const iconArrowUpRightBoxOutline = "arrow-up-right-box-outline";
