// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDownSharp } from "ionicons/icons";

addIcons({"arrow-down-sharp": arrowDownSharp });

export const iconArrowDownSharp = "arrow-down-sharp";
