// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpLeftBox } from "ionicons/icons";

addIcons({"arrow-up-left-box": arrowUpLeftBox });

export const iconArrowUpLeftBox = "arrow-up-left-box";
