// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpSharp } from "ionicons/icons";

addIcons({"arrow-up-sharp": arrowUpSharp });

export const iconArrowUpSharp = "arrow-up-sharp";
