// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowBackSharp } from "ionicons/icons";

addIcons({"arrow-back-sharp": arrowBackSharp });

export const iconArrowBackSharp = "arrow-back-sharp";
