// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowRedoSharp } from "ionicons/icons";

addIcons({"arrow-redo-sharp": arrowRedoSharp });

export const iconArrowRedoSharp = "arrow-redo-sharp";
