// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDownCircleSharp } from "ionicons/icons";

addIcons({"arrow-down-circle-sharp": arrowDownCircleSharp });

export const iconArrowDownCircleSharp = "arrow-down-circle-sharp";
