// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpCircleOutline } from "ionicons/icons";

addIcons({"arrow-up-circle-outline": arrowUpCircleOutline });

export const iconArrowUpCircleOutline = "arrow-up-circle-outline";
