// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpLeftBoxSharp } from "ionicons/icons";

addIcons({"arrow-up-left-box-sharp": arrowUpLeftBoxSharp });

export const iconArrowUpLeftBoxSharp = "arrow-up-left-box-sharp";
