// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpCircle } from "ionicons/icons";

addIcons({"arrow-up-circle": arrowUpCircle });

export const iconArrowUpCircle = "arrow-up-circle";
