// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowForwardCircle } from "ionicons/icons";

addIcons({"arrow-forward-circle": arrowForwardCircle });

export const iconArrowForwardCircle = "arrow-forward-circle";
