// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowUpLeftBoxOutline } from "ionicons/icons";

addIcons({"arrow-up-left-box-outline": arrowUpLeftBoxOutline });

export const iconArrowUpLeftBoxOutline = "arrow-up-left-box-outline";
