// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowRedoOutline } from "ionicons/icons";

addIcons({"arrow-redo-outline": arrowRedoOutline });

export const iconArrowRedoOutline = "arrow-redo-outline";
