// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowDownCircleOutline } from "ionicons/icons";

addIcons({"arrow-down-circle-outline": arrowDownCircleOutline });

export const iconArrowDownCircleOutline = "arrow-down-circle-outline";
