// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { arrowForwardOutline } from "ionicons/icons";

addIcons({"arrow-forward-outline": arrowForwardOutline });

export const iconArrowForwardOutline = "arrow-forward-outline";
