// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { attachOutline } from "ionicons/icons";

addIcons({"attach-outline": attachOutline });

export const iconAttachOutline = "attach-outline";
