// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { backspace } from "ionicons/icons";

addIcons({"backspace": backspace });

export const iconBackspace = "backspace";
