// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagRemoveOutline } from "ionicons/icons";

addIcons({"bag-remove-outline": bagRemoveOutline });

export const iconBagRemoveOutline = "bag-remove-outline";
