// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagRemoveSharp } from "ionicons/icons";

addIcons({"bag-remove-sharp": bagRemoveSharp });

export const iconBagRemoveSharp = "bag-remove-sharp";
