// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagCheck } from "ionicons/icons";

addIcons({"bag-check": bagCheck });

export const iconBagCheck = "bag-check";
