// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagAddSharp } from "ionicons/icons";

addIcons({"bag-add-sharp": bagAddSharp });

export const iconBagAddSharp = "bag-add-sharp";
