// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bagHandleOutline } from "ionicons/icons";

addIcons({"bag-handle-outline": bagHandleOutline });

export const iconBagHandleOutline = "bag-handle-outline";
