// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { balloonOutline } from "ionicons/icons";

addIcons({"balloon-outline": balloonOutline });

export const iconBalloonOutline = "balloon-outline";
