// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bandageSharp } from "ionicons/icons";

addIcons({"bandage-sharp": bandageSharp });

export const iconBandageSharp = "bandage-sharp";
