// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { barChart } from "ionicons/icons";

addIcons({"bar-chart": barChart });

export const iconBarChart = "bar-chart";
