// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { barbellSharp } from "ionicons/icons";

addIcons({"barbell-sharp": barbellSharp });

export const iconBarbellSharp = "barbell-sharp";
