// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { barcodeOutline } from "ionicons/icons";

addIcons({"barcode-outline": barcodeOutline });

export const iconBarcodeOutline = "barcode-outline";
