// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { baseballSharp } from "ionicons/icons";

addIcons({"baseball-sharp": baseballSharp });

export const iconBaseballSharp = "baseball-sharp";
