// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { basketballOutline } from "ionicons/icons";

addIcons({"basketball-outline": basketballOutline });

export const iconBasketballOutline = "basketball-outline";
