// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { batteryChargingSharp } from "ionicons/icons";

addIcons({"battery-charging-sharp": batteryChargingSharp });

export const iconBatteryChargingSharp = "battery-charging-sharp";
