// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { batteryHalfSharp } from "ionicons/icons";

addIcons({"battery-half-sharp": batteryHalfSharp });

export const iconBatteryHalfSharp = "battery-half-sharp";
