// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { batteryFullSharp } from "ionicons/icons";

addIcons({"battery-full-sharp": batteryFullSharp });

export const iconBatteryFullSharp = "battery-full-sharp";
