// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { batteryDeadSharp } from "ionicons/icons";

addIcons({"battery-dead-sharp": batteryDeadSharp });

export const iconBatteryDeadSharp = "battery-dead-sharp";
