// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bedSharp } from "ionicons/icons";

addIcons({"bed-sharp": bedSharp });

export const iconBedSharp = "bed-sharp";
