// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bedOutline } from "ionicons/icons";

addIcons({"bed-outline": bedOutline });

export const iconBedOutline = "bed-outline";
