// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bicycleOutline } from "ionicons/icons";

addIcons({"bicycle-outline": bicycleOutline });

export const iconBicycleOutline = "bicycle-outline";
