// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { binocularsOutline } from "ionicons/icons";

addIcons({"binoculars-outline": binocularsOutline });

export const iconBinocularsOutline = "binoculars-outline";
