// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { binocularsSharp } from "ionicons/icons";

addIcons({"binoculars-sharp": binocularsSharp });

export const iconBinocularsSharp = "binoculars-sharp";
