// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bluetoothSharp } from "ionicons/icons";

addIcons({"bluetooth-sharp": bluetoothSharp });

export const iconBluetoothSharp = "bluetooth-sharp";
