// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bluetooth } from "ionicons/icons";

addIcons({"bluetooth": bluetooth });

export const iconBluetooth = "bluetooth";
