// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { boatOutline } from "ionicons/icons";

addIcons({"boat-outline": boatOutline });

export const iconBoatOutline = "boat-outline";
