// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bodySharp } from "ionicons/icons";

addIcons({"body-sharp": bodySharp });

export const iconBodySharp = "body-sharp";
