// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bonfireOutline } from "ionicons/icons";

addIcons({"bonfire-outline": bonfireOutline });

export const iconBonfireOutline = "bonfire-outline";
