// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bookmarksOutline } from "ionicons/icons";

addIcons({"bookmarks-outline": bookmarksOutline });

export const iconBookmarksOutline = "bookmarks-outline";
