// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bookmarksSharp } from "ionicons/icons";

addIcons({"bookmarks-sharp": bookmarksSharp });

export const iconBookmarksSharp = "bookmarks-sharp";
