// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bowlingBallOutline } from "ionicons/icons";

addIcons({"bowling-ball-outline": bowlingBallOutline });

export const iconBowlingBallOutline = "bowling-ball-outline";
