// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { browsersSharp } from "ionicons/icons";

addIcons({"browsers-sharp": browsersSharp });

export const iconBrowsersSharp = "browsers-sharp";
