// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { brushOutline } from "ionicons/icons";

addIcons({"brush-outline": brushOutline });

export const iconBrushOutline = "brush-outline";
