// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bulbSharp } from "ionicons/icons";

addIcons({"bulb-sharp": bulbSharp });

export const iconBulbSharp = "bulb-sharp";
