// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { bulbOutline } from "ionicons/icons";

addIcons({"bulb-outline": bulbOutline });

export const iconBulbOutline = "bulb-outline";
