// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { calendarClearSharp } from "ionicons/icons";

addIcons({"calendar-clear-sharp": calendarClearSharp });

export const iconCalendarClearSharp = "calendar-clear-sharp";
