// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { calendarSharp } from "ionicons/icons";

addIcons({"calendar-sharp": calendarSharp });

export const iconCalendarSharp = "calendar-sharp";
