// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { callSharp } from "ionicons/icons";

addIcons({"call-sharp": callSharp });

export const iconCallSharp = "call-sharp";
