// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cameraReverseSharp } from "ionicons/icons";

addIcons({"camera-reverse-sharp": cameraReverseSharp });

export const iconCameraReverseSharp = "camera-reverse-sharp";
