// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cameraReverseOutline } from "ionicons/icons";

addIcons({"camera-reverse-outline": cameraReverseOutline });

export const iconCameraReverseOutline = "camera-reverse-outline";
