// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cameraSharp } from "ionicons/icons";

addIcons({"camera-sharp": cameraSharp });

export const iconCameraSharp = "camera-sharp";
