// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { carSharp } from "ionicons/icons";

addIcons({"car-sharp": carSharp });

export const iconCarSharp = "car-sharp";
