// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretUpOutline } from "ionicons/icons";

addIcons({"caret-up-outline": caretUpOutline });

export const iconCaretUpOutline = "caret-up-outline";
