// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretUpCircleOutline } from "ionicons/icons";

addIcons({"caret-up-circle-outline": caretUpCircleOutline });

export const iconCaretUpCircleOutline = "caret-up-circle-outline";
