// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretBack } from "ionicons/icons";

addIcons({"caret-back": caretBack });

export const iconCaretBack = "caret-back";
