// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { caretDown } from "ionicons/icons";

addIcons({"caret-down": caretDown });

export const iconCaretDown = "caret-down";
