// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatbubbleEllipsesSharp } from "ionicons/icons";

addIcons({"chatbubble-ellipses-sharp": chatbubbleEllipsesSharp });

export const iconChatbubbleEllipsesSharp = "chatbubble-ellipses-sharp";
