// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatboxSharp } from "ionicons/icons";

addIcons({"chatbox-sharp": chatboxSharp });

export const iconChatboxSharp = "chatbox-sharp";
