// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatboxEllipsesOutline } from "ionicons/icons";

addIcons({"chatbox-ellipses-outline": chatboxEllipsesOutline });

export const iconChatboxEllipsesOutline = "chatbox-ellipses-outline";
