// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatbubbleEllipses } from "ionicons/icons";

addIcons({"chatbubble-ellipses": chatbubbleEllipses });

export const iconChatbubbleEllipses = "chatbubble-ellipses";
