// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chatbubblesOutline } from "ionicons/icons";

addIcons({"chatbubbles-outline": chatbubblesOutline });

export const iconChatbubblesOutline = "chatbubbles-outline";
