// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkmarkSharp } from "ionicons/icons";

addIcons({"checkmark-sharp": checkmarkSharp });

export const iconCheckmarkSharp = "checkmark-sharp";
