// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { checkboxOutline } from "ionicons/icons";

addIcons({"checkbox-outline": checkboxOutline });

export const iconCheckboxOutline = "checkbox-outline";
