// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronDownCircleSharp } from "ionicons/icons";

addIcons({"chevron-down-circle-sharp": chevronDownCircleSharp });

export const iconChevronDownCircleSharp = "chevron-down-circle-sharp";
