// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronCollapseSharp } from "ionicons/icons";

addIcons({"chevron-collapse-sharp": chevronCollapseSharp });

export const iconChevronCollapseSharp = "chevron-collapse-sharp";
