// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronBackSharp } from "ionicons/icons";

addIcons({"chevron-back-sharp": chevronBackSharp });

export const iconChevronBackSharp = "chevron-back-sharp";
