// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronForwardCircleOutline } from "ionicons/icons";

addIcons({"chevron-forward-circle-outline": chevronForwardCircleOutline });

export const iconChevronForwardCircleOutline = "chevron-forward-circle-outline";
