// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronForwardSharp } from "ionicons/icons";

addIcons({"chevron-forward-sharp": chevronForwardSharp });

export const iconChevronForwardSharp = "chevron-forward-sharp";
