// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronDownOutline } from "ionicons/icons";

addIcons({"chevron-down-outline": chevronDownOutline });

export const iconChevronDownOutline = "chevron-down-outline";
