// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronDownCircleOutline } from "ionicons/icons";

addIcons({"chevron-down-circle-outline": chevronDownCircleOutline });

export const iconChevronDownCircleOutline = "chevron-down-circle-outline";
