// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronDown } from "ionicons/icons";

addIcons({"chevron-down": chevronDown });

export const iconChevronDown = "chevron-down";
