// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronCollapse } from "ionicons/icons";

addIcons({"chevron-collapse": chevronCollapse });

export const iconChevronCollapse = "chevron-collapse";
