// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { chevronForward } from "ionicons/icons";

addIcons({"chevron-forward": chevronForward });

export const iconChevronForward = "chevron-forward";
