// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { clipboard } from "ionicons/icons";

addIcons({"clipboard": clipboard });

export const iconClipboard = "clipboard";
