// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { closeCircleSharp } from "ionicons/icons";

addIcons({"close-circle-sharp": closeCircleSharp });

export const iconCloseCircleSharp = "close-circle-sharp";
