// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { closeSharp } from "ionicons/icons";

addIcons({"close-sharp": closeSharp });

export const iconCloseSharp = "close-sharp";
