// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudCircle } from "ionicons/icons";

addIcons({"cloud-circle": cloudCircle });

export const iconCloudCircle = "cloud-circle";
