// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudUpload } from "ionicons/icons";

addIcons({"cloud-upload": cloudUpload });

export const iconCloudUpload = "cloud-upload";
