// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudDownloadOutline } from "ionicons/icons";

addIcons({"cloud-download-outline": cloudDownloadOutline });

export const iconCloudDownloadOutline = "cloud-download-outline";
