// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudOfflineOutline } from "ionicons/icons";

addIcons({"cloud-offline-outline": cloudOfflineOutline });

export const iconCloudOfflineOutline = "cloud-offline-outline";
