// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudSharp } from "ionicons/icons";

addIcons({"cloud-sharp": cloudSharp });

export const iconCloudSharp = "cloud-sharp";
