// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cloudDoneSharp } from "ionicons/icons";

addIcons({"cloud-done-sharp": cloudDoneSharp });

export const iconCloudDoneSharp = "cloud-done-sharp";
