// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { codeWorkingSharp } from "ionicons/icons";

addIcons({"code-working-sharp": codeWorkingSharp });

export const iconCodeWorkingSharp = "code-working-sharp";
