// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { cogSharp } from "ionicons/icons";

addIcons({"cog-sharp": cogSharp });

export const iconCogSharp = "cog-sharp";
