// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { colorFilter } from "ionicons/icons";

addIcons({"color-filter": colorFilter });

export const iconColorFilter = "color-filter";
