// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { colorFilterSharp } from "ionicons/icons";

addIcons({"color-filter-sharp": colorFilterSharp });

export const iconColorFilterSharp = "color-filter-sharp";
