// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { colorFill } from "ionicons/icons";

addIcons({"color-fill": colorFill });

export const iconColorFill = "color-fill";
