// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { colorFillSharp } from "ionicons/icons";

addIcons({"color-fill-sharp": colorFillSharp });

export const iconColorFillSharp = "color-fill-sharp";
