// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { colorPaletteOutline } from "ionicons/icons";

addIcons({"color-palette-outline": colorPaletteOutline });

export const iconColorPaletteOutline = "color-palette-outline";
