// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { contractOutline } from "ionicons/icons";

addIcons({"contract-outline": contractOutline });

export const iconContractOutline = "contract-outline";
