// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { copyOutline } from "ionicons/icons";

addIcons({"copy-outline": copyOutline });

export const iconCopyOutline = "copy-outline";
