// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { createOutline } from "ionicons/icons";

addIcons({"create-outline": createOutline });

export const iconCreateOutline = "create-outline";
