// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { createSharp } from "ionicons/icons";

addIcons({"create-sharp": createSharp });

export const iconCreateSharp = "create-sharp";
