// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { diceOutline } from "ionicons/icons";

addIcons({"dice-outline": diceOutline });

export const iconDiceOutline = "dice-outline";
