// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentLockSharp } from "ionicons/icons";

addIcons({"document-lock-sharp": documentLockSharp });

export const iconDocumentLockSharp = "document-lock-sharp";
