// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentAttach } from "ionicons/icons";

addIcons({"document-attach": documentAttach });

export const iconDocumentAttach = "document-attach";
