// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentTextOutline } from "ionicons/icons";

addIcons({"document-text-outline": documentTextOutline });

export const iconDocumentTextOutline = "document-text-outline";
