// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentTextSharp } from "ionicons/icons";

addIcons({"document-text-sharp": documentTextSharp });

export const iconDocumentTextSharp = "document-text-sharp";
