// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { documentOutline } from "ionicons/icons";

addIcons({"document-outline": documentOutline });

export const iconDocumentOutline = "document-outline";
