// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { downloadSharp } from "ionicons/icons";

addIcons({"download-sharp": downloadSharp });

export const iconDownloadSharp = "download-sharp";
