// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { eggSharp } from "ionicons/icons";

addIcons({"egg-sharp": eggSharp });

export const iconEggSharp = "egg-sharp";
