// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisVerticalCircle } from "ionicons/icons";

addIcons({"ellipsis-vertical-circle": ellipsisVerticalCircle });

export const iconEllipsisVerticalCircle = "ellipsis-vertical-circle";
