// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisHorizontalCircleSharp } from "ionicons/icons";

addIcons({"ellipsis-horizontal-circle-sharp": ellipsisHorizontalCircleSharp });

export const iconEllipsisHorizontalCircleSharp = "ellipsis-horizontal-circle-sharp";
