// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisVerticalSharp } from "ionicons/icons";

addIcons({"ellipsis-vertical-sharp": ellipsisVerticalSharp });

export const iconEllipsisVerticalSharp = "ellipsis-vertical-sharp";
