// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisVerticalCircleOutline } from "ionicons/icons";

addIcons({"ellipsis-vertical-circle-outline": ellipsisVerticalCircleOutline });

export const iconEllipsisVerticalCircleOutline = "ellipsis-vertical-circle-outline";
