// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ellipsisHorizontalCircle } from "ionicons/icons";

addIcons({"ellipsis-horizontal-circle": ellipsisHorizontalCircle });

export const iconEllipsisHorizontalCircle = "ellipsis-horizontal-circle";
