// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { expandOutline } from "ionicons/icons";

addIcons({"expand-outline": expandOutline });

export const iconExpandOutline = "expand-outline";
