// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { extensionPuzzleOutline } from "ionicons/icons";

addIcons({"extension-puzzle-outline": extensionPuzzleOutline });

export const iconExtensionPuzzleOutline = "extension-puzzle-outline";
