// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { eyeOutline } from "ionicons/icons";

addIcons({"eye-outline": eyeOutline });

export const iconEyeOutline = "eye-outline";
