// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { eyeOffOutline } from "ionicons/icons";

addIcons({"eye-off-outline": eyeOffOutline });

export const iconEyeOffOutline = "eye-off-outline";
