// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { eyeOffSharp } from "ionicons/icons";

addIcons({"eye-off-sharp": eyeOffSharp });

export const iconEyeOffSharp = "eye-off-sharp";
