// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { eyedropSharp } from "ionicons/icons";

addIcons({"eyedrop-sharp": eyedropSharp });

export const iconEyedropSharp = "eyedrop-sharp";
