// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { eyedropOutline } from "ionicons/icons";

addIcons({"eyedrop-outline": eyedropOutline });

export const iconEyedropOutline = "eyedrop-outline";
