// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fastFoodOutline } from "ionicons/icons";

addIcons({"fast-food-outline": fastFoodOutline });

export const iconFastFoodOutline = "fast-food-outline";
