// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { femaleOutline } from "ionicons/icons";

addIcons({"female-outline": femaleOutline });

export const iconFemaleOutline = "female-outline";
