// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fileTray } from "ionicons/icons";

addIcons({"file-tray": fileTray });

export const iconFileTray = "file-tray";
