// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { fileTrayStackedOutline } from "ionicons/icons";

addIcons({"file-tray-stacked-outline": fileTrayStackedOutline });

export const iconFileTrayStackedOutline = "file-tray-stacked-outline";
