// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { filmSharp } from "ionicons/icons";

addIcons({"film-sharp": filmSharp });

export const iconFilmSharp = "film-sharp";
