// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { filterCircle } from "ionicons/icons";

addIcons({"filter-circle": filterCircle });

export const iconFilterCircle = "filter-circle";
