// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { filterCircleOutline } from "ionicons/icons";

addIcons({"filter-circle-outline": filterCircleOutline });

export const iconFilterCircleOutline = "filter-circle-outline";
