// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flagOutline } from "ionicons/icons";

addIcons({"flag-outline": flagOutline });

export const iconFlagOutline = "flag-outline";
