// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flameOutline } from "ionicons/icons";

addIcons({"flame-outline": flameOutline });

export const iconFlameOutline = "flame-outline";
