// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flashSharp } from "ionicons/icons";

addIcons({"flash-sharp": flashSharp });

export const iconFlashSharp = "flash-sharp";
