// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flashlight } from "ionicons/icons";

addIcons({"flashlight": flashlight });

export const iconFlashlight = "flashlight";
