// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { flashOutline } from "ionicons/icons";

addIcons({"flash-outline": flashOutline });

export const iconFlashOutline = "flash-outline";
