// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { footballOutline } from "ionicons/icons";

addIcons({"football-outline": footballOutline });

export const iconFootballOutline = "football-outline";
