// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { giftOutline } from "ionicons/icons";

addIcons({"gift-outline": giftOutline });

export const iconGiftOutline = "gift-outline";
