// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitNetwork } from "ionicons/icons";

addIcons({"git-network": gitNetwork });

export const iconGitNetwork = "git-network";
