// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitBranchSharp } from "ionicons/icons";

addIcons({"git-branch-sharp": gitBranchSharp });

export const iconGitBranchSharp = "git-branch-sharp";
