// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitCompare } from "ionicons/icons";

addIcons({"git-compare": gitCompare });

export const iconGitCompare = "git-compare";
