// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitNetworkSharp } from "ionicons/icons";

addIcons({"git-network-sharp": gitNetworkSharp });

export const iconGitNetworkSharp = "git-network-sharp";
