// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gitCommit } from "ionicons/icons";

addIcons({"git-commit": gitCommit });

export const iconGitCommit = "git-commit";
