// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { gridOutline } from "ionicons/icons";

addIcons({"grid-outline": gridOutline });

export const iconGridOutline = "grid-outline";
