// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { handLeftOutline } from "ionicons/icons";

addIcons({"hand-left-outline": handLeftOutline });

export const iconHandLeftOutline = "hand-left-outline";
