// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { handRight } from "ionicons/icons";

addIcons({"hand-right": handRight });

export const iconHandRight = "hand-right";
