// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { happyOutline } from "ionicons/icons";

addIcons({"happy-outline": happyOutline });

export const iconHappyOutline = "happy-outline";
