// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartCircleOutline } from "ionicons/icons";

addIcons({"heart-circle-outline": heartCircleOutline });

export const iconHeartCircleOutline = "heart-circle-outline";
