// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { heartHalfOutline } from "ionicons/icons";

addIcons({"heart-half-outline": heartHalfOutline });

export const iconHeartHalfOutline = "heart-half-outline";
