// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { helpBuoy } from "ionicons/icons";

addIcons({"help-buoy": helpBuoy });

export const iconHelpBuoy = "help-buoy";
