// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { helpOutline } from "ionicons/icons";

addIcons({"help-outline": helpOutline });

export const iconHelpOutline = "help-outline";
