// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { hourglassOutline } from "ionicons/icons";

addIcons({"hourglass-outline": hourglassOutline });

export const iconHourglassOutline = "hourglass-outline";
