// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { iceCreamOutline } from "ionicons/icons";

addIcons({"ice-cream-outline": iceCreamOutline });

export const iconIceCreamOutline = "ice-cream-outline";
