// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { imagesSharp } from "ionicons/icons";

addIcons({"images-sharp": imagesSharp });

export const iconImagesSharp = "images-sharp";
