// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { imageOutline } from "ionicons/icons";

addIcons({"image-outline": imageOutline });

export const iconImageOutline = "image-outline";
