// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { infiniteSharp } from "ionicons/icons";

addIcons({"infinite-sharp": infiniteSharp });

export const iconInfiniteSharp = "infinite-sharp";
