// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { information } from "ionicons/icons";

addIcons({"information": information });

export const iconInformation = "information";
