// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { informationCircleSharp } from "ionicons/icons";

addIcons({"information-circle-sharp": informationCircleSharp });

export const iconInformationCircleSharp = "information-circle-sharp";
