// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { invertMode } from "ionicons/icons";

addIcons({"invert-mode": invertMode });

export const iconInvertMode = "invert-mode";
