// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { journalOutline } from "ionicons/icons";

addIcons({"journal-outline": journalOutline });

export const iconJournalOutline = "journal-outline";
