// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { journalSharp } from "ionicons/icons";

addIcons({"journal-sharp": journalSharp });

export const iconJournalSharp = "journal-sharp";
