// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { keypadSharp } from "ionicons/icons";

addIcons({"keypad-sharp": keypadSharp });

export const iconKeypadSharp = "keypad-sharp";
