// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { laptopOutline } from "ionicons/icons";

addIcons({"laptop-outline": laptopOutline });

export const iconLaptopOutline = "laptop-outline";
