// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { leafSharp } from "ionicons/icons";

addIcons({"leaf-sharp": leafSharp });

export const iconLeafSharp = "leaf-sharp";
