// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { leafOutline } from "ionicons/icons";

addIcons({"leaf-outline": leafOutline });

export const iconLeafOutline = "leaf-outline";
