// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { librarySharp } from "ionicons/icons";

addIcons({"library-sharp": librarySharp });

export const iconLibrarySharp = "library-sharp";
