// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { listOutline } from "ionicons/icons";

addIcons({"list-outline": listOutline });

export const iconListOutline = "list-outline";
