// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { locateOutline } from "ionicons/icons";

addIcons({"locate-outline": locateOutline });

export const iconLocateOutline = "locate-outline";
