// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { locateSharp } from "ionicons/icons";

addIcons({"locate-sharp": locateSharp });

export const iconLocateSharp = "locate-sharp";
