// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { locationOutline } from "ionicons/icons";

addIcons({"location-outline": locationOutline });

export const iconLocationOutline = "location-outline";
