// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { lockOpenOutline } from "ionicons/icons";

addIcons({"lock-open-outline": lockOpenOutline });

export const iconLockOpenOutline = "lock-open-outline";
