// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoInstagram } from "ionicons/icons";

addIcons({"logo-instagram": logoInstagram });

export const iconLogoInstagram = "logo-instagram";
