// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoGooglePlaystore } from "ionicons/icons";

addIcons({"logo-google-playstore": logoGooglePlaystore });

export const iconLogoGooglePlaystore = "logo-google-playstore";
