// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoOctocat } from "ionicons/icons";

addIcons({"logo-octocat": logoOctocat });

export const iconLogoOctocat = "logo-octocat";
