// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoXbox } from "ionicons/icons";

addIcons({"logo-xbox": logoXbox });

export const iconLogoXbox = "logo-xbox";
