// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoBuffer } from "ionicons/icons";

addIcons({"logo-buffer": logoBuffer });

export const iconLogoBuffer = "logo-buffer";
