// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoEuro } from "ionicons/icons";

addIcons({"logo-euro": logoEuro });

export const iconLogoEuro = "logo-euro";
