// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoReddit } from "ionicons/icons";

addIcons({"logo-reddit": logoReddit });

export const iconLogoReddit = "logo-reddit";
