// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoClosedCaptioning } from "ionicons/icons";

addIcons({"logo-closed-captioning": logoClosedCaptioning });

export const iconLogoClosedCaptioning = "logo-closed-captioning";
