// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoIonic } from "ionicons/icons";

addIcons({"logo-ionic": logoIonic });

export const iconLogoIonic = "logo-ionic";
