// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoSteam } from "ionicons/icons";

addIcons({"logo-steam": logoSteam });

export const iconLogoSteam = "logo-steam";
