// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoXing } from "ionicons/icons";

addIcons({"logo-xing": logoXing });

export const iconLogoXing = "logo-xing";
