// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoBitbucket } from "ionicons/icons";

addIcons({"logo-bitbucket": logoBitbucket });

export const iconLogoBitbucket = "logo-bitbucket";
