// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoLaravel } from "ionicons/icons";

addIcons({"logo-laravel": logoLaravel });

export const iconLogoLaravel = "logo-laravel";
