// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoDribbble } from "ionicons/icons";

addIcons({"logo-dribbble": logoDribbble });

export const iconLogoDribbble = "logo-dribbble";
