// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoPaypal } from "ionicons/icons";

addIcons({"logo-paypal": logoPaypal });

export const iconLogoPaypal = "logo-paypal";
