// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoTrapeze } from "ionicons/icons";

addIcons({"logo-trapeze": logoTrapeze });

export const iconLogoTrapeze = "logo-trapeze";
