// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoFigma } from "ionicons/icons";

addIcons({"logo-figma": logoFigma });

export const iconLogoFigma = "logo-figma";
