// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoLinkedin } from "ionicons/icons";

addIcons({"logo-linkedin": logoLinkedin });

export const iconLogoLinkedin = "logo-linkedin";
