// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoDocker } from "ionicons/icons";

addIcons({"logo-docker": logoDocker });

export const iconLogoDocker = "logo-docker";
