// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoYoutube } from "ionicons/icons";

addIcons({"logo-youtube": logoYoutube });

export const iconLogoYoutube = "logo-youtube";
