// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoPlaystation } from "ionicons/icons";

addIcons({"logo-playstation": logoPlaystation });

export const iconLogoPlaystation = "logo-playstation";
