// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoJavascript } from "ionicons/icons";

addIcons({"logo-javascript": logoJavascript });

export const iconLogoJavascript = "logo-javascript";
