// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoAmplify } from "ionicons/icons";

addIcons({"logo-amplify": logoAmplify });

export const iconLogoAmplify = "logo-amplify";
