// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoCss3 } from "ionicons/icons";

addIcons({"logo-css3": logoCss3 });

export const iconLogoCss3 = "logo-css3";
