// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoCodepen } from "ionicons/icons";

addIcons({"logo-codepen": logoCodepen });

export const iconLogoCodepen = "logo-codepen";
