// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoApple } from "ionicons/icons";

addIcons({"logo-apple": logoApple });

export const iconLogoApple = "logo-apple";
