// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoSass } from "ionicons/icons";

addIcons({"logo-sass": logoSass });

export const iconLogoSass = "logo-sass";
