// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { logoSnapchat } from "ionicons/icons";

addIcons({"logo-snapchat": logoSnapchat });

export const iconLogoSnapchat = "logo-snapchat";
