// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { magnetSharp } from "ionicons/icons";

addIcons({"magnet-sharp": magnetSharp });

export const iconMagnetSharp = "magnet-sharp";
