// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { mailSharp } from "ionicons/icons";

addIcons({"mail-sharp": mailSharp });

export const iconMailSharp = "mail-sharp";
