// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { maleFemale } from "ionicons/icons";

addIcons({"male-female": maleFemale });

export const iconMaleFemale = "male-female";
