// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { maleFemaleOutline } from "ionicons/icons";

addIcons({"male-female-outline": maleFemaleOutline });

export const iconMaleFemaleOutline = "male-female-outline";
