// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { maleOutline } from "ionicons/icons";

addIcons({"male-outline": maleOutline });

export const iconMaleOutline = "male-outline";
