// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { manSharp } from "ionicons/icons";

addIcons({"man-sharp": manSharp });

export const iconManSharp = "man-sharp";
