// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { mapOutline } from "ionicons/icons";

addIcons({"map-outline": mapOutline });

export const iconMapOutline = "map-outline";
