// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { mapSharp } from "ionicons/icons";

addIcons({"map-sharp": mapSharp });

export const iconMapSharp = "map-sharp";
