// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { medkitSharp } from "ionicons/icons";

addIcons({"medkit-sharp": medkitSharp });

export const iconMedkitSharp = "medkit-sharp";
