// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { medkitOutline } from "ionicons/icons";

addIcons({"medkit-outline": medkitOutline });

export const iconMedkitOutline = "medkit-outline";
