// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { megaphoneSharp } from "ionicons/icons";

addIcons({"megaphone-sharp": megaphoneSharp });

export const iconMegaphoneSharp = "megaphone-sharp";
