// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { micOffCircleOutline } from "ionicons/icons";

addIcons({"mic-off-circle-outline": micOffCircleOutline });

export const iconMicOffCircleOutline = "mic-off-circle-outline";
