// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { micCircle } from "ionicons/icons";

addIcons({"mic-circle": micCircle });

export const iconMicCircle = "mic-circle";
