// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { micOffSharp } from "ionicons/icons";

addIcons({"mic-off-sharp": micOffSharp });

export const iconMicOffSharp = "mic-off-sharp";
