// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { micOffCircleSharp } from "ionicons/icons";

addIcons({"mic-off-circle-sharp": micOffCircleSharp });

export const iconMicOffCircleSharp = "mic-off-circle-sharp";
