// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { micOffCircle } from "ionicons/icons";

addIcons({"mic-off-circle": micOffCircle });

export const iconMicOffCircle = "mic-off-circle";
