// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { moonSharp } from "ionicons/icons";

addIcons({"moon-sharp": moonSharp });

export const iconMoonSharp = "moon-sharp";
