// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { moveOutline } from "ionicons/icons";

addIcons({"move-outline": moveOutline });

export const iconMoveOutline = "move-outline";
