// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { navigateCircle } from "ionicons/icons";

addIcons({"navigate-circle": navigateCircle });

export const iconNavigateCircle = "navigate-circle";
