// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { navigateOutline } from "ionicons/icons";

addIcons({"navigate-outline": navigateOutline });

export const iconNavigateOutline = "navigate-outline";
