// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsCircleSharp } from "ionicons/icons";

addIcons({"notifications-circle-sharp": notificationsCircleSharp });

export const iconNotificationsCircleSharp = "notifications-circle-sharp";
