// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { notificationsCircleOutline } from "ionicons/icons";

addIcons({"notifications-circle-outline": notificationsCircleOutline });

export const iconNotificationsCircleOutline = "notifications-circle-outline";
