// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { nutritionSharp } from "ionicons/icons";

addIcons({"nutrition-sharp": nutritionSharp });

export const iconNutritionSharp = "nutrition-sharp";
