// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { openSharp } from "ionicons/icons";

addIcons({"open-sharp": openSharp });

export const iconOpenSharp = "open-sharp";
