// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { optionsOutline } from "ionicons/icons";

addIcons({"options-outline": optionsOutline });

export const iconOptionsOutline = "options-outline";
