// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { paperPlaneSharp } from "ionicons/icons";

addIcons({"paper-plane-sharp": paperPlaneSharp });

export const iconPaperPlaneSharp = "paper-plane-sharp";
