// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { partlySunnyOutline } from "ionicons/icons";

addIcons({"partly-sunny-outline": partlySunnyOutline });

export const iconPartlySunnyOutline = "partly-sunny-outline";
