// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pauseCircleOutline } from "ionicons/icons";

addIcons({"pause-circle-outline": pauseCircleOutline });

export const iconPauseCircleOutline = "pause-circle-outline";
