// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pauseOutline } from "ionicons/icons";

addIcons({"pause-outline": pauseOutline });

export const iconPauseOutline = "pause-outline";
