// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pencilSharp } from "ionicons/icons";

addIcons({"pencil-sharp": pencilSharp });

export const iconPencilSharp = "pencil-sharp";
