// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { peopleOutline } from "ionicons/icons";

addIcons({"people-outline": peopleOutline });

export const iconPeopleOutline = "people-outline";
