// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { peopleCircleOutline } from "ionicons/icons";

addIcons({"people-circle-outline": peopleCircleOutline });

export const iconPeopleCircleOutline = "people-circle-outline";
