// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personAddSharp } from "ionicons/icons";

addIcons({"person-add-sharp": personAddSharp });

export const iconPersonAddSharp = "person-add-sharp";
