// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personRemoveOutline } from "ionicons/icons";

addIcons({"person-remove-outline": personRemoveOutline });

export const iconPersonRemoveOutline = "person-remove-outline";
