// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { personCircle } from "ionicons/icons";

addIcons({"person-circle": personCircle });

export const iconPersonCircle = "person-circle";
