// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { phoneLandscape } from "ionicons/icons";

addIcons({"phone-landscape": phoneLandscape });

export const iconPhoneLandscape = "phone-landscape";
