// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pieChart } from "ionicons/icons";

addIcons({"pie-chart": pieChart });

export const iconPieChart = "pie-chart";
