// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pieChartSharp } from "ionicons/icons";

addIcons({"pie-chart-sharp": pieChartSharp });

export const iconPieChartSharp = "pie-chart-sharp";
