// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pintOutline } from "ionicons/icons";

addIcons({"pint-outline": pintOutline });

export const iconPintOutline = "pint-outline";
