// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playCircleSharp } from "ionicons/icons";

addIcons({"play-circle-sharp": playCircleSharp });

export const iconPlayCircleSharp = "play-circle-sharp";
