// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playBackOutline } from "ionicons/icons";

addIcons({"play-back-outline": playBackOutline });

export const iconPlayBackOutline = "play-back-outline";
