// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playSharp } from "ionicons/icons";

addIcons({"play-sharp": playSharp });

export const iconPlaySharp = "play-sharp";
