// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playBackCircle } from "ionicons/icons";

addIcons({"play-back-circle": playBackCircle });

export const iconPlayBackCircle = "play-back-circle";
