// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playSkipBackSharp } from "ionicons/icons";

addIcons({"play-skip-back-sharp": playSkipBackSharp });

export const iconPlaySkipBackSharp = "play-skip-back-sharp";
