// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { playForwardCircleSharp } from "ionicons/icons";

addIcons({"play-forward-circle-sharp": playForwardCircleSharp });

export const iconPlayForwardCircleSharp = "play-forward-circle-sharp";
