// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { podiumSharp } from "ionicons/icons";

addIcons({"podium-sharp": podiumSharp });

export const iconPodiumSharp = "podium-sharp";
