// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pricetagOutline } from "ionicons/icons";

addIcons({"pricetag-outline": pricetagOutline });

export const iconPricetagOutline = "pricetag-outline";
