// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pricetagsSharp } from "ionicons/icons";

addIcons({"pricetags-sharp": pricetagsSharp });

export const iconPricetagsSharp = "pricetags-sharp";
