// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { prismOutline } from "ionicons/icons";

addIcons({"prism-outline": prismOutline });

export const iconPrismOutline = "prism-outline";
