// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { pushOutline } from "ionicons/icons";

addIcons({"push-outline": pushOutline });

export const iconPushOutline = "push-outline";
