// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { qrCodeSharp } from "ionicons/icons";

addIcons({"qr-code-sharp": qrCodeSharp });

export const iconQrCodeSharp = "qr-code-sharp";
