// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { radioButtonOffOutline } from "ionicons/icons";

addIcons({"radio-button-off-outline": radioButtonOffOutline });

export const iconRadioButtonOffOutline = "radio-button-off-outline";
