// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { radioButtonOnSharp } from "ionicons/icons";

addIcons({"radio-button-on-sharp": radioButtonOnSharp });

export const iconRadioButtonOnSharp = "radio-button-on-sharp";
