// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { radioButtonOffSharp } from "ionicons/icons";

addIcons({"radio-button-off-sharp": radioButtonOffSharp });

export const iconRadioButtonOffSharp = "radio-button-off-sharp";
