// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { receiptOutline } from "ionicons/icons";

addIcons({"receipt-outline": receiptOutline });

export const iconReceiptOutline = "receipt-outline";
