// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { receiptSharp } from "ionicons/icons";

addIcons({"receipt-sharp": receiptSharp });

export const iconReceiptSharp = "receipt-sharp";
