// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { recordingSharp } from "ionicons/icons";

addIcons({"recording-sharp": recordingSharp });

export const iconRecordingSharp = "recording-sharp";
