// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { refreshOutline } from "ionicons/icons";

addIcons({"refresh-outline": refreshOutline });

export const iconRefreshOutline = "refresh-outline";
