// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { refreshCircleOutline } from "ionicons/icons";

addIcons({"refresh-circle-outline": refreshCircleOutline });

export const iconRefreshCircleOutline = "refresh-circle-outline";
