// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { reloadCircle } from "ionicons/icons";

addIcons({"reload-circle": reloadCircle });

export const iconReloadCircle = "reload-circle";
