// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { reloadCircleSharp } from "ionicons/icons";

addIcons({"reload-circle-sharp": reloadCircleSharp });

export const iconReloadCircleSharp = "reload-circle-sharp";
