// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { removeCircleSharp } from "ionicons/icons";

addIcons({"remove-circle-sharp": removeCircleSharp });

export const iconRemoveCircleSharp = "remove-circle-sharp";
