// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { reorderThreeSharp } from "ionicons/icons";

addIcons({"reorder-three-sharp": reorderThreeSharp });

export const iconReorderThreeSharp = "reorder-three-sharp";
