// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { reorderThree } from "ionicons/icons";

addIcons({"reorder-three": reorderThree });

export const iconReorderThree = "reorder-three";
