// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { resizeSharp } from "ionicons/icons";

addIcons({"resize-sharp": resizeSharp });

export const iconResizeSharp = "resize-sharp";
