// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { restaurantSharp } from "ionicons/icons";

addIcons({"restaurant-sharp": restaurantSharp });

export const iconRestaurantSharp = "restaurant-sharp";
