// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { restaurant } from "ionicons/icons";

addIcons({"restaurant": restaurant });

export const iconRestaurant = "restaurant";
