// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnDownForwardOutline } from "ionicons/icons";

addIcons({"return-down-forward-outline": returnDownForwardOutline });

export const iconReturnDownForwardOutline = "return-down-forward-outline";
