// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnDownBack } from "ionicons/icons";

addIcons({"return-down-back": returnDownBack });

export const iconReturnDownBack = "return-down-back";
