// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnDownBackSharp } from "ionicons/icons";

addIcons({"return-down-back-sharp": returnDownBackSharp });

export const iconReturnDownBackSharp = "return-down-back-sharp";
