// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnDownForward } from "ionicons/icons";

addIcons({"return-down-forward": returnDownForward });

export const iconReturnDownForward = "return-down-forward";
