// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnUpForwardSharp } from "ionicons/icons";

addIcons({"return-up-forward-sharp": returnUpForwardSharp });

export const iconReturnUpForwardSharp = "return-up-forward-sharp";
