// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { returnDownForwardSharp } from "ionicons/icons";

addIcons({"return-down-forward-sharp": returnDownForwardSharp });

export const iconReturnDownForwardSharp = "return-down-forward-sharp";
