// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { ribbonSharp } from "ionicons/icons";

addIcons({"ribbon-sharp": ribbonSharp });

export const iconRibbonSharp = "ribbon-sharp";
