// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { rocketOutline } from "ionicons/icons";

addIcons({"rocket-outline": rocketOutline });

export const iconRocketOutline = "rocket-outline";
