// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { rocketSharp } from "ionicons/icons";

addIcons({"rocket-sharp": rocketSharp });

export const iconRocketSharp = "rocket-sharp";
