// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { roseOutline } from "ionicons/icons";

addIcons({"rose-outline": roseOutline });

export const iconRoseOutline = "rose-outline";
