// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { saveOutline } from "ionicons/icons";

addIcons({"save-outline": saveOutline });

export const iconSaveOutline = "save-outline";
