// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { scanOutline } from "ionicons/icons";

addIcons({"scan-outline": scanOutline });

export const iconScanOutline = "scan-outline";
