// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { schoolOutline } from "ionicons/icons";

addIcons({"school-outline": schoolOutline });

export const iconSchoolOutline = "school-outline";
