// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { searchOutline } from "ionicons/icons";

addIcons({"search-outline": searchOutline });

export const iconSearchOutline = "search-outline";
