// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { searchCircleSharp } from "ionicons/icons";

addIcons({"search-circle-sharp": searchCircleSharp });

export const iconSearchCircleSharp = "search-circle-sharp";
