// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { searchCircleOutline } from "ionicons/icons";

addIcons({"search-circle-outline": searchCircleOutline });

export const iconSearchCircleOutline = "search-circle-outline";
