// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { settingsOutline } from "ionicons/icons";

addIcons({"settings-outline": settingsOutline });

export const iconSettingsOutline = "settings-outline";
