// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shapesOutline } from "ionicons/icons";

addIcons({"shapes-outline": shapesOutline });

export const iconShapesOutline = "shapes-outline";
