// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shieldOutline } from "ionicons/icons";

addIcons({"shield-outline": shieldOutline });

export const iconShieldOutline = "shield-outline";
