// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shieldHalf } from "ionicons/icons";

addIcons({"shield-half": shieldHalf });

export const iconShieldHalf = "shield-half";
