// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shieldHalfOutline } from "ionicons/icons";

addIcons({"shield-half-outline": shieldHalfOutline });

export const iconShieldHalfOutline = "shield-half-outline";
