// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { shuffleSharp } from "ionicons/icons";

addIcons({"shuffle-sharp": shuffleSharp });

export const iconShuffleSharp = "shuffle-sharp";
