// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { sparklesSharp } from "ionicons/icons";

addIcons({"sparkles-sharp": sparklesSharp });

export const iconSparklesSharp = "sparkles-sharp";
