// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { speedometerOutline } from "ionicons/icons";

addIcons({"speedometer-outline": speedometerOutline });

export const iconSpeedometerOutline = "speedometer-outline";
