// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { squareOutline } from "ionicons/icons";

addIcons({"square-outline": squareOutline });

export const iconSquareOutline = "square-outline";
