// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { squareSharp } from "ionicons/icons";

addIcons({"square-sharp": squareSharp });

export const iconSquareSharp = "square-sharp";
