// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { statsChartSharp } from "ionicons/icons";

addIcons({"stats-chart-sharp": statsChartSharp });

export const iconStatsChartSharp = "stats-chart-sharp";
