// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { statsChartOutline } from "ionicons/icons";

addIcons({"stats-chart-outline": statsChartOutline });

export const iconStatsChartOutline = "stats-chart-outline";
