// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { stopCircleSharp } from "ionicons/icons";

addIcons({"stop-circle-sharp": stopCircleSharp });

export const iconStopCircleSharp = "stop-circle-sharp";
