// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { stopSharp } from "ionicons/icons";

addIcons({"stop-sharp": stopSharp });

export const iconStopSharp = "stop-sharp";
