// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { stopCircle } from "ionicons/icons";

addIcons({"stop-circle": stopCircle });

export const iconStopCircle = "stop-circle";
