// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { stopOutline } from "ionicons/icons";

addIcons({"stop-outline": stopOutline });

export const iconStopOutline = "stop-outline";
