// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { stopwatch } from "ionicons/icons";

addIcons({"stopwatch": stopwatch });

export const iconStopwatch = "stopwatch";
