// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { storefront } from "ionicons/icons";

addIcons({"storefront": storefront });

export const iconStorefront = "storefront";
