// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { subwaySharp } from "ionicons/icons";

addIcons({"subway-sharp": subwaySharp });

export const iconSubwaySharp = "subway-sharp";
