// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { swapVerticalSharp } from "ionicons/icons";

addIcons({"swap-vertical-sharp": swapVerticalSharp });

export const iconSwapVerticalSharp = "swap-vertical-sharp";
