// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { swapVerticalOutline } from "ionicons/icons";

addIcons({"swap-vertical-outline": swapVerticalOutline });

export const iconSwapVerticalOutline = "swap-vertical-outline";
