// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { syncCircleOutline } from "ionicons/icons";

addIcons({"sync-circle-outline": syncCircleOutline });

export const iconSyncCircleOutline = "sync-circle-outline";
