// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tabletLandscape } from "ionicons/icons";

addIcons({"tablet-landscape": tabletLandscape });

export const iconTabletLandscape = "tablet-landscape";
