// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tabletPortrait } from "ionicons/icons";

addIcons({"tablet-portrait": tabletPortrait });

export const iconTabletPortrait = "tablet-portrait";
