// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { telescope } from "ionicons/icons";

addIcons({"telescope": telescope });

export const iconTelescope = "telescope";
