// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { telescopeOutline } from "ionicons/icons";

addIcons({"telescope-outline": telescopeOutline });

export const iconTelescopeOutline = "telescope-outline";
