// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tennisball } from "ionicons/icons";

addIcons({"tennisball": tennisball });

export const iconTennisball = "tennisball";
