// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thumbsUp } from "ionicons/icons";

addIcons({"thumbs-up": thumbsUp });

export const iconThumbsUp = "thumbs-up";
