// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thumbsDown } from "ionicons/icons";

addIcons({"thumbs-down": thumbsDown });

export const iconThumbsDown = "thumbs-down";
