// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { thunderstorm } from "ionicons/icons";

addIcons({"thunderstorm": thunderstorm });

export const iconThunderstorm = "thunderstorm";
