// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { todayOutline } from "ionicons/icons";

addIcons({"today-outline": todayOutline });

export const iconTodayOutline = "today-outline";
