// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { todaySharp } from "ionicons/icons";

addIcons({"today-sharp": todaySharp });

export const iconTodaySharp = "today-sharp";
