// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trailSign } from "ionicons/icons";

addIcons({"trail-sign": trailSign });

export const iconTrailSign = "trail-sign";
