// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trailSignSharp } from "ionicons/icons";

addIcons({"trail-sign-sharp": trailSignSharp });

export const iconTrailSignSharp = "trail-sign-sharp";
