// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { transgenderSharp } from "ionicons/icons";

addIcons({"transgender-sharp": transgenderSharp });

export const iconTransgenderSharp = "transgender-sharp";
