// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trendingDownSharp } from "ionicons/icons";

addIcons({"trending-down-sharp": trendingDownSharp });

export const iconTrendingDownSharp = "trending-down-sharp";
