// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trendingUpSharp } from "ionicons/icons";

addIcons({"trending-up-sharp": trendingUpSharp });

export const iconTrendingUpSharp = "trending-up-sharp";
