// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trendingDownOutline } from "ionicons/icons";

addIcons({"trending-down-outline": trendingDownOutline });

export const iconTrendingDownOutline = "trending-down-outline";
