// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { triangleSharp } from "ionicons/icons";

addIcons({"triangle-sharp": triangleSharp });

export const iconTriangleSharp = "triangle-sharp";
