// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { trophyOutline } from "ionicons/icons";

addIcons({"trophy-outline": trophyOutline });

export const iconTrophyOutline = "trophy-outline";
