// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { tvOutline } from "ionicons/icons";

addIcons({"tv-outline": tvOutline });

export const iconTvOutline = "tv-outline";
