// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { umbrellaSharp } from "ionicons/icons";

addIcons({"umbrella-sharp": umbrellaSharp });

export const iconUmbrellaSharp = "umbrella-sharp";
