// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { videocamOutline } from "ionicons/icons";

addIcons({"videocam-outline": videocamOutline });

export const iconVideocamOutline = "videocam-outline";
