// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { videocamOffSharp } from "ionicons/icons";

addIcons({"videocam-off-sharp": videocamOffSharp });

export const iconVideocamOffSharp = "videocam-off-sharp";
