// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { videocamOffOutline } from "ionicons/icons";

addIcons({"videocam-off-outline": videocamOffOutline });

export const iconVideocamOffOutline = "videocam-off-outline";
