// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeMute } from "ionicons/icons";

addIcons({"volume-mute": volumeMute });

export const iconVolumeMute = "volume-mute";
