// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeLowOutline } from "ionicons/icons";

addIcons({"volume-low-outline": volumeLowOutline });

export const iconVolumeLowOutline = "volume-low-outline";
