// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeMuteOutline } from "ionicons/icons";

addIcons({"volume-mute-outline": volumeMuteOutline });

export const iconVolumeMuteOutline = "volume-mute-outline";
