// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeHigh } from "ionicons/icons";

addIcons({"volume-high": volumeHigh });

export const iconVolumeHigh = "volume-high";
