// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { volumeHighSharp } from "ionicons/icons";

addIcons({"volume-high-sharp": volumeHighSharp });

export const iconVolumeHighSharp = "volume-high-sharp";
