// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { walletSharp } from "ionicons/icons";

addIcons({"wallet-sharp": walletSharp });

export const iconWalletSharp = "wallet-sharp";
