// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { walletOutline } from "ionicons/icons";

addIcons({"wallet-outline": walletOutline });

export const iconWalletOutline = "wallet-outline";
