// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { warningSharp } from "ionicons/icons";

addIcons({"warning-sharp": warningSharp });

export const iconWarningSharp = "warning-sharp";
