// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { watchSharp } from "ionicons/icons";

addIcons({"watch-sharp": watchSharp });

export const iconWatchSharp = "watch-sharp";
