// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { wifiOutline } from "ionicons/icons";

addIcons({"wifi-outline": wifiOutline });

export const iconWifiOutline = "wifi-outline";
