// Auto-generated by scripts/generate.ts

import { addIcons } from "ionicons";
import { womanOutline } from "ionicons/icons";

addIcons({"woman-outline": womanOutline });

export const iconWomanOutline = "woman-outline";
