
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-nav'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonProps } from '../lib'

initialize()
defineCustomElement()

export type IonNavProps = FixIonProps<IonicJSX.IonNav> &
  JSXBase.HTMLAttributes<HTMLIonNavElement>

export function IonNav(props: IonNavProps) {
  //@ts-ignore
  return <ion-nav {...props} />
}
