
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-split-pane'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonEventCasing } from '../lib'

initialize()
defineCustomElement()

export type IonSplitPaneProps = FixIonEventCasing<IonicJSX.IonSplitPane> &
  JSXBase.HTMLAttributes<HTMLIonSplitPaneElement>

export function IonSplitPane(props: IonSplitPaneProps) {
  //@ts-ignore
  return <ion-split-pane {...props} />
}
