
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-grid'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonProps } from '../lib'

initialize()
defineCustomElement()

export type IonGridProps = FixIonProps<IonicJSX.IonGrid> &
  JSXBase.HTMLAttributes<HTMLIonGridElement>

export function IonGrid(props: IonGridProps) {
  //@ts-ignore
  return <ion-grid {...props} />
}
