
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-menu-toggle'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonProps } from '../lib'

initialize()
defineCustomElement()

export type IonMenuToggleProps = FixIonProps<IonicJSX.IonMenuToggle> &
  JSXBase.HTMLAttributes<HTMLIonMenuToggleElement>

export function IonMenuToggle(props: IonMenuToggleProps) {
  //@ts-ignore
  return <ion-menu-toggle {...props} />
}
