
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-item-group'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonEventCasing } from '../lib'

initialize()
defineCustomElement()

export type IonItemGroupProps = FixIonEventCasing<IonicJSX.IonItemGroup> &
  JSXBase.HTMLAttributes<HTMLIonItemGroupElement>

export function IonItemGroup(props: IonItemGroupProps) {
  //@ts-ignore
  return <ion-item-group {...props} />
}
