
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-card-header'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonProps } from '../lib'

initialize()
defineCustomElement()

export type IonCardHeaderProps = FixIonProps<IonicJSX.IonCardHeader> &
  JSXBase.HTMLAttributes<HTMLIonCardHeaderElement>

export function IonCardHeader(props: IonCardHeaderProps) {
  //@ts-ignore
  return <ion-card-header {...props} />
}
