
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-refresher'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonProps } from '../lib'

initialize()
defineCustomElement()

export type IonRefresherProps = FixIonProps<IonicJSX.IonRefresher> &
  JSXBase.HTMLAttributes<HTMLIonRefresherElement>

export function IonRefresher(props: IonRefresherProps) {
  //@ts-ignore
  return <ion-refresher {...props} />
}
