
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-searchbar'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonProps } from '../lib'

initialize()
defineCustomElement()

export type IonSearchbarProps = FixIonProps<IonicJSX.IonSearchbar> &
  JSXBase.HTMLAttributes<HTMLIonSearchbarElement>

export function IonSearchbar(props: IonSearchbarProps) {
  //@ts-ignore
  return <ion-searchbar {...props} />
}
