
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-label'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonProps } from '../lib'

initialize()
defineCustomElement()

export type IonLabelProps = FixIonProps<IonicJSX.IonLabel> &
  JSXBase.HTMLAttributes<HTMLIonLabelElement>

export function IonLabel(props: IonLabelProps) {
  //@ts-ignore
  return <ion-label {...props} />
}
