
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-select-popover'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonEventCasing } from '../lib'

initialize()
defineCustomElement()

export type IonSelectPopoverProps = FixIonEventCasing<IonicJSX.IonSelectPopover> &
  JSXBase.HTMLAttributes<HTMLIonSelectPopoverElement>

export function IonSelectPopover(props: IonSelectPopoverProps) {
  //@ts-ignore
  return <ion-select-popover {...props} />
}
