
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-radio-group'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonEventCasing } from '../lib'

initialize()
defineCustomElement()

export type IonRadioGroupProps = FixIonEventCasing<IonicJSX.IonRadioGroup> &
  JSXBase.HTMLAttributes<HTMLIonRadioGroupElement>

export function IonRadioGroup(props: IonRadioGroupProps) {
  //@ts-ignore
  return <ion-radio-group {...props} />
}
