
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-infinite-scroll'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonEventCasing } from '../lib'

initialize()
defineCustomElement()

export type IonInfiniteScrollProps = FixIonEventCasing<IonicJSX.IonInfiniteScroll> &
  JSXBase.HTMLAttributes<HTMLIonInfiniteScrollElement>

export function IonInfiniteScroll(props: IonInfiniteScrollProps) {
  //@ts-ignore
  return <ion-infinite-scroll {...props} />
}
