
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-title'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonProps } from '../lib'

initialize()
defineCustomElement()

export type IonTitleProps = FixIonProps<IonicJSX.IonTitle> &
  JSXBase.HTMLAttributes<HTMLIonTitleElement>

export function IonTitle(props: IonTitleProps) {
  //@ts-ignore
  return <ion-title {...props} />
}
