
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-progress-bar'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonEventCasing } from '../lib'

initialize()
defineCustomElement()

export type IonProgressBarProps = FixIonEventCasing<IonicJSX.IonProgressBar> &
  JSXBase.HTMLAttributes<HTMLIonProgressBarElement>

export function IonProgressBar(props: IonProgressBarProps) {
  //@ts-ignore
  return <ion-progress-bar {...props} />
}
