
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-fab-button'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonProps } from '../lib'

initialize()
defineCustomElement()

export type IonFabButtonProps = FixIonProps<IonicJSX.IonFabButton> &
  JSXBase.HTMLAttributes<HTMLIonFabButtonElement>

export function IonFabButton(props: IonFabButtonProps) {
  //@ts-ignore
  return <ion-fab-button {...props} />
}
