
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-content'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonProps } from '../lib'

initialize()
defineCustomElement()

export type IonContentProps = FixIonProps<IonicJSX.IonContent> &
  JSXBase.HTMLAttributes<HTMLIonContentElement>

export function IonContent(props: IonContentProps) {
  //@ts-ignore
  return <ion-content {...props} />
}
