
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-footer'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonProps } from '../lib'

initialize()
defineCustomElement()

export type IonFooterProps = FixIonProps<IonicJSX.IonFooter> &
  JSXBase.HTMLAttributes<HTMLIonFooterElement>

export function IonFooter(props: IonFooterProps) {
  //@ts-ignore
  return <ion-footer {...props} />
}
