
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-note'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonEventCasing } from '../lib'

initialize()
defineCustomElement()

export type IonNoteProps = FixIonEventCasing<IonicJSX.IonNote> &
  JSXBase.HTMLAttributes<HTMLIonNoteElement>

export function IonNote(props: IonNoteProps) {
  //@ts-ignore
  return <ion-note {...props} />
}
