
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-nav-link'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonEventCasing } from '../lib'

initialize()
defineCustomElement()

export type IonNavLinkProps = FixIonEventCasing<IonicJSX.IonNavLink> &
  JSXBase.HTMLAttributes<HTMLIonNavLinkElement>

export function IonNavLink(props: IonNavLinkProps) {
  //@ts-ignore
  return <ion-nav-link {...props} />
}
