
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-item-divider'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonEventCasing } from '../lib'

initialize()
defineCustomElement()

export type IonItemDividerProps = FixIonEventCasing<IonicJSX.IonItemDivider> &
  JSXBase.HTMLAttributes<HTMLIonItemDividerElement>

export function IonItemDivider(props: IonItemDividerProps) {
  //@ts-ignore
  return <ion-item-divider {...props} />
}
