
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-item-option'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonProps } from '../lib'

initialize()
defineCustomElement()

export type IonItemOptionProps = FixIonProps<IonicJSX.IonItemOption> &
  JSXBase.HTMLAttributes<HTMLIonItemOptionElement>

export function IonItemOption(props: IonItemOptionProps) {
  //@ts-ignore
  return <ion-item-option {...props} />
}
