
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-reorder'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonEventCasing } from '../lib'

initialize()
defineCustomElement()

export type IonReorderProps = FixIonEventCasing<IonicJSX.IonReorder> &
  JSXBase.HTMLAttributes<HTMLIonReorderElement>

export function IonReorder(props: IonReorderProps) {
  //@ts-ignore
  return <ion-reorder {...props} />
}
