
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-infinite-scroll-content'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonProps } from '../lib'

initialize()
defineCustomElement()

export type IonInfiniteScrollContentProps = FixIonProps<IonicJSX.IonInfiniteScrollContent> &
  JSXBase.HTMLAttributes<HTMLIonInfiniteScrollContentElement>

export function IonInfiniteScrollContent(props: IonInfiniteScrollContentProps) {
  //@ts-ignore
  return <ion-infinite-scroll-content {...props} />
}
