
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-ripple-effect'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonProps } from '../lib'

initialize()
defineCustomElement()

export type IonRippleEffectProps = FixIonProps<IonicJSX.IonRippleEffect> &
  JSXBase.HTMLAttributes<HTMLIonRippleEffectElement>

export function IonRippleEffect(props: IonRippleEffectProps) {
  //@ts-ignore
  return <ion-ripple-effect {...props} />
}
