
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-text'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonProps } from '../lib'

initialize()
defineCustomElement()

export type IonTextProps = FixIonProps<IonicJSX.IonText> &
  JSXBase.HTMLAttributes<HTMLIonTextElement>

export function IonText(props: IonTextProps) {
  //@ts-ignore
  return <ion-text {...props} />
}
