
// Auto-generated by scripts/generate.ts

import { defineCustomElement } from '@ionic/core/components/ion-menu'
import { initialize } from '@ionic/core/components'
import { type JSX as IonicJSX } from '@ionic/core'
import { JSX as JSXBase } from 'solid-js'
import { FixIonEventCasing } from '../lib'

initialize()
defineCustomElement()

export type IonMenuProps = FixIonEventCasing<IonicJSX.IonMenu> &
  JSXBase.HTMLAttributes<HTMLIonMenuElement>

export function IonMenu(props: IonMenuProps) {
  //@ts-ignore
  return <ion-menu {...props} />
}
