on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [release-npm]

name: Release to NPM
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: bun wsrun -t -c run build
      - run: npm publish --access=public --workspace packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
