on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release Management
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          target-branch: ${{ github.ref_name }}

      - name: Dispatch release event
        if: ${{ steps.release.outputs.releases_created }}
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: release-npm
